### ISSUE TITLE
Patient sample required is missing

### ISSUE THREAD

**Issue by Chavez34** [EIDSS/EIDSS7#10]
**Summary**
Patient sample required is missing

**To Reproduce**
1. Log in as ‘…mollyrue
2. Go to select the Accessioned sample of Michael Write
2. patient name is missing

**Expected behavior**
Patient sample required is missing 

Screenshots**

**Additional details:**
 - Build: 77
 - Script title (script-based): LAB04

**Issue severity**
Severity N/A

**Additional context**
N/A

**Comment by Chavez34** [comment]
![MR](https://user-images.githubusercontent.com/52667706/60828010-693c7880-a17f-11e9-8769-2409ee335c5d.PNG)

**Comment by jkkannan** [comment]
Closed in GAT remediation.  This was an issue with entering prerequisite data.
