### ISSUE TITLE
If it is possible the Date of Final Case Classification should be hidden because we not using this field. (Low priority)

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#1008]
### Country

Georgia

### Username

bakuradze

### Build number

7.0.427

### Language

Georgian

### Severity (MANDATORY)

4 - Low

### Module

Human

### Description of the steps to reproduce

If it is possible the Date of Final Case Classification may be hidden because we are not using this field. (Low priority)
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/780a9cbf-85fb-429f-a085-4a0126adb572)

**Comment by herashchenkoa** [comment]
TEST

**Comment by bakuradzebakuradze** [comment]
The issue is resolved
