### ISSUE TITLE
Deduplication Records NOT FOUND

### ISSUE THREAD

**Issue by srbatni** [EIDSS/EIDSS7#101]
**Summary**
No records exist for person to deduplicate.

**To Reproduce**
1. Log in as jefflisker
2. Go to Administration, Deduplication, Person Record
3. Click on Enter Daisy Monroe, search

**Expected behavior**
Two records for Daisy Monroe should exist to be deduplicated.  No records were found (see below).
**Screenshots**
![image](https://user-images.githubusercontent.com/52708365/60980957-4da1b100-a2ea-11e9-8659-0369502b76ef.png)

**Additional details:**
 - Build: 81
 - Script title (enter ad hoc if not script-based): HSP09

**Issue severity**
Severity (critical, major, minor, low): Critical

**Additional context**

**Comment by jkkannan** [comment]
Not reproducible.  Had tester attempt to reproduce and two records for Daisy Monroe appeared at this time.
