### ISSUE TITLE
Spot Map for the Botulism cases unable to display

### ISSUE THREAD

**Issue by shahina77** [EIDSS/EIDSS7#102]
**Summary**
Spot Map for the Botulism cases unable to display.  

**To Reproduce**
1. Log in as andrewpeters
2. Go to : 2018 Botulism Distribution in Imereti 
3. Click on :open map

**Expected behavior**

**Screenshots**

**Additional details:**
 - Build: 81
 - Script title (enter ad hoc if not script-based):

**Issue severity**
Severity (critical, major, minor, low):

**Additional context**
AVR08

**Comment by jkkannan** [comment]
Known issue in AVR.
