### ISSUE TITLE
ADM22 Update Human Disease List

### ISSUE THREAD

**Issue by Aj-Kakar** [EIDSS/EIDSS7#103]
**Summary**
It takes a little time to select all the different lab/sample test options so by the time you hit submit the system times out. This might just be a development environment issue but something to review. I tried twice to complete the script but both times it timed out.

This same issue impacted the testing of **ADM23** update to the animal disease list.

**To Reproduce**
1. Log in as rykermase
2. Go to admin > reference editor > diseases 
3. Click on add control to add new disease 
4. Fill in the information and select the lab options
5. Hit submit 

**Expected behavior**
System should allow enough time to complete the form and submit changes. 

**Screenshots**
None 

**Additional details:**
 - Build: 81
 - Script title (enter ad hoc if not script-based): ADM22 Update human Disease List

**Issue severity**
Severity (critical, major, minor, low): Low

**Comment by christhompson17** [comment]
Unable to reproduce in GAT or integration. (see disease added in GAT Environment- "Chesapeake Bay Crab Fever")

**Comment by jkkannan** [comment]
Related to ticket for  other modules also redirecting to log-in screen.
