### ISSUE TITLE
ILI Aggregate Form NOT FOUND

### ISSUE THREAD

**Issue by srbatni** [EIDSS/EIDSS7#104]
**Summary**
Under Human from main menu, ILI Aggregate Form was NOT an option to select from drop down menu. See below

**To Reproduce**
1. Log in as Diana Ross
2. Go to Human
3. Click on 

**Expected behavior**
ILI Aggregate Form should have been an option to select from drop down menu

**Screenshots**
![HPS14](https://user-images.githubusercontent.com/52708365/60981798-da993a00-a2eb-11e9-9ddd-79201db6a637.png)

**Additional details:**
 - Build: 81
 - Script title (enter ad hoc if not script-based): HPS14

**Issue severity**
Severity (critical, major, minor, low): Critical

**Additional context**

**Comment by christhompson17** [comment]
This is a confirmed bug in GAT. When using "dianaross", the "ILI Aggregate Form" does not display in the "Human" menu. However, when using "ellenskylar", the menu does display. This is a permission issue.
