### ISSUE TITLE
Search Results were not responsive to customized range

### ISSUE THREAD

**Issue by srbatni** [EIDSS/EIDSS7#106]
**Summary**
Entered a customized date range (6/1/2019 - 6/30/2019) and disease report listing that was returned was NOT narrowed down to just that search range.

**To Reproduce**
1. Log in as John Snow
2. Go to Human Disease Report
3. Click on Date Entered Range (6/1/2019 - 6/30/2019), hit search

**Expected behavior**
Only disease reports from June 2019 would be displayed in Kakheti and Telavi region.

**Screenshots**
![image](https://user-images.githubusercontent.com/52708365/60982544-32847080-a2ed-11e9-8555-ae4f44624bad.png)

**Additional details:**
 - Build: 81
 - Script title (enter ad hoc if not script-based): HPS16

**Issue severity**
Severity (critical, major, minor, low): Major

**Additional context**

**Comment by jkkannan** [comment]
Confirmed defect in GAT environment.
