### ISSUE TITLE
Deduplication Issues

### ISSUE THREAD

**Issue by srbatni** [EIDSS/EIDSS7#109]
**Summary**
Record 19....36 was supposed to say Daisy J Monroe, Record 19....37 was Daisy Monroe; both records say Daisy Monroe. When clicked the person ID the screen would not allow me to view either file, and grayed out.

**To Reproduce**
1. Log in as jefflisker
2. Go to Administration, Deduplication, person record, enter Daisy Monroe in name field
3. Click on Search 

**Expected behavior**
2 records should appear in disease list 
19....36 should be Daisy J Monroe
19....37 should be Daisy Monroe

**Screenshots**
![image](https://user-images.githubusercontent.com/52708365/60983147-55635480-a2ee-11e9-88e5-71fd402a353d.png)

![image](https://user-images.githubusercontent.com/52708365/60983385-affcb080-a2ee-11e9-800e-16cd1537020d.png)

**Additional details:**
 - Build: 81
 - Script title (enter ad hoc if not script-based): HSP09

**Issue severity**
Severity (critical, major, minor, low):

**Additional context**

**Comment by christhompson17** [comment]
2 issues to note here:
1. I can confirm what the tester experienced, that if you click on the Person ID it does lock everything out and this aspect is a bug. 
2. In reality, the user should select the check box to the right to avoid the above action from happening and try to re-run the script.
