### ISSUE TITLE
VPS 05 several failed log in and data entry and submission issues

### ISSUE THREAD

**Issue by jeanmrichards** [EIDSS/EIDSS7#110]
**Summary**
Several issues found trying to edit and submit avian disease report for white leghorn farm

**To Reproduce**
1. Log in as david robbins
2. Go to find avain disease report for white leghorn, then edit icon
3. unable to enter field accession ID
4. click on farm epi info; unable to enter any info
5. click on species investigation button; unable to enter any data 
6. click on vaccine info button; yes able to add info there as per script
7. click on samples button; yes able to add sample info per script but no option for ryan johnson as officer for samples 3-7 - have to choose blank or another officer
8. click on penside test; yes able to add first penside sample ok for AI antigen for sample 1 and the sample type and species pre-populated correctly but when I tried to entersecond penside test for ND antigen there was no info in sample type or species and it was gray and I could not edit. Tried to save anyway. Nothing. Tried to cancel, nothing. clicked X in top right of window and the box disappeared but then I wasnt able to add any new penside tests. 
9> click on case classification; unable to edit
10. click on review button; able to see the samples and one penside test i was able to enter during review but when I submit it kicks me back to penside test tab and cannot submit.
11. nothing to verify for step 25 in script since it didnt allow me to submit. 
[VPS04 many fails.zip](https://github.com/EIDSS/EIDSS7/files/3378316/VPS04.many.fails.zip)

+ 2 additional issues: step 2 logging in fail - error - problem occurred on website and step 4 when trying to search for avian record it kicked me out completely randomly and had to log in again and start over

**Expected behavior**

**Screenshots**

**Additional details:**
 - Build:81
 - Script title (enter ad hoc if not script-based):

**Issue severity**
Severity (critical, major, minor, low):major

**Additional context**

**Comment by jkkannan** [comment]
Multiple defects:
1) Intermittent kicking out of system (previously documented)
2) Issue with flex forms not displaying. Severity: CRITICAL
3) Penside tests--unable to add a second test due to missing attributes from sample; also unable to close out properly. Severity: CRITICAL
4) Unable to submit record; kicked back to earlier tab in disease report but no error message or field highlighted to indicate a missing or problematic field. Severity: CRITICAL
