### ISSUE TITLE
Deduplication: Phone number same for both records 

### ISSUE THREAD

**Issue by srbatni** [EIDSS/EIDSS7#111]
**Summary**
The work phone number should be different in the two records; it is the same so cannot select the correct number as noted in the script

**To Reproduce**
1. Log in as jefflisker
2. Go to Administration, Deduplication, person record, Daisy Monroe, deduplication
3. Click on Person Employment/School Information

**Expected behavior**
The phone numbers in the 2 records would differ, and you would select the correct one as listed in the script.
**Screenshots**
![image](https://user-images.githubusercontent.com/52708365/60983981-c6efd280-a2ef-11e9-864c-da75b42bf547.png)

**Additional details:**
 - Build: 81
 - Script title (enter ad hoc if not script-based): HPS09

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by christhompson17** [comment]
Not a bug, GAT data issue. BAs should modify the records to match the script and the tester can re-run the scenario.

**Comment by christhompson17** [comment]
GAT data has been updated. The tester can re-test.
