### ISSUE TITLE
Deduplication Step 21

### ISSUE THREAD

**Issue by srbatni** [EIDSS/EIDSS7#112]
**Summary**
When prompted if I wanted to merge the reports, I clicked yes but nothing happened. The screen would blink, but the message remained and I could not proceed further.

**To Reproduce**
1. Log in as jefflisker
2. Go to Administration, Deduplicate, person record, deduplicate, merge
3. Click on Yes

**Expected behavior**
The system would have accepted my selection to merge the records and I would receive a message stating "The record has been successfully saved."

**Screenshots**
![image](https://user-images.githubusercontent.com/52708365/60984576-cd327e80-a2f0-11e9-89d6-f4761c155caf.png)

**Additional details:**
 - Build: 81
 - Script title (enter ad hoc if not script-based): HSP09

**Issue severity (Optional)**
Severity (critical, major, minor, low): Critical

**Additional context**

**Comment by EBH2001** [comment]
Not reproducible in Integration and PreGAT build 83.1  

(Please See GitHub #125)
[HPS09_GitHub#112_Step20_Deduplicate_Person Record_NotReproducible.docx](https://github.com/EIDSS/EIDSS7/files/3387964/HPS09_GitHub.112_Step20_Deduplicate_Person.Record_NotReproducible.docx)
