### ISSUE TITLE
ADM27 - Manage Resource Fields 

### ISSUE THREAD

**Issue by Aj-Kakar** [EIDSS/EIDSS7#113]
**Summary**
I removed two fields from the Veterinary Action Report but unable to verify. No report is available under the Veterinary drop down menu. 

**To Reproduce**
1. Log in as rykermase
2. Go to resource editor update fields 
3. Go back to dashboard and look for the VETERINARY > AGGREGATE ACTIONS

**Expected behavior**
user should be able to review the report to verify removal of fields 

**Screenshots**
![Missing report](https://user-images.githubusercontent.com/52667376/60984927-881b4600-a30a-11e9-867f-9d31d3eeb770.png)

**Additional details:**
 - Build: 81
 - Script title (enter ad hoc if not script-based): ADM27 - Manage Resource Fields 

**Issue severity (Optional)**
Low

**Comment by christhompson17** [comment]
Unable to reproduce, however it is directly linked to #116. Certain menu items are randomly disappearing. 

The tester logged out and logged back in to continue the scenario testing.
