### ISSUE TITLE
VPS06 unable to add record in existing lab test

### ISSUE THREAD

**Issue by jeanmrichards** [EIDSS/EIDSS7#114]
**Summary**
when attempting to add record in each lab test (x6) nothing happens when you click on the record icon so you cant enter data per script in all associated steps 8-19

**To Reproduce**
1. Log in as david robbins
see attached

**Expected behavior**

**Screenshots**

**Additional details:**
 - Build:81
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):major
[VPS06 add test record issue.zip](https://github.com/EIDSS/EIDSS7/files/3378397/VPS06.add.test.record.issue.zip)

**Additional context**

**Comment by christhompson17** [comment]
Unable to reproduce, however agree this is a bug after seeing other intermittent issues while doing Ad Hoc.
