### ISSUE TITLE
VPS06 unable to change case classification or submit avian disease report

### ISSUE THREAD

**Issue by jeanmrichards** [EIDSS/EIDSS7#115]
**Summary**
unable to edit the case classification and also unable to submit after reviewing (nothing to review since I couldnt edit anything in lab tests). when you try to submit it kicks you back to lab test button. unable to verify anything since nothing was submitted.

**To Reproduce**
1. Log in as david robbins
2. Go to search for avian disease recod for AI on red cornish farm
3. Click on see above in summary

**Expected behavior**

**Screenshots**

**Additional details:**
 - Build:81
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):major

**Additional context**

**Comment by jkkannan** [comment]
Check roles and permissions; related to other ticket from tester about being kicked back in the report when trying to submit.

**Comment by EBH2001** [comment]
The changing of the Case Classification was not reproducible in Integration or PreGAT 83.1 build.  However, confirmed that there was no submit button.

**PLEASE SEE ATTACHMENT
[VPS06_GitHub#115_Lab_avian_Influenza_SubmitDefectReproduced.docx](https://github.com/EIDSS/EIDSS7/files/3388010/VPS06_GitHub.115_Lab_avian_Influenza_SubmitDefectReproduced.docx)
**
