### ISSUE TITLE
ADM28 - Reference editor 

### ISSUE THREAD

**Issue by Aj-Kakar** [EIDSS/EIDSS7#117]
**Summary**
Please review the script unable to determine the actual test. Script is testing if user are able to modify accessory code to include livestock and avian. System doesnt allow you to select two options and also I can't save anymore, please review screen shot.

**To Reproduce**
1. Log in as rykermase
2. Go to admin > reference editor > species 
3. Click on OTHER and update the field 

**Expected behavior**
Not sure 

**Screenshots**
![Problem saving](https://user-images.githubusercontent.com/52667376/60985439-80a86c80-a30b-11e9-86df-194769af2d6b.png)

**Additional details:**
 - Build: 81
 - Script title (enter ad hoc if not script-based): ADM28 - Reference editor 

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by jkkannan** [comment]
Look at script/have QA review.  Severity not yet known; not yet reproduced.
