### ISSUE TITLE
Human Aberration Analysis NO Charts, Summary generated

### ISSUE THREAD

**Issue by srbatni** [EIDSS/EIDSS7#118]
**Summary**
Entered all the information in Step 4 of ABE01 and hit the analyze tab, the system would give the circle as if running however no charts or summary reports were generated and automatically opened in new windows. I tried several times and it failed each time.

**To Reproduce**
1. Log in as ignazsemmelweis
2. Go to Human Aberration Analysis
3. Click on View report after parameters are entered

**Expected behavior**
Summary section report and charts should have popped up in new windows.

**Screenshots**
![image](https://user-images.githubusercontent.com/52708365/60985948-46cb6c00-a2f3-11e9-8782-820c0cecc2e0.png)

**Additional details:**
 - Build: 81
 - Script title (enter ad hoc if not script-based): ABE01

**Issue severity (Optional)**
Severity (critical, major, minor, low): Critical

**Additional context**

**Comment by jkkannan** [comment]
Report displays in Edge but not in Chrome.

**Comment by EBH2001** [comment]
This is reproducible in both Integration and PreGAT.  Report does not display in Build 83.1

**PLEASE SEE ATTACHMENT
[ABE01_GitHub#118_NoAberrationAnalysisRptDisplay.docx](https://github.com/EIDSS/EIDSS7/files/3389356/ABE01_GitHub.118_NoAberrationAnalysisRptDisplay.docx)
**

**Comment by jkkannan** [comment]
Closed during GAT remediation.
