### ISSUE TITLE
Error when trying to login to EIDSS from Icon on Main Menu

### ISSUE THREAD

**Issue by srbatni** [EIDSS/EIDSS7#119]
**Summary**
Tried to load EIDSS and received an error message

**To Reproduce**
1. Log in as N/A
2. Go to 
3. Click on 

**Expected behavior**
EIDSS Login page should be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/52708365/60986297-028c9b80-a2f4-11e9-9e3a-5ce0c8134da8.png)

**Additional details:**
 - Build: 81
 - Script title (enter ad hoc if not script-based): ABE01

**Issue severity (Optional)**
Severity (critical, major, minor, low): Critical

**Additional context**

**Comment by jkkannan** [comment]
Closing because error is due to environment and use of a shortcut icon.
