### ISSUE TITLE
User Account DWashington Does NOT exist

### ISSUE THREAD

**Issue by srbatni** [EIDSS/EIDSS7#120]
**Summary**
The EIDSS account for DWashington REP01 does not exist.

**To Reproduce**
1. Log in as 
2. Go to 
3. Click on 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/52708365/60987167-e38f0900-a2f5-11e9-94a9-7551ca00016c.png)

**Additional details:**
 - Build: 81
 - Script title (enter ad hoc if not script-based): REP01

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by jkkannan** [comment]
Closed during GAT remediation.  Purely a script issue.
