### ISSUE TITLE
ADHOC - Navigation Format

### ISSUE THREAD

**Issue by Aj-Kakar** [EIDSS/EIDSS7#121]
**Summary**
Navigation format, font, color scheme, labeling are not consistent 

**To Reproduce**
1. Log in as rykermase
2. Review navigation
3. Go to Lab > samples
4. Review navigation

**Expected behavior**
Navigation formatting should be consistent

**Screenshots**
![Screenshot A](https://user-images.githubusercontent.com/52667376/60987674-1fcf6300-a310-11e9-84bd-0ece3a6d3866.png)
![Screenshot B](https://user-images.githubusercontent.com/52667376/60987691-23fb8080-a310-11e9-8582-eb6af3d1f17f.png)

**Additional details:**
 - Build: 81
 - Script title (enter ad hoc if not script-based): ADHOC

**Issue severity (Optional)**
Low

**Comment by christhompson17** [comment]
Confirmed, this is related to #107 and is being sent to the front-end developers for CSS formatting.

**Comment by jkkannan** [comment]
Closing out as duplicate.
