### ISSUE TITLE
Outbreak Session/Summary Not Created

### ISSUE THREAD

**Issue by srbatni** [EIDSS/EIDSS7#122]
**Summary**
Entered information for a new outbreak following Step 5 in the script but when clicked submit, nothing happened and an outbreak summary screen and new outbreak ID were NOT created.

**To Reproduce**
1. Log in as 
2. Go to 
3. Click on 

**Expected behavior**

**Screenshots**

**Additional details:**
 - Build: 81
 - Script title (enter ad hoc if not script-based): OM01

**Issue severity (Optional)**
Severity (critical, major, minor, low): Critical

**Additional context**

**Comment by EBH2001** [comment]
Not reproducible in Integration and PreGA 83.1 build.

**PLEASE SEE ATTACHMENT
[OM01_GitHub#122_Create Outbreak Session_NotReproducible.docx](https://github.com/EIDSS/EIDSS7/files/3387895/OM01_GitHub.122_Create.Outbreak.Session_NotReproducible.docx)
**
