### ISSUE TITLE
Outbreak Record for CCHF Does NOT Exist

### ISSUE THREAD

**Issue by srbatni** [EIDSS/EIDSS7#123]
**Summary**
The outbreak file I was asked to select does not exist (See below)

**To Reproduce**
1. Log in as michaelwinston
2. Go to Outbreak Outbreak
3. Click on Outbreak Management List (pages 1 and 2)

**Expected behavior**
A file for CCHF should have been displayed in the outbreak management list screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/52708365/60988894-809f7100-a2f9-11e9-9c67-26b7c8c90c7d.png)

![image](https://user-images.githubusercontent.com/52708365/60988922-914fe700-a2f9-11e9-96e2-40ba758a0f18.png)

**Additional details:**
 - Build: 81
 - Script title (enter ad hoc if not script-based): OM02

**Issue severity (Optional)**
Severity (critical, major, minor, low): Major, data doesn't exist

**Additional context**

**Comment by christhompson17** [comment]
Confirmed that data for OMM was not properly moved to the GAT environment. Tester is standing down until data is moved.

**Comment by jkkannan** [comment]
Closed during GAT remediation.  Data issue with entering prerequisite data during GAT.
