### ISSUE TITLE
VPS 07 results summary and interpretation 

### ISSUE THREAD

**Issue by jeanmrichards** [EIDSS/EIDSS7#124]
**Summary**
after creating a new lab test result for the positive AI PCR Matrix Gene  (search white turkey farm) the script says to click on new record button to create new results summary and interpretation which I can do but several fields are missing including test name, test category, result, sample type and then the script says step 9 that the expected result is that the lab test record became disabled but how do I check that? so I skipped to step 10 and chose "rule in" and then saved it, although there is an issue that it says ryan, ryan (or russell, russell, or ryker, ryker) when trying to reproduce still logged in as ryan johnson?) for the interpreted by instead of ryan johnson. After saving the rule in window I tried to test whether the lab test record is disabled but still not sure how to tell. i can still create a new record with rule in rule out info and then delete it, so maybe it's not disabled as it should be? see step recorder.

Also had some issue that were not reproduced. #1 Sometimes when I tried to delete a lab record that had an associated result summary it made me delete the result summary first before deleting the lab record, which makes sense, but when i deleted the result summary i still could not delete the lab record unless i hit review and submit and went back in to find the record, then I could delete the lab record. When i tried it again, it allowed me to delete both in the same session (worked right 1/5 times tried). #2 sometimes when I tried to submit after review, it would say "are you sure you want to delete this record" or "do you want to cancel all changes and close this form" rather than giving me the normal window after submit that says "return to record" or return to dashboard.

**To Reproduce**
1. Log in as ryan johnson
2. Go to 
3. Click on 

**Expected behavior**

**Screenshots**

**Additional details:**
 - Build:81
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):not sure
[VPS 07 results summary and interpretation.zip](https://github.com/EIDSS/EIDSS7/files/3378642/VPS.07.results.summary.and.interpretation.zip)

**Additional context**

**Comment by jkkannan** [comment]
Need to split into
1: Script error (fields discrepancy)
2. Name is a) repeated (Ryan, Ryan) but also changing to others who are not logged-in user.  Severity: MAJOR
3. Script or bug: Unclear if lab record is supposed to be disabled and how to verify.  TO BE TRIAGED
4. Variable parent-child relationship between lab record and result summary; does not always allow deletion as it should. Severity: MAJOR
5. Incorrect pop-up messages: "Do you want to delete" rather than "return"; bug was intermittent. Severity: MINOR

**Comment by aatmns** [comment]
Defects are confirmed and reported to the internal TFS system for corrective actions.
