### ISSUE TITLE
Deduplication Error

### ISSUE THREAD

**Issue by srbatni** [EIDSS/EIDSS7#125]
**Summary**
I successfully followed the steps to deduplicate records for Daisy J Monroe. However, when going back to verify that the correct record was present, 3 records instead of 1 now exist. 

**To Reproduce**
1. Log in as jefflisker
2. Go to Human Person Record, Daisy J Monroe
3. Click on Search

**Expected behavior**
Only one record PER19...36 should exist. 

**Screenshots**
![image](https://user-images.githubusercontent.com/52708365/60990673-ce1ddd00-a2fd-11e9-9648-e3dfc2770227.png)

**Additional details:**
 - Build: 81
 - Script title (enter ad hoc if not script-based): HPS09

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by EBH2001** [comment]
Not reproducible in Integration and PreGAT.  Slight report count mismatch in environments but was able to complete the script.
[HPS09_GitHub#125_Deduplicate_Person Record_NotReproducible.docx](https://github.com/EIDSS/EIDSS7/files/3387862/HPS09_GitHub.125_Deduplicate_Person.Record_NotReproducible.docx)


**PLEASE SEE ATTACHMENT**

**Comment by jkkannan** [comment]
Closed during GAT remediation.
