### ISSUE TITLE
Disclaimer hyperlink causes error

### ISSUE THREAD

**Issue by jkkannan** [EIDSS/EIDSS7#128]
**Summary**
Clicking on the disclaimer at the bottom of any page causes an error.

**To Reproduce**
1. Click on disclaimer from any where after the log-in screen.

**Expected behavior**
Expect disclaimer or, if disclaimer is not yet ready, then disable hyperlink for the time being.

**Screenshots**
![Disclaimer_error message](https://user-images.githubusercontent.com/35157698/61048493-f2d28d00-a3af-11e9-98b2-cd2efc277da9.PNG)
**Additional details:**
 - Build: 81.0
 - Script title (enter ad hoc if not script-based): Ad hoc

**Issue severity (Optional)**
Severity (critical, major, minor, low):  Minor

**Additional context**

**Comment by aatmns** [comment]
Retested and validated the defect.
