### ISSUE TITLE
[BUG] Prepopulated data fails to appear in search HPS

### ISSUE THREAD

**Issue by shahina77** [EIDSS/EIDSS7#13]
**Summary**
Prepopulated data fails to display for Region and Rayon
**To Reproduce**
1. Log in as ‘…’
2. Go to '...'

**Expected behavior**

Screenshots**

**Additional details:**
 - Build: 77
 - HPSO6 PS
![HPSO6](https://user-images.githubusercontent.com/52667472/60828638-e6b4b880-a180-11e9-8034-79c6eed5a625.png)
 (enter ad hoc if not script-based):

**Issue severity**
Severity (critical, major, minor, low): Minor

**Additional context**

**Comment by jkkannan** [comment]
Closing out as duplicate of #7
