### ISSUE TITLE
 Does not display Veterinary Active Surveillance Campaign in the edit mode

### ISSUE THREAD

**Issue by Chavez34** [EIDSS/EIDSS7#130]
**Summary**
 Does not display Veterinary Active Surveillance Campaign in the edit mode

**To Reproduce**
1. Log in as michaelwinston
2. Go to Veterinary
3. Click on Active Surveillance Campaign
4. Enter Campaign Type: Study, Campaign Status: New and Campaign Disease: Brucellosis abortus
5. Select Search: does not display Veterinary Active Surveillance Campaign in the edit mode

**Expected behavior**
Display Veterinary Active Surveillance Campaign in the edit mode

**Screenshots**
![image](https://user-images.githubusercontent.com/52667706/61058090-92017f80-a3c4-11e9-922a-608a75bb2fe8.png)

**Additional details:**
 - Build: 82.2
 - Script Title: VAS05, Closing Veterinary Active Surveillance Campaign for Brucellosis

**Issue severity (Optional)**
Severity: Critical

**Additional context**
None

**Comment by aatmns** [comment]
Unable to replicate the defect.
The internal system correctly filtered the record based on three search criteria:
![23](https://user-images.githubusercontent.com/32458032/61072947-58d80800-a3e2-11e9-806b-9979e0b8604f.PNG)


Need to retest at the GAT station.
