### ISSUE TITLE
VAS04 Unable to save species and sample update

### ISSUE THREAD

**Issue by Aj-Kakar** [EIDSS/EIDSS7#131]
**Summary**
I am getting multiple errors when updating the species and sample types.
-unable to delete the record for cattle
-unable to modify cattle record 

**To Reproduce**
1. Log in as michaelwinston
2. Go to vet > active surveillance 
3. Search all open campaign 
4. Select 2019 Fall Brucellosis surveillance campaign report
5. scroll down to edit the cattle record or try to delete it 

**Expected behavior**
user should be able to delete or modify the record 

**Screenshots**
[unable to save species and sample updates.zip](https://github.com/EIDSS/EIDSS7/files/3382533/unable.to.save.species.and.sample.updates.zip)

**Additional details:**
 - Build: 82.2
 - Script title (enter ad hoc if not script-based): VAS04

**Issue severity (Optional)**
Severity (critical, major, minor, low): Major

**Comment by aatmns** [comment]
Unable to replicate the defect. 
The internal system found and deleted the active surveillance campaign record SCV0000190098 correctly.
![5](https://user-images.githubusercontent.com/32458032/61071520-4d371200-a3df-11e9-9aeb-f4515bc3ff22.PNG)

Searched for the specific campaign record via Campaign ID and using search criteria in the Scenario. The record was deleted.
![7](https://user-images.githubusercontent.com/32458032/61071566-6dff6780-a3df-11e9-956e-9bb8413483d8.PNG)

Need to retest at the GAT station.

**Comment by aatmns** [comment]
Unable to replicate the defect. 
The internal system allowed me to edit and delete species/samples records from the saved Active Surveillance Campaign.
Three records of the saved ASCampaign with SCV190107:
![11](https://user-images.githubusercontent.com/32458032/61072090-93d93c00-a3e0-11e9-8716-bcaa5dc2f9c2.PNG)

Removed Duck record:
![12](https://user-images.githubusercontent.com/32458032/61072209-d3078d00-a3e0-11e9-96f1-7081b46c3205.PNG)

Removed Chicken record:
![13](https://user-images.githubusercontent.com/32458032/61072603-a142f600-a3e1-11e9-8b6d-eeb7ebced413.PNG)

Removed Buffalo record:
![14](https://user-images.githubusercontent.com/32458032/61072648-b6b82000-a3e1-11e9-8bd0-891dde7862e1.PNG)
