### ISSUE TITLE
VPS 08 errors ALL

### ISSUE THREAD

**Issue by jkkannan** [EIDSS/EIDSS7#133]
**Summary**
multiple issues with validation and results summary and interpretation boxes

**To Reproduce**
1. Log in as michael winston
2. Go to Avian Influenza report for Grey Cornish farm
3. Issue #1 when you go to lab tests section the report says probable and the script says it should be confirmed. I tried to change it to confirmed to try to see if it fixed the bugs with validation but when I did that (the first time) it removed all the edit boxes from lab tests and results summary sections, when I did it again after changing it back to probable (2nd time) it removed all the boxes (there were 3 where the edit symbol was, but then there were 0)
4. Issue #2 Go down to results summary section and click edit for the first one (19-021). Script says the box should have fields for species, disease, test name, category, result, sample type, sample ID but they are all missing. (this is the same for all results summary sections in script)
5. Issue #3 When you check the validated control the date validated works and is today's date but the validated by is gray and not populated with user's name. this is for 19-021
6. Issue #4 In the results summary box where you are supposed to check validated box, the interpreted by box is pulling two first names from random users, not first and last
7. When you switch between probable and confirmed and the review, submit each time, it doesnt respond by switching edit and non edit functions for the lab tests and results summary sections. It gets confused and breaks and ultimately you have to go out and search all over again to reset it.
8. when you try to validate the rest in the list 19-022, 19-023 etc the validated control is not editable - red circle. maybe because I saved and submitted for 19-021 already? 
9. When you make any changes in the results summary box, like checking the validated box, and try to save, the save button doesnt work. see steps recorder. 
[VPS 08 unable to validate result summary and interpretation second lab test.zip](https://github.com/EIDSS/EIDSS7/files/3382473/VPS.08.unable.to.validate.result.summary.and.interpretation.second.lab.test.zip)
[VPS 08 unable to validate result summary and interpretation.zip](https://github.com/EIDSS/EIDSS7/files/3382474/VPS.08.unable.to.validate.result.summary.and.interpretation.zip)
10. when attempting to create a new linked avian disease report it does create the new report but the disease is copied over from the parent - it should have been pullorum but it was AI so the disease from the lab test didnt copy into the child record, the disease from the parent report copied.
11. It wasnt possible to check whether the farm epi or clinical info were copied into child report  because there was not any data in the parent. 
12. the lab tests for turkeys were supposed to be moved per the script from parent to child but they still exist in both, which makes sense. Maybe script error? Interpretation records are also still in both.
13. After reviewing and saving the child disease report it says you should click ok to be back in the parent report but it's still in the child.
14. after searching and finding the parent again i changed it to closed, reviewed, saved, it worked, but the scripts want me to return to dashboard and see epizootologist dashboard and I see users and positions
15. unable to verify pullorum record as per script becuase it was created as AI from the parent record. 

**Expected behavior**

**Screenshots**

**Additional details:**
 - Build: 82.2
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by aatmns** [comment]
1a. Scenario omission to set the "Case Classsification"= Confirmed.
1b. Was not able to replicate defect description with changes of "Case Classification" values.  Grids in the "Lab Tests" and "Results Summary and Interpretations" did not change when changed to "not a case", "probable", "suspect", etc.
Need to retest at the GAT station.

**Comment by aatmns** [comment]
2a. Retested in the internal environment. The Results Summary and Interpretation grid does display all requested fields:
Species, Disease, Test Name, Test Category, Test Result, Sample Type, Field Sample ID, Rule in/Rule out, Comments:
![1](https://user-images.githubusercontent.com/32458032/61068435-04c82600-a3d8-11e9-9746-f445f7508517.PNG)

and scrolling horizontally: Date Interpreted, Interpreted by, Validated, Date Validated, Validated by and action icons:
![2](https://user-images.githubusercontent.com/32458032/61068527-4062f000-a3d8-11e9-93f0-05c4560f755e.PNG)
Need to retest at the GAT station.

**Comment by aatmns** [comment]
3. Retested and confirmed defects.  
a. The Comment section is still disabled. This section needs to be enabled for a user to provide any input.
b. Validated by is disabled and user name is not auto-populated. The user name of validator needs to be entered.
c. Species and Disease values are missing from two fields. Need to be pre-populated accordingly for a user to visually approve this Interpretation record.
![3](https://user-images.githubusercontent.com/32458032/61068892-207ffc00-a3d9-11e9-9d0f-7c0d4d22b3be.PNG)

**Comment by aatmns** [comment]
4. Retested and validated. 
Defect with auto-populating first name, last name style in the Interpreted By field.
![4](https://user-images.githubusercontent.com/32458032/61069065-7fde0c00-a3d9-11e9-8518-a9a6ef5b9257.PNG)

**Comment by aatmns** [comment]
5. Retested and validated defect. 
Interpreted laboratory test results are not available for editing.

**Comment by aatmns** [comment]
6. (8) Not able to validate presented condition due to the defect 5.

**Comment by aatmns** [comment]
7.(9) Retested and validated.
Defect in saving changes to interpretation records.

**Comment by aatmns** [comment]
8. (10) Retested and validated defects:
a. Linked Avian Disease Report "Disease" needs to be set to 'Pullorum Disease"
b. The business rule dictated to move unique samples from the Session to the Avian Disease Report with intention not to create duplicate records of a unique physical sample/laboratory test for sample/test count reporting.

**Comment by aatmns** [comment]
9. (11) That is correct behavior of creation of a linked animal disease report. The Veterinary active surveillance session only collects samples and the linked Disease Report is intended to conduct additional field follow-up investigations (if such decision is rendered) to confirm or reject the presence of sick animals.

**Comment by aatmns** [comment]
10. (12) Recommendation to treat this as a defect as the functional requirement defines business rules for copying and/or moving appropriate records.
Interpretation records need to be moved to the linked animal disease report.

**Comment by aatmns** [comment]
(13). Retested and validated as a defect. 
The system needs to provide ability to return to the parent Veterinary active surveillance session to perform any other actions or finalize editing of the main record.

**Comment by aatmns** [comment]
(14) The intent to return to dashboard is to close the existing record of interest, so the validation step would not pull any remains of previous screens.

**Comment by aatmns** [comment]
15. Recommend to treat this a defect as the system did not create the Pullorum Disease report but Avian Influenza disease report.
