### ISSUE TITLE
When clicking previous at bottom of a case file, system would not allow backwards navigation

### ISSUE THREAD

**Issue by srbatni** [EIDSS/EIDSS7#134]
**Summary**
Opened a case report, clicked on previous as it was the wrong report, but the system would not take me back to the previous screen.

**To Reproduce**
1. Log in as: adamanders 
2. Go to: Outbreak Sessions, Cases 
3. Click on: Any person ID hyperlink, previous 

**Expected behavior**
Clicking on the previous link should have brought me back from outbreak case report screen to the list of cases.

**Screenshots**
![image](https://user-images.githubusercontent.com/52708365/61061182-a045a080-a3b0-11e9-940b-073a6e9f8a54.png)

**Additional details:**
 - Build: 82.2
 - Script title (enter ad hoc if not script-based): Ad hoc from OM3

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by aatmns** [comment]
Recreated in the internal environment. The control "previous" needs to be removed. 
The "Cancel" control is intended to return user to the Outbreak Session main record.
"Previous" control is redundant.
