### ISSUE TITLE
Selection of Return to Dashboard does not  display the Chief Epizootologist 

### ISSUE THREAD

**Issue by Chavez34** [EIDSS/EIDSS7#135]
**Summary**
Selection of Return to Dashboard does not display the Chief Epizootologist 

**To Reproduce**
1. Log in as janemoore
2. Go to Veterinary 
3. Click on Active Surveillance Campaign - Veterinary Active Surveillance Campaign search screen is displayed
4. Select and enter search criteria
5. Select search control - Veterinary Active Surveillance Campaign edit mode is displayed
6. Select + a new Livestock Active Surveillance Session is displayed
7. Session is expanded with all fields visible
8. Enter requested information and system displayed entered data
9 Select next button and the Veterinary Active Surveillance Session in review mode
10. Select Submit is successfully saved
11. Select Return to Dashboard - no confirmation message is displayed and the Chief Epizootologist dashboard is not displayed.

**Expected behavior**
Return to Dashboard displays the Chief Epizootologist

**Screenshots**
![image](https://user-images.githubusercontent.com/52667706/61061294-f4a94a00-a3c9-11e9-8f75-6b4e34c80da1.png)

**Additional details:**
 - Build: 82.2
 - Script title: VAS06, Linked Livestock Active Surveillance Session in Gurjaani Rayon

**Issue severity (Optional)**
Severity:  Major

**Additional context**
None
r context about the problem here.

**Comment by aatmns** [comment]
Not able to replicate the defect.
Created connected AS Session according to the VAS06.
![33](https://user-images.githubusercontent.com/32458032/61073375-45796c80-a3e3-11e9-90ae-b02e3ae0036e.PNG)

Submitted the Session record and selected "Return to Dashboard":
![34](https://user-images.githubusercontent.com/32458032/61073414-60e47780-a3e3-11e9-82ea-df5f6498aaa3.PNG)

The system correctly displayed Jane Moore's dashboard:
![35](https://user-images.githubusercontent.com/32458032/61073460-7e194600-a3e3-11e9-83b3-366fdfb5c1be.PNG)


Need to retest at the GAT station.

**Comment by jkkannan** [comment]
Intermittent dashboard issue; linked to others of the same type.
