### ISSUE TITLE
VAS09 Request: "error" and prepopulated session ID

### ISSUE THREAD

**Issue by Aj-Kakar** [EIDSS/EIDSS7#136]
**Summary**
When accessing the vet active surveillance session page and navigating throughout the system I keep receiving a "Request error". Also, when accessing the vet active surveillance session page the session ID was prepopulated, not sure if that was the intent. 

**To Reproduce**
1. Log in as michaelwinston
2. Go to vet > active surveillance session 

**Expected behavior**

**Screenshots**
![Active surveillance screenshot](https://user-images.githubusercontent.com/52667376/61062716-b4979680-a3cc-11e9-9f47-21d760342536.png)

**Additional details:**
 - Build: 82.2
 - Script title (enter ad hoc if not script-based): VAS09

**Issue severity (Optional)**
Severity (critical, major, minor, low): LOW

**Comment by aatmns** [comment]
Attempted to replicate in two internal environments. The message was not experienced in any of those.
However, I've seen this message a few time on the GAT environment.
Need to investigate further the nature and origin of that message.

**Comment by jkkannan** [comment]
Second part is based on a requirement to save and prepopulate with prior search fields.  Has been source of feedback throughout GAT; may require further discussion with submitter on alternate ways to achieve same goal (i.e. list of recently used terms).
