### ISSUE TITLE
Human Aberration Analysis

### ISSUE THREAD

**Issue by srbatni** [EIDSS/EIDSS7#137]
**Summary**
Logged in as Ignaz Semmelweis didn't work. Logged in as Adam Anders and worked. However, received an error message when selected Human Aberration Analysis (see below).

**To Reproduce**
1. Log in as: Adam Anders 
2. Go to: Human, Aberration Analysis 
3. Click on: N/A

**Expected behavior**
Report viewer with Analysis Parameters displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/52708365/61064172-1dbfdf80-a3b6-11e9-9cd6-0bf66a441a0c.png)

**Additional details:**
 - Build: 82.2
 - Script title (enter ad hoc if not script-based): ABE01

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by jkkannan** [comment]
Closed during GAT remediation. Report appears when logged in as admin user.
