### ISSUE TITLE
Select Add button from the detailed Animals and Samples section is missing

### ISSUE THREAD

**Issue by Chavez34** [EIDSS/EIDSS7#138]
**Summary**

Select Add button from the detailed Animals and Samples section is missing

**To Reproduce**
1. Log in as davidrobbins
2. Go to number 18
3.  "Add" button from the detailed Animals and Samples section i missing;  unable to proceed with subsequent steps.

**Expected behavior**
Selection of "Add" button populates Detailed Animal and Sample modal window to enter or view information requested

**Screenshots**

![image](https://user-images.githubusercontent.com/52667706/61064669-3a691100-a3d0-11e9-86f2-bcdf1df265fb.png)

**Additional details:**
 - Build: 82.2
 - Script title:   VA07, Detailed sample collection  of Livestock Active Surveillance Session in Gurjaani Rayon

**Issue severity (Optional)**
Severity: Major

**Additional context**
None

**Comment by aatmns** [comment]
Retested in the internal environment. Was not able to replicate. Control 'Add' is present after adding one sample.
![138-1](https://user-images.githubusercontent.com/32458032/61066544-c2044f00-a3d3-11e9-8fe8-5d999cc9440c.PNG)

Added another sample - control "Add" is present.
![138-2](https://user-images.githubusercontent.com/32458032/61066599-d6484c00-a3d3-11e9-83f7-44484f82d132.PNG)

Need to retest at the GAT machine.
