### ISSUE TITLE
VPS 09 results summary/interpretation - does not disable after adding interpretation

### ISSUE THREAD

**Issue by jkkannan** [EIDSS/EIDSS7#139]
**Summary**
after adding a sample interpretation  it should disable to prevent another sample interpretation but that doesnt happen

**To Reproduce**
1. Log in as michael winston
2. Go to lab samples and then results summary and interpretation
3. Click on 

**Expected behavior**

**Screenshots**

**Additional details:**
 - Build: 82.2
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by aatmns** [comment]
Retested and validated the defect.
