### ISSUE TITLE
Error submitting new employee ADM [BUG]

### ISSUE THREAD

**Issue by Aj-Kakar** [EIDSS/EIDSS7#14]
**Summary**
Unable to add new employee - upon submitting a new employee to the system I am receiving an error message, please see screen shot. However, when double checking the employee list, the employee submission of "thomasjones" seems to be in the system.

**To Reproduce**
1. Log in as "ellenskylar". 
2. Select **Employees** under the **Administration** drop down menu.
3. Click on **New** on the **Employees** Details page.
4. Enter employee details and click continue.
5. Enter the employee login information and click continue.
6. Select group and click continue.
7. Review system functions and click continue.
8. Review all employee details and click submit.
9. This is where the error occurs, please review the screen shot.

**Expected behavior**
Unable to add new employee, however, the employee still shows in the employee list.

Screenshots**
![Error submitting New Employee](https://user-images.githubusercontent.com/52667376/60828704-195eb100-a181-11e9-83bc-85f9ccb6f4cb.PNG)

**Issue severity**
Major

**Build**
77

**Comment by aatmns** [comment]
7/12/2019, Anatoliy
Not able to replicate in the internal environment.
The system operates as designed.
