### ISSUE TITLE
VPS 09 validation is being logged when validation box is not checked

### ISSUE THREAD

**Issue by jkkannan** [EIDSS/EIDSS7#140]
**Summary**
when you are trying to add "rule in" into results summary and interpretation box, the validation box is not checked but the validation date is entered as today and grayed out and the validated by is also populated and grayed out when I am not validating the result. 

**To Reproduce**
1. Log in as michael winston
2. Go to loab samples then results summary and interpretation
3. Click on 

**Expected behavior**

**Screenshots**

**Additional details:**
 - Build: 82.2
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by aatmns** [comment]
Retested and validated defect.
