### ISSUE TITLE
AVR04: 'and (+)' sign  in the Edit filters window was disabled when creating the new layout  

### ISSUE THREAD

**Issue by shahina77** [EIDSS/EIDSS7#141]
**Summary**

**To Reproduce**
1. Log in as andrewpeters
2. Go to pivot grid 
3. Click on Edit Filter

**Expected behavior**
User should be able to customize grid fields
![avr04_1](https://user-images.githubusercontent.com/52667472/61069275-e6fbc080-a3d9-11e9-8aa4-406d6085e8cf.png)

**Screenshots**

**Additional details:**
 - Build: 82.2
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by aatmns** [comment]
Not able to replicate on local machine with standalone AVR application.
However, did observed defective behavior when the user is not able to create a layout from custom queries. Still, the AVR correctly created layout from Standard Queries. Need to investigate current setup and corresponding AVR services.
A screenshot with technical information is passed to the Development Team.
