### ISSUE TITLE
Facility Details Tab will not allow me to enter new information

### ISSUE THREAD

**Issue by srbatni** [EIDSS/EIDSS7#142]
**Summary**
Retesting HPS03 both as Russell Peters and as Adam Anders; in both instances the name of facility patient first sought care box was greyed out and I couldn't enter new information even though the script prompted me to do so.

**To Reproduce**
1. Log in as: russellpeters or adamanders 
2. Go to: Human, Disease Report, Andrew Taylor 
3. Click on Report ID and Facility Details Tab

**Expected behavior**
User should be able to add a facility name where patient first sought care and hospital name.
**Screenshots**
![image](https://user-images.githubusercontent.com/52708365/61069872-228a9080-a3c2-11e9-8941-4be3a44bb35f.png)

**Additional details:**
 - Build: 82.2
 - Script title (enter ad hoc if not script-based): HPS03

**Issue severity (Optional)**
Severity (critical, major, minor, low): 

**Additional context**

**Comment by aatmns** [comment]
Unable to replicate the defect.
The record HUM190022 opened correctly with all fields editable in the Clinical Information: Facility Details:
![44](https://user-images.githubusercontent.com/32458032/61075492-1a454c00-a3e8-11e9-82c7-81880dca6135.PNG)

Need to verify at the GAT station.
