### ISSUE TITLE
VAS13 unable to find session in search, unable to cancel changes or close record

### ISSUE THREAD

**Issue by jeanmrichards** [EIDSS/EIDSS7#143]
**Summary**
script asks to search for active surv session, choose ssv190102, it does not exist (issue 1), so I chose one that does exist and continued to check for fields that should be entered. Most are populated but campaign type is blank and should be active (issue 2). Script asks to click cancel and see message " do you want to cancel changes and close record?" and when i click cancel i dont see a message (issue 3). there are yes, no, ok buttons. I click yes and the record should be closed showing the active surv search results list but it keeps me in the record and nothing happens when I click yes, no, or ok. 

**To Reproduce**
1. Log in as michael winston
see steps recorder
[VAS13 not able to find session ID, not able to cancel changes or close record.zip](https://github.com/EIDSS/EIDSS7/files/3383134/VAS13.not.able.to.find.session.ID.not.able.to.cancel.changes.or.close.record.zip)

**Expected behavior**

**Screenshots**

**Additional details:**
 - Build: 82.2
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by aatmns** [comment]
Retested and validated defect.
