### ISSUE TITLE
VAS 13 unable to delete active surv session

### ISSUE THREAD

**Issue by jeanmrichards** [EIDSS/EIDSS7#145]
**Summary**
script asks to search for active surv session, the one you are supposed to find doesnt exist but I clicked on the second one available to try the delete function from step 9. There was no delete button, therefore no way to test delete function and choose yes and see if I got back to search results list. I got out of the session, searched again, again chose the second option in the list, and delete was there and it worked. Went back to test again with remaining active surv session and delete was gone. Checked other active surv sessions from other searches and sometimes delete is there and sometimes it is not. 

**To Reproduce**
1. Log in as michael winston
2. Go to see steps recorder
[VAS 13 inconsistent ability to delete active surveillance session.zip](https://github.com/EIDSS/EIDSS7/files/3383182/VAS.13.inconsistent.ability.to.delete.active.surveillance.session.zip)

**Expected behavior**

**Screenshots**

**Additional details:**
 - Build: 82.2
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by aatmns** [comment]
Retested and validated defect.
