### ISSUE TITLE
Cannot Edit Samples when clicking on edit icon

### ISSUE THREAD

**Issue by srbatni** [EIDSS/EIDSS7#146]
**Summary**
I was trying to edit a sample that I entered by clicking the edit icon, however, nothing happened.

**To Reproduce**
1. Log in as adamanders
2. Go to Human Disease Report, Andrew Taylor, Report ID
3. Click on Samples link

**Expected behavior**
Should be able to click on edit icon to edit a previously entered sample entry.

**Screenshots**

![image](https://user-images.githubusercontent.com/52708365/61071197-51eecc80-a3c5-11e9-8cef-473ed2c1e9e4.png)

**Additional details:**
 - Build: 82.2
 - Script title (enter ad hoc if not script-based): Ad-hoc/HPS03

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by EBH2001** [comment]
Not reproducible in Integration 83.4 build.

PLEASE SEE ATTACHMENT

[HPS03_GitHub#146_Investigation_human_brucellosis_NotReproducible.docx](https://github.com/EIDSS/EIDSS7/files/3407549/HPS03_GitHub.146_Investigation_human_brucellosis_NotReproducible.docx)
