### ISSUE TITLE
LAB Functional area drop down does not display data AND sample details lack printer control/barcode

### ISSUE THREAD

**Issue by Chavez34** [EIDSS/EIDSS7#15]
**Summary**
A clear and concise description of the issue.

**To Reproduce**
1. Log in as mollyrue and go to lab, samples
BUG1: 2. Go to  5. functional area - no data displayed
BUG2: 2. printer icon not displayed; barcode not displayed in sample details

Screenshots**
![image](https://user-images.githubusercontent.com/52667706/60828911-aefa4080-a181-11e9-8cae-ebbd409a37ef.png)

**Additional details:**
 - Build: 77
 - Script title (enter ad hoc if not script-based): LAB02

**Issue severity**
Severity major

**Additional context**
none

**Comment by aatmns** [comment]
7/12/2019, Anatoliy
Not able to replicate in the internal environment.
The system operates as designed. 
The barcode was printed successfully.

**Comment by aatmns** [comment]
![15-1](https://user-images.githubusercontent.com/32458032/61154739-ed169d80-a4bc-11e9-96e9-f8a3ec174f3b.PNG)
