### ISSUE TITLE
Unable to edit contact list or add new contact

### ISSUE THREAD

**Issue by srbatni** [EIDSS/EIDSS7#151]
**Summary**
The functionality to add a new contact in the contact list and the functionality to edit an existing contact are both disabled.

**To Reproduce**
1. Log in as: adamanders 
2. Go to: Human Disease Report, search for Andrew Taylor, click on Report ID, go to Case Investigation, contact list  
3. Click on 

**Expected behavior**
You can add a new contact and edit an existing one.

**Screenshots**
![image](https://user-images.githubusercontent.com/52708365/61072700-afd0e380-a3c8-11e9-8ae5-bb934e7915e5.png)

**Additional details:**
 - Build: 82.2
 - Script title (enter ad hoc if not script-based): HPS03/Ad-hoc testing

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by EBH2001** [comment]
Not reproducible in Integration and PreGA using both users; Russell Peters and Adam Anders.

**PLEASE SEE ATTACHMENT**
[HPS03_GitHub#151_Investigation_human_brucellosis_NotReproducible.docx](https://github.com/EIDSS/EIDSS7/files/3387484/HPS03_GitHub.151_Investigation_human_brucellosis_NotReproducible.docx)

**Comment by jkkannan** [comment]
Closed during GAT remediation.
