### ISSUE TITLE
AD HOC CSS Formatting - Dashboard 

### ISSUE THREAD

**Issue by jkkannan** [EIDSS/EIDSS7#156]
**Summary**

Just flagging this for future builds, as I understand this will change depending on requirements. 

- All of white space - maybe realign some links
- Number of records should read "total number of records" on the bottom left of the main page.
- Some places the middle name reads N/A and some places its blank

**To Reproduce**
1. Log in as adamanders 
2. Review dashboard 

**Expected behavior**
Cleaner user interface 

**Screenshots**
![CSS fomatting](https://user-images.githubusercontent.com/35157698/61131634-b5d9c980-a487-11e9-9e34-180edfedfeb7.png)

**Additional details:**
 - Build: 82.2
 - Script title (enter ad hoc if not script-based): AD HOC

**Issue severity (Optional)**
Severity (critical, major, minor, low): LOW

**Comment by Aj-Kakar** [comment]
![Screenshot (19)](https://user-images.githubusercontent.com/52667376/61135041-d9544280-a48e-11e9-9b5b-e5854a449a3b.png)

**Comment by Aj-Kakar** [comment]
CSS Freezers Page:

![Screenshot (20)](https://user-images.githubusercontent.com/52667376/61137667-f2abbd80-a493-11e9-94fd-d74b93cbc689.png)
