### ISSUE TITLE
LAB Unable to access 12 samples and create two aliquots

### ISSUE THREAD

**Issue by Chavez34** [EIDSS/EIDSS7#16]
**Summary**
A clear and concise description of the issue.

**To Reproduce**
1. Log in as mollyrue
2. Go to Select laboratory >samples from the main menu - several rows missing and not highlighted (missing samples that were supposed to be present per script)
2. Click on #3

**Expected behavior**

Screenshots**

**Additional details:**
 - Build: 77
 - Script title (enter ad hoc if not script-based): LAB01

**Issue severity**
Severity (critical, major, minor, low): N/A

**Additional context**

**Comment by jkkannan** [comment]
Closed in GAT remediation as this was a script issue.
