### ISSUE TITLE
Adhoc: Vector Surveillance Session: Add Sample tab disabled 

### ISSUE THREAD

**Issue by shahina77** [EIDSS/EIDSS7#160]
**Summary**
Vector Surveillance Session: Add Sample tab is disabled 

**To Reproduce**
1. Log in as 
![Vector SV Sample](https://user-images.githubusercontent.com/52667472/61134024-af9a1c00-a48c-11e9-815d-9c19cabea283.PNG)

2. Go to 
3. Click on 

**Expected behavior**

**Screenshots**

**Additional details:**
 - Build: 82.2
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by aatmns** [comment]
Request to the tester:
Please indicate the EIDSS user from this exercise? Adam Anders? Marcy Kaptur?

**Comment by aatmns** [comment]
Replicated and confirmed as defect.
The "add sample" control is disabled at the "Samples" of the Vector Surveillance Session, Detailed Collection.

**Comment by EBH2001** [comment]
This is a workflow issue in the application code.  This will be fixed in the next build.
