### ISSUE TITLE
ADHOC - Human > Person main page

### ISSUE THREAD

**Issue by Aj-Kakar** [EIDSS/EIDSS7#161]
**Summary**
Multiple issues:

- Print icon is a dead link
- Standard report is a dead link 
- Last name is populated by default 
- Repeating fields "Personal ID"

**To Reproduce**
1. Log in as admananders
2. Go to human > person 

**Expected behavior**

**Screenshots**
![dead links](https://user-images.githubusercontent.com/52667376/61134171-01db3d00-a48d-11e9-851e-f7f9c3c90149.png)

**Additional details:**
 - Build: 82.2
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low): Low - CSS stuff mostly

**Comment by jkkannan** [comment]
Print icon is a dead link: New bug; Low
Standard report is a dead link: Duplicate
Last name is populated by default: Not a bug, but related enhancement is already documented
Repeating fields "Personal ID": Not a bug
