### ISSUE TITLE
ADHOC: Date of Disease Error Notification

### ISSUE THREAD

**Issue by srbatni** [EIDSS/EIDSS7#163]
**Summary**
The dates on the outbreak management form don't make sense. You can arbitrarily enter any date in the date of notification field and don't receive an error, until you try and get to the clinical information tab and you start receiving errors which don't necessarily logically follow the date of notification. This could just be a GAT testing issue, but worth exploring.

**To Reproduce**
1. Log in as adamanders
2. Go to Outbreak, outbreak management, PER19000000003, OUT190009
3. Click on Clinical Information

**Expected behavior**
Keep changing dates but timeline and error messages don't seem to flow logically.

**Screenshots**
![image](https://user-images.githubusercontent.com/52708365/61136359-5aeca600-a478-11e9-89da-f0fc6cf43cde.png)

**Additional details:**
 - Build: 82.2
 - Script title (enter ad hoc if not script-based): Ad Hoc

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by nlipskaya** [comment]
Confirmed in Integration. Need to refine business rules around date fields and update validation.

![image](https://user-images.githubusercontent.com/30051006/61156712-0ec65380-a4c2-11e9-8df3-dc3ba8a11e9d.png)
