### ISSUE TITLE
ADHOC:  Monthly Morbidity and Mortality Reports Enhancement

### ISSUE THREAD

**Issue by srbatni** [EIDSS/EIDSS7#164]
**Summary**
The spelling of morbidity and mortality in title screen is incorrect. When you download the reports in any format other than Excel, the formatting is off (columns are cut off etc.) 

**To Reproduce**
1. Log in as adamanders
2. Go to human monthly morbidity and mortality reports
3. Click on: Different report formats (the only one that displays correctly is Excel)

**Expected behavior**
The report should display correctly without cutting off any columns/rows, etc.

**Screenshots**
![image](https://user-images.githubusercontent.com/52708365/61137773-fe3eba80-a47a-11e9-9055-7eabd0b80403.png)

![image](https://user-images.githubusercontent.com/52708365/61137844-1d3d4c80-a47b-11e9-9dcb-2f59c42badea.png)

**Additional details:**
 - Build: 82.2
 - Script title (enter ad hoc if not script-based): Ad Hoc

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by jkkannan** [comment]
Actually two defects; one is the spelling error which is low.  Second is the formatting.
