### ISSUE TITLE
ADHOC unable to create livestock disease report with full details

### ISSUE THREAD

**Issue by jeanmrichards** [EIDSS/EIDSS7#165]
**Summary**
Attempting to create new suspected swine flu cases at livestock farm in Tbilisi; I go into farm owned by tony panno and add new disease report. I am only able to edit a few tabs - many are gray. The notification data entry box is prepopulated with a human hospital and I cannot edit. 

Able to edit:
Farm herd species
vaccination
animals
samples

unable to edit:
notification including disease name
farm epi
species

This bug occurred twice and on the 3rd attempt it works...?

**To Reproduce**
1. Log in as 
2. Go to 
3. Click on 

**Expected behavior**

**Screenshots**

**Additional details:**
 - Build: 82.2
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by aatmns** [comment]
Not able to fully replicate on the internal environment.
Did see that the "Farm Epidemiology" section was greyed out for editing. Saved the record. Relogged in as Mike Tyson again, and the section became unlocked.  Hence I was able to enter the rest of data.
Will be replicating the same workflow on the GAT station at 12:15pm (7/12/19).
