### ISSUE TITLE
ADHOC new livestock disease report - functionality to add?

### ISSUE THREAD

**Issue by jeanmrichards** [EIDSS/EIDSS7#166]
**Summary**
suggested functionality:
-farm epi tab - animals introduced - should be able to add multiple species with associated details
-species investigation tab - clinical signs - should you use the same matching drop down as animals tab? when you add animals in animals tab and click clinical signs YES then you see options - these could be/ should be used for species investigation?
-vaccinations - remove ASF as an option?

**To Reproduce**
1. Log in as 
2. Go to 
3. Click on 

**Expected behavior**

**Screenshots**

**Additional details:**
 - Build: 82.2
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by jkkannan** [comment]
Need to crosswalk to use case to determine if bug or enhancement.

**Comment by aatmns** [comment]
Not considered for a software change request.
