### ISSUE TITLE
ADHOC: Human Aberration Analysis

### ISSUE THREAD

**Issue by srbatni** [EIDSS/EIDSS7#167]
**Summary**
Tried several diseases and date ranges, but each time the graph that displayed showed zero for observed and expected cases.

**To Reproduce**
1. Log in as: adamanders
2. Go to: Human Aberration Analysis 
3. Click on: Any disease, different date ranges

**Expected behavior**
There should be a two trend lines one for observed and one for expected cases over time.

**Screenshots**
![image](https://user-images.githubusercontent.com/52708365/61142100-cf791200-a483-11e9-9f9c-d8d8a7a24bd6.png)

![image](https://user-images.githubusercontent.com/52708365/61142178-fdf6ed00-a483-11e9-899f-34fc0f8a895e.png)

SEPARATE RUN
![image](https://user-images.githubusercontent.com/52708365/61141717-06025d00-a483-11e9-99d7-0920613c2e4f.png)

**Additional details:**
 - Build: 82.2
 - Script title (enter ad hoc if not script-based): Ad-hoc

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by nlipskaya** [comment]
Confirmed in integration.
