### ISSUE TITLE
ADHOC new avian disease report - unable to choose/edit flock name

### ISSUE THREAD

**Issue by jeanmrichards** [EIDSS/EIDSS7#168]
**Summary**
when adding a new flock in farm/flock/species there are 2 issues

#1 - may have reported already - when you add a new flock and then a new species under it, you can't delete the species or the herd due to parent/child issues

#2 - can't choose your own flock name or edit it once you create a new flock

**To Reproduce**
1. Log in as 
2. Go to 
3. Click on 

**Expected behavior**

**Screenshots**

**Additional details:**
 - Build: 82.2
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by jkkannan** [comment]
2 is enhancement. Notes are an option for addressing that.
1 is a defect that has been previously noted with child objects.

**Comment by aatmns** [comment]
Not considered for a software change request.
