### ISSUE TITLE
[BUG] LAB Samples not showing as unacessioned; missing samples

### ISSUE THREAD

**Issue by Chavez34** [EIDSS/EIDSS7#17]
**Summary**
A clear and concise description of the issue.

**To Reproduce**
1. Log in as troymcclure
2. Go to #3  45 of highlighted samples not displayed, and all samples were non-highlighted and indicated they were accessioned.
2. Click on  sample status.

**Expected behavior**
Expected to see 45 samples and to see some as unaccessioned (thus highlighted).

Screenshots**
![image](https://user-images.githubusercontent.com/52667706/60829634-5166f380-a183-11e9-95e0-015a95432697.png)

**Additional details:**
 - Build: 77
 - Script title Lab 03 Module

**Issue severity**
Severity Major

**Additional context**

**Comment by aatmns** [comment]
7/12/2019, Anatoliy
Not able to replicate in the internal environment.
The system operates as designed.

Selected unaccessioned samples:
![17-1](https://user-images.githubusercontent.com/32458032/61154982-aaa19080-a4bd-11e9-811e-b83f44882608.PNG)

Clicked on "Accession" button:
![17-2](https://user-images.githubusercontent.com/32458032/61154995-b68d5280-a4bd-11e9-9a53-1c733d250422.PNG)

Clicked on "Save" button:
![17-3](https://user-images.githubusercontent.com/32458032/61155011-c147e780-a4bd-11e9-97af-314ddf05dcc6.PNG)
