### ISSUE TITLE
REP 03 vet yearly situation report

### ISSUE THREAD

**Issue by jeanmrichards** [EIDSS/EIDSS7#172]
**Summary**
difficult to get to yearly situation report in drop down

**To Reproduce**
1. Log in as ellen skylar
2. Go to reports>standard>vet>vet yearly situation
see steps

**Expected behavior**
should be able to get to vet yearly situation easily

**Screenshots**

**Additional details:**
 - Build: 83.3
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low): major
[REP 03 vet reports drop down issue.zip](https://github.com/EIDSS/EIDSS7/files/3392654/REP.03.vet.reports.drop.down.issue.zip)

**Additional context**

**Comment by jkkannan** [comment]
Known issue interally on menu dropdowns being difficult to access.
