### ISSUE TITLE
REP 03 missing "use archived data" button

### ISSUE THREAD

**Issue by jeanmrichards** [EIDSS/EIDSS7#173]
**Summary**
script calls for unchecked button but button does not exist

**To Reproduce**
1. Log in as ellen skylar
2. Go to 
3. Click on 

**Expected behavior**

**Screenshots**

**Additional details:**
 - Build: 83.3
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by jkkannan** [comment]
Need to check UC on how system will behave when there is no archive data.  May or may not be bug.
