### ISSUE TITLE
HPS14 ILI Aggreate Form "Total ILI" number not displaying (per script)

### ISSUE THREAD

**Issue by TheTommyLee** [EIDSS/EIDSS7#174]
**Summary**
A clear and concise description of the issue.
ILI Aggreate Form "Total ILI" number not displaying until add control (+) is clicked.  Need to update the expected results. 

**To Reproduce**
1. Log in as EllenSkylar
2. Go to 6 in script

**Expected behavior**
The <Total> value displayed should be 19

**Screenshots**

**Additional details:**
 - Build: 83.3
 - Script title (enter ad hoc if not script-based):  HPS14 Human Passive Surveillance

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by jkkannan** [comment]
Have internal issue.  Control should be a calculate icon rather than an add icon.
