### ISSUE TITLE
REP 03 vet yearly situation report does not have print control

### ISSUE THREAD

**Issue by jeanmrichards** [EIDSS/EIDSS7#175]
**Summary**
scripts asks to select print control but there is no print control. right click in browser to print does not display anything in print preview either. 

**To Reproduce**
1. Log in as ellen skylar
2. Go to 
3. Click on 

**Expected behavior**

**Screenshots**

**Additional details:**
 - Build: 83.3
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by jkkannan** [comment]
Documentation issue.  Need to check on SSRS.
Also question on all the Export functions that are possible and whether reports export to all of those correctly and also if all of those are needed. SEPARATE issue.
