### ISSUE TITLE
REP 03 vet yearly sitrep verification failed

### ISSUE THREAD

**Issue by jeanmrichards** [EIDSS/EIDSS7#177]
**Summary**
when attempting to verify that what is in the sitrep and what is in EIDSS for each disease for 2019 are the same quantity for FMD and AI, the numbers don't match. sit rep says 1 FMD and 6 AI; search shows 2 FMD and 7 AI.

**To Reproduce**
1. Log in as ellen skylar
2. Go to see steps
[REP 03 vet yearly report disease numbers.zip](https://github.com/EIDSS/EIDSS7/files/3392845/REP.03.vet.yearly.report.disease.numbers.zip)

**Expected behavior**

**Screenshots**

**Additional details:**
 - Build: 83.3
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by jkkannan** [comment]
Need to check if specification is only for confirmed, if discrepancy is due to environment/replication, or some other issue. Issue type pending that discussion.
