### ISSUE TITLE
REP 03 no organization shows for vet yearly sitrep

### ISSUE THREAD

**Issue by jeanmrichards** [EIDSS/EIDSS7#178]
**Summary**
name of organization does not show up for logged in user (i.e. NCDC or other org.)

**To Reproduce**
1. Log in as ellen skylar
2. Go to 
3. Click on 

**Expected behavior**

**Screenshots**

**Additional details:**
 - Build: 83.3
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by jkkannan** [comment]
Need to check UC; missing in report generation parameters as well as in generated report.
