### ISSUE TITLE
Human Monthly Morbidity and Mortality - Blank text Box above report form

### ISSUE THREAD

**Issue by TheTommyLee** [EIDSS/EIDSS7#179]
**Summary**
Blank Text box displaying above the report form.

**To Reproduce**
1. Log in as adamanders
2. Go to 4 in script 
3. Click on 

**Expected behavior**
Text box should not appear on the Report form

**Screenshots**
![Screenshot (27)](https://user-images.githubusercontent.com/52924423/61228103-97780600-a6f3-11e9-809d-f104ac27c061.png)

**Additional details:**
 - Build: 83.3
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by jkkannan** [comment]
Need to check if reproducible.
