### ISSUE TITLE
[BUG] HPS Unable to add disease and other information to human disease report

### ISSUE THREAD

**Issue by shahina77** [EIDSS/EIDSS7#18]
**Summary**
Disease Tab is disabled, won't allow to select disease name using drop down many
**To Reproduce**
1. Log in as Russell Peters
2. Search for Jane Grey in person search
3. Open Jane Grey's record and scroll down to disease reports and select Add
4.  Go to step 9 and try to enter disease, date of disease, etc; all fields were disabled and could not be edited. 

**Expected behavior**

Screenshots**

**Additional details:**
 - Build: 77
 - (enter ad hoc if not script-based): HPSO6 

**Issue severity**
Severity (critical, major, minor, low): Critical

**Additional context**
![HPSO6_ DTab](https://user-images.githubusercontent.com/52667472/60830412-24b3db80-a185-11e9-993e-f9634154dc0a.png)

**Comment by lmit1040** [comment]
Disease Reports are added Through the Person Record. 
1. Click on Human => Person
2. Search for Jane Grey
3. Click on Person Review
4. Scroll down to Disease Reports
5. Select Add

![image](https://user-images.githubusercontent.com/25065421/60908484-fa782180-a249-11e9-86c5-9efde24c6728.png)

**Comment by EBH2001** [comment]
Not reproducible in Integration and PreGA 83.1 build.

**PLEASE SEE ATTACHMENT
[HPS06_GitHub#18_Childhood disease for adult_NotReproducible.docx](https://github.com/EIDSS/EIDSS7/files/3390185/HPS06_GitHub.18_Childhood.disease.for.adult_NotReproducible.docx)
