### ISSUE TITLE
REP 04 vet active surv reports disease field is called diagnosis

### ISSUE THREAD

**Issue by jeanmrichards** [EIDSS/EIDSS7#181]
**Summary**
field does not match script in vet active surv report - should be disease and match the field in the system but it says diagnosis - may matter for exporting in ENG language for international disease reporting

**To Reproduce**
1. Log in as 
2. Go to 
3. Click on 

**Expected behavior**

**Screenshots**

**Additional details:**
 - Build: 83.3
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by jkkannan** [comment]
Also need to check against previous report. May not be bug.
