### ISSUE TITLE
ABE03 chart from vet aberration analysis issues

### ISSUE THREAD

**Issue by jeanmrichards** [EIDSS/EIDSS7#186]
**Summary**
issue 1 chart x and y axis are not labeled

issue 2 first chart with number of cases and date entered: the observed, expected, and alerts lines should be shown but the chart only has the first 2, not alerts

issue 3 first chart with number of cases and date entered: the values for number of cases as partial numbers (0-1.2) is strange for case numbers. should be whole numbers

issue 4 second chart with CUSUM and date entered: script says it should have threshold and CUSUM values but it has threshold and observed 

issue 5 second chart with CUSUM and date entered: there is a strange 000000 line in the chart

issue 6 table on pages 3/4 in the first column the title is just "#" but it should be labeled "time unit #" and also second in column should be "time unit beginning date" but it says "case date"

issue 7 there is no "close" control to exit the report and return to EIDSS

**To Reproduce**
1. Log in as ellen skylar
see steps

[ABE 03 chart issues.zip](https://github.com/EIDSS/EIDSS7/files/3393317/ABE.03.chart.issues.zip)

**Expected behavior**

**Screenshots**

**Additional details:**
 - Build: 83.3
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by jkkannan** [comment]
Query issue with flat zero line for observed values.  Related to #3 above as the Y axis should have a wider range and be in whole numbers.
