### ISSUE TITLE
ADM04 - Modify existing Org.

### ISSUE THREAD

**Issue by Aj-Kakar** [EIDSS/EIDSS7#188]
**Summary**
ADM04 - User is expected to update the organization information. I am able to update everything besides postal code. The postal code should be a data entry field but it is actually a drop down option in the system.  

**To Reproduce**
1. Log in as admanders
2. Go to Organization List 
3. Click on the edit button for a organization
4. Update the postal code to "45209" - This is the point of failure, unable to update the postal code which is a required field. 

**Expected behavior**
User should be able to update the postal code field 

**Screenshots**
![ADM04](https://user-images.githubusercontent.com/52667376/66319162-a03f3900-e8ea-11e9-9e18-e390b199316a.png)

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by aatmns** [comment]
A known issue with postal codes. 
Defect confirmed.

**Comment by jkkannan** [comment]
Discussion regarding the field. Should be combination of dropdown and free text entry to allow for full range of potential user countries. 
Suggestion from GAT remediation team to have example data in fields grayed out as a possible way to reduce user error.
