### ISSUE TITLE
HPS02: Incorrect "Report Type" Autopopulated 

### ISSUE THREAD

**Issue by tonihudson06** [EIDSS/EIDSS7#189]
**Summary**
The report type in the "Disease Report Summary" was supposed to autopopulate the "Report Type" as "passive" but it was populated as "active"

**To Reproduce**
1. Log in as michaeldouglas
2. Go to Human-->Person from main menu
3. Enter information to search for existing record
4. Open John Smith record in view mode
5. Scroll to Disease Reports
6. Select Add button
7. Select carat control to right of Disease Report Summary

**Expected behavior**
Report type was supposed to autopopulate as "passive"

**Screenshots**

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based): HPS02

**Issue severity (Optional)**
Severity (critical, major, minor, low): Minor

**Additional context**

**Comment by nlipskaya** [comment]
Known issue. In a queue for fixing as minor.

**Comment by jkkannan** [comment]
Discussion of idea: keeping it as blank upon opening a disease report but user will then have to edit to either active or passive to avoid false entry of the wrong type.
