### ISSUE TITLE
Employee search functionality has multiple issues [BUG]

### ISSUE THREAD

**Issue by Aj-Kakar** [EIDSS/EIDSS7#19]
**Summary**
When you use the search functionality in the employee list I am getting multiple errors, if I keep resubmitting my search for the last name "jones" few times 10-15 seconds apart I am getting mutiple results:
-System logs me out
-Doesn't perform the search
-Performs the correct search
-Takes me to the employees details page

SECOND AND THIRD BUGS IDed: Clear button does not clear for Employee Search or Organization search; MINOR bugs for these two.

**To Reproduce**
1. Log in as "ellenskylar". 
2. Select **Employees** under the **Administration** drop down menu.
3. Click on **Search** 
4. Enter employee name (jones) to search and submit search

**Expected behavior**
Search filter should perform the search for the expected employee name and the search filter should clear upon clicking **clear** search.

Screenshots**
None

**Issue severity**
Major

**Additional context**
The search functionality crashes if the user submits too many searches to quick - seems to be a loading issue.

**Build**
77

**Comment by aatmns** [comment]
7/12/19 Anatoliy
Defect replicated and confirmed in PRE.  INT operates as designed.
![191](https://user-images.githubusercontent.com/32458032/61155354-bc376800-a4be-11e9-8d50-5d5e9fb549ca.PNG)

![192](https://user-images.githubusercontent.com/32458032/61155494-19cbb480-a4bf-11e9-9bf2-1a20d36ce646.PNG)
