### ISSUE TITLE
VPS01 unable to find created livestock disease report

### ISSUE THREAD

**Issue by jeanmrichards** [EIDSS/EIDSS7#190]
**Summary**
unable to find created livestock disease report

**To Reproduce**
after creating and submitting LDR, with confirmation of save with new report ID generated, unable to find report in search using the ID or other information in search criteria.

**Expected behavior**

**Screenshots**

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by EBH2001** [comment]
This issue is not reproducible in both QA and PreGAT.  Will re-test in GAT to confirm.

**Comment by jkkannan** [comment]
Tested in GAT; were able to find record. Tester reported recurring issue with system controls changing, not seeing records but this was fixed by logging out and logging back in or changing WiFi etc.
