### ISSUE TITLE
ADM06 - Modify Settlement

### ISSUE THREAD

**Issue by Aj-Kakar** [EIDSS/EIDSS7#191]
**Summary**
Followed test plan ADM6 to modify settlement data - I was able to update the information, however, I was about able to verify if the record was recorded. Search function did not return the updated record "Khala V2". Search function also had country, region, and rayon auto-populated which might be impacting the search. Sort functionality was not also available to make it easier to verify submission or to find a record. Same issues as round 1 GAT testing. 

**To Reproduce**
1. Log in as adamanders
2. Go to settlement list
3. Click on the edit button for any village record
4. Update the record and submit 
5. Verify submission - This is the failure point

**Expected behavior**
User should be able to verify the submission of a updated record

**Screenshots**
![ADM06](https://user-images.githubusercontent.com/52667376/66321289-5a846f80-e8ee-11e9-8489-cc50393587ca.png)

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by aatmns** [comment]
The settlement record is successfully updated and verified in the testing environment.
Not able to reproduce in the testing.

**Comment by aatmns** [comment]
Need to retest in the GAT environment

**Comment by jkkannan** [comment]
Related issue identified that fields are not autopopulated some times in the search screen but other times it is autopopulated as above.
