### ISSUE TITLE
LAB03 Accession Veterinary Samples

### ISSUE THREAD

**Issue by Chavez34** [EIDSS/EIDSS7#192]
**Summary**
Step 6. Lab Sample ID is not generated.

**To Reproduce**
1. Log in as troymcclure
2. Go to Step 6 
3. Click on Select accepted in Good Condition from the drop-down field.
4.  Each accessioned sample does not generate a sample ID.

**Expected behavior**
Step 6:  Lab sample ID is generated.

**Screenshots**

![image](https://user-images.githubusercontent.com/52667706/66322341-fa8ec880-e8ef-11e9-88f2-0541ee191f87.png)

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):
Critical

**Additional context**

**Comment by aatmns** [comment]
The system operates as designed. Not able to replicate failure in the testing environment.
The Laboratory IDs were generated correctly.
Issue: incorrect scenario step #6. It should not expect to create laboratory IDs without saving those samples.
The LAB03 scenario is already updated.
List of samples marked as "accepted in good condition":
![192-1](https://user-images.githubusercontent.com/32458032/66323989-b2bd7080-e8f2-11e9-9d16-50bd42dc9574.PNG)

List of samples with assigned Lab IDs after selecting "Save".
![192-2](https://user-images.githubusercontent.com/32458032/66323999-b7822480-e8f2-11e9-8f57-77a988f63060.PNG)

**Comment by aatmns** [comment]
The updated LAB03 scenario.
[LAB03 Accession vet sample.docx](https://github.com/EIDSS/EIDSS7/files/3698124/LAB03.Accession.vet.sample.docx)
