### ISSUE TITLE
ADM07 - Manage Case Classification

### ISSUE THREAD

**Issue by Aj-Kakar** [EIDSS/EIDSS7#193]
**Summary**
Unable to read the accessory Code under the case classification window, also, unable to save the update.

**To Reproduce**
1. Log in as adamanders
2. Go to case classifications 
3. Use ctrl key to remove accessory code selection 
5. click save - the system stays in edit mode

**Expected behavior**

**Screenshots**
![ADM07](https://user-images.githubusercontent.com/52667376/66322956-fe6f1a80-e8f0-11e9-822b-c1843be43193.png)

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by aatmns** [comment]
Unable to replicate this issue in the testing environment.
The system operates as designed.
Need to retest this in the GAT environment.

Steps taken:
Lost to follow up record is opened in the edit mode:
![193-1](https://user-images.githubusercontent.com/32458032/66325872-fe254e00-e8f5-11e9-812f-3eb1e9912cd7.PNG)
Three values were selected.

Unchecked two values:
![193-2](https://user-images.githubusercontent.com/32458032/66325979-32007380-e8f6-11e9-83d9-d72761e75380.PNG)

Selected "Save" control:
![193-3](https://user-images.githubusercontent.com/32458032/66326012-43498000-e8f6-11e9-9ec4-b1a5f4f777c7.PNG)

Dismissed the notification message:
![193-4](https://user-images.githubusercontent.com/32458032/66326030-4cd2e800-e8f6-11e9-908f-d590af02807d.PNG)

The changes were saved.
