### ISSUE TITLE
HPS03: Some fields not saved in the verification step

### ISSUE THREAD

**Issue by tonihudson06** [EIDSS/EIDSS7#194]
**Summary**
All steps passed except for Step #30 (Verification Step) where two fields were not saved: the Clinical info on antibiotics and vaccines

**To Reproduce**
1. Log in as russellpeters
*Follow script HPS03 until Step 30*

**Expected behavior**
After inputting all the fields prompted to in the procedure, in the verification step all information is supposed to be updated.

**Screenshots**
See attachment

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based): HPS03

**Issue severity (Optional)**
Severity (critical, major, minor, low): Major
![HPS03](https://user-images.githubusercontent.com/56262298/66323941-9b7e8300-e8f2-11e9-9f89-68a04416d4fb.PNG)

**Additional context**

**Comment by nlipskaya** [comment]
Issue is confirmed in QA.
