### ISSUE TITLE
HPS03-Epidemiological inconsistencies & recommendations

### ISSUE THREAD

**Issue by tonihudson06** [EIDSS/EIDSS7#195]
**Summary**
All steps in script HPS03 passed; however, I would like to note the following:
1) The case was classified as a "confirmed case"though there were no laboratory tests documented in their case report form. Without laboratory confirmation, a case cannot be classified as "confirmed"
2)Recommendation #1: In Step #19 it asks the user if the "location of exposure is known?". If "no"/"unknown" is selected then there is no option to populate likely/possible exposures; this option is crucial. For example, for a foodborne illness, a person may have multiple exposures and may not know the exact source but it's still worth noting so the epidemiologist investigating the case is aware of potential exposure locations and can possibly identify a source based on other persons reporting similar illnesses with the same exposure location(s). 
3) Recommendation #2: In Step #21 there is a question that asks "Is the case aware of any other persons having a similar disease". Recommend that this says "similar disease/symptoms". The person may not be aware of another person's official diagnosis but is more likely to know if another person is experiencing similar symptoms.

**To Reproduce**
1. Log in as 
2. Go to 
3. Click on 

**Expected behavior**

**Screenshots**

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based): HPS03

**Issue severity (Optional)**
Severity (critical, major, minor, low): Major

**Additional context**

**Comment by nlipskaya** [comment]
Issue 1: Confirmed. There should be a blank line there to not pick up on a status.
Recommendation 1: Implemented as in EIDSS 6.1
Recommendation 2: Wording as in EIDSS 6.1
