### ISSUE TITLE
VPS01 epizootologist dashboard

### ISSUE THREAD

**Issue by jeanmrichards** [EIDSS/EIDSS7#196]
**Summary**
script says upon login that epizoo dashboard should be displayed but I see unaccessioned samples with ryanjohnson. should it be "my investigations"? does it matter?

**To Reproduce**
1. Log in as ryan johnson
2. Go to 
3. Click on 

**Expected behavior**

**Screenshots**

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by EBH2001** [comment]
This issue was reproduced in QA.  The user permission's for Ryan Johnson was incorrectly set and has been addressed.

**Comment by EBH2001** [comment]
**Correction:**

The role for Ryan Johnson was updated successfully.  However, when you logout and log back in the dashboard still displays Laboratory.

This is a defect.
