### ISSUE TITLE
LAB05 Mark a sample for deletion due to a clerical error

### ISSUE THREAD

**Issue by Chavez34** [EIDSS/EIDSS7#197]
**Summary**
Step 7. Select save - does not save or display EIDSS Success Message

**To Reproduce**
1. Log in as Molly Rue
2. Go to Step 5 check the selection for any one sample for William Gates
3. Select the samples menu and select lab record deletion >delete sample
4. Sample ID selected for deletion
5. Enter reason for deletion "clerical error"
6. Select delete control
7. Select save - does not save deletion or display EIDSS Success Message

**Expected behavior**
Step 7. Select Save control in the samples tab header saves and the EIDSS Success Message is displayed.

**Screenshots**

![image](https://user-images.githubusercontent.com/52667706/66327005-0bdbd300-e8f8-11e9-910f-f6622f1fcf25.png)

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Critical

**Additional context**

**Comment by aatmns** [comment]
Defect is confirmed.
The system did not display saved record in the Samples section.
