### ISSUE TITLE
HPS04: Prepopulated fields not prepopulated

### ISSUE THREAD

**Issue by tonihudson06** [EIDSS/EIDSS7#199]
**Summary**
In step #3 of HPS04 the region and rayon are not prepopulated

**To Reproduce**
1. Log in as russellpeters
2. Go to Human-->Disease Report

**Expected behavior**
In the search screen the region and rayon are supposed to prepopulate as "Kakheti" and "Telavi (rayon)", respectively

**Screenshots**

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based): HPS04

**Issue severity (Optional)**
Severity (critical, major, minor, low): Minor

**Additional context**

**Comment by nlipskaya** [comment]
Confirmed.

**Comment by nlipskaya** [comment]
"Kakheti" and "Telavi (rayon)" not populated.
