### ISSUE TITLE
Lab Sample ID - not present, unable to create derivatives

### ISSUE THREAD

**Issue by Chavez34** [EIDSS/EIDSS7#20]
**Summary**
A lab sample ID for Michael Write does not appear in the table of samples in Lab.  All subsequent steps do not populate appropriately, nor are the requisite 24 derivatives created. 

**To Reproduce**
1. Log in as mollyrue
2. Go to #4, Write the selected lab sample ID (missing); 
2. Click on create derivative - appears as though instructional steps are missing.

**Expected behavior**
Lab Sample ID present, able to create 24 derivatives. 

Screenshots**

**Additional details:**
 - Build: 77
 - Script title (enter ad hoc if not script-based): LAB04

**Issue severity**
Severity (critical, major, minor, low): Critical

**Additional context**

**Comment by EBH2001** [comment]
Not reproducible in Integration Build 83.1.  The script step for #4 was incorrect.  The Lab Sample ID is not populated until after you click "Save" to save the accessioned samples.  If you checked "print barcodes", you will see the Lab Sample ID(s) after you close the print dialogue.

**PLEASE SEE ATTACHMENT**

[LAB01_GitHub#20_Accession sample_NotReproducible.docx](https://github.com/EIDSS/EIDSS7/files/3390441/LAB01_GitHub.20_Accession.sample_NotReproducible.docx)

**Comment by jkkannan** [comment]
Closed in GAT remediation with script modification to reflect workflow.
