### ISSUE TITLE
HPS04: Tests Grid are not populated as expected

### ISSUE THREAD

**Issue by tonihudson06** [EIDSS/EIDSS7#200]
**Summary**
In Step#7 to review the Tests grid, the system did not display the two test results as expected. Only one result was displayed; there was no "test disease" field; the "test result" was positive not negative; "rule in/rule out" was not populated; the "validated" field has a "Y/N" selection option and said "true", not a checked checkbox as expected

**To Reproduce**
1. Log in as russellpeters
2. Go to Human-->Disease Report
3. Entered "disease", "first name", "last name" data and searched for records
4. Opened the human disease report for Melanie Jones using the edit icon 
5. Selected the tests link in the Navigation bar
6. Reviewed the tests grid

**Expected behavior**
The system was supposed to display test results for Tularemia and Measles with the fields noted in the script

**Screenshots**
See attachment

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based): HPS04

**Issue severity (Optional)**
Severity (critical, major, minor, low): Major
![HPS04_Step7 Tests Grid](https://user-images.githubusercontent.com/56262298/66332658-38491c80-e903-11e9-97b6-0901442545e1.PNG)

**Additional context**

**Comment by nlipskaya** [comment]
Script Issue: Christine Jonson should be search for.
