### ISSUE TITLE
HPS04: Report Status was not prepopulated

### ISSUE THREAD

**Issue by tonihudson06** [EIDSS/EIDSS7#202]
**Summary**
In Step#10 of HPS04 the step asks to verify the "report status" field which was supposed to populate as "closed" but the field was "in progress"; I therefore had to populate manually.

**To Reproduce**
1. Log in as russellpeters
2. Go to Human-->Disease Report
3. Entered "disease", "first name", "last name" data and searched for records
4. Opened the human disease report for Melanie Jones using the edit icon 
5. Selected the tests link in the Navigation bar
6. Reviewed the tests grid
7.Select final outcome link
8. Selected "not a case" in the final case classification drop down
9. Verified the "report status" in the Disease Report Summary dropdown

**Expected behavior**
The report status field is supposed to prepopulate as "closed"

**Screenshots**
see attachment

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based): HPS04

**Issue severity (Optional)**
Severity (critical, major, minor, low): Minor
![HPS04_Step 10](https://user-images.githubusercontent.com/56262298/66332941-e48b0300-e903-11e9-9285-e01d8f61377f.PNG)

**Additional context**

**Comment by nlipskaya** [comment]
Script Issue: Christine Jonson should be searched by.

**Comment by jkkannan** [comment]
Needs follow-up on TFS.
