### ISSUE TITLE
LAB06 Register a new sample in the  laboratory module

### ISSUE THREAD

**Issue by Chavez34** [EIDSS/EIDSS7#203]
**Summary**
Step 10 Select  (cancel) control) confirm "Yes" does not display and the Lab sample ID is not populated.

**To Reproduce**
1. Log in as mollyrue
2. Go to Step 10 
3. Select (cancel) control and confirm "Yes"

**Expected behavior**
Step 10 Select  (cancel)l control and confirm "Yes",  the  Lab sample ID should populate.

**Screenshots**

![image](https://user-images.githubusercontent.com/52667706/66332564-08017e00-e903-11e9-8e49-267114c9d4d4.png)

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Critical:

**Additional context**

**Comment by aatmns** [comment]
Defect confirmed.
