### ISSUE TITLE
ADM21 - Sample Types List Update

### ISSUE THREAD

**Issue by Aj-Kakar** [EIDSS/EIDSS7#205]
**Summary**
I was able to edit sample types, but, the submission of a new sample type did not save in the system.

**To Reproduce**
1. Log in as rykermase
2. Go to admin > reference editor > sample types
3. Click on add
4. Add new sample data
5. Verify the new samples in the sample types list 

**Expected behavior**
User should be able to add  "Feed - Hay and Feed - Silage" sample types

**Screenshots**
![ADM21](https://user-images.githubusercontent.com/52667376/66333700-84955c00-e905-11e9-899d-8f45e5d9fd09.png)

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by aatmns** [comment]
Unable to replicate this defect in the testing environment.
The records were saved successfully.
Need to retest in the GAT environment.

Example of new sample:
![205-](https://user-images.githubusercontent.com/32458032/66335342-de4b5580-e908-11e9-93ee-fde0e4545724.PNG)
