### ISSUE TITLE
HPS04: Error message when attempt to submit the new connected case report

### ISSUE THREAD

**Issue by tonihudson06** [EIDSS/EIDSS7#206]
**Summary**
Unable to submit the new connected case report. When attempted I received an error message that says "an error occurred on this page. Please verify your information to resolve the issue." No report ID was generated because the symptoms were not populated from the connected tularemia case. 

**To Reproduce**
1. Log in as russellpeters
2. Go to Human-->Disease Report
3. Entered "disease", "first name", "last name" data and searched for records
4. Opened the human disease report for Melanie Jones using the edit icon 
5. Selected the tests link in the Navigation bar
6. Reviewed the tests grid
7.Select final outcome link
8. Selected "not a case" in the final case classification drop down
9. Verified the "report status" in the Disease Report Summary dropdown
10. Review, submit, and select "yes" when save confirmation message pops up
11. Navigate to notification and complete the disease, date of diagnosis, and date of notification fields
12. Review case report
14. Select submit

**Expected behavior**
System is supposed to display a save success message with the new report ID

**Screenshots**
See attached

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based): HPS04

**Issue severity (Optional)**
Severity (critical, major, minor, low): Critical
![HPS04_Step16_submit](https://user-images.githubusercontent.com/56262298/66334051-451b3f80-e906-11e9-959b-1f731a1a903f.PNG)

**Additional context**

**Comment by nlipskaya** [comment]
Script Issue: Christine Jonson record should be used.

**Comment by jkkannan** [comment]
Linked to #204 and #202 and #200 for HPS04. May all be script issue. Needs retesting.
