### ISSUE TITLE
ADM23 - Updates to the Animals Disease List

### ISSUE THREAD

**Issue by Aj-Kakar** [EIDSS/EIDSS7#207]
**Summary**
Per script ADM23, I added "Canine Distemper" to the disease list, but I was unable later verify the submission by reviewing the disease list. 

**To Reproduce**
1. Log in as rykermase
2. Go to admin > reference editor > diseases 
3. Click on add
4. Add "Canine Distemper" as a new disease following the script details 
5. Verify the submission - this is the point of failure, unable to verify.

**Expected behavior**
System should save the new disease submission.

**Screenshots**

![ADM23](https://user-images.githubusercontent.com/52667376/66335072-4188b800-e908-11e9-8721-7c148100b9f4.png)

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by aatmns** [comment]
Defect confirmed.
