### ISSUE TITLE
LAB Sample ID referenced in script was not present in system

### ISSUE THREAD

**Issue by Chavez34** [EIDSS/EIDSS7#21]
**Summary**
Sample ID is missing. Sample is not deleted. Effects all subsequent steps. Unable to mark a sample for deletion due to clerical error.

**To Reproduce**
1. Log in as mollyrue
2. Go to Laboratory, Samples
3. searched for sample associated with Jack Sparrow, blood-plasma, etc
4. Unable to locate the sample and thus could not delete.

**Expected behavior**

Screenshots**

**Additional details:**
 - Build: 77
 - Script title (enter ad hoc if not script-based): LAB05

**Issue severity**
Severity Major

**Additional context**

**Comment by aatmns** [comment]
7/12/2019, Anatoliy
Not able to replicate in the internal environment.
The system operates as designed.
The sample was located:
![211](https://user-images.githubusercontent.com/32458032/61155977-551ab300-a4c0-11e9-8f1e-1c12f3d71dbf.PNG)

**Comment by jkkannan** [comment]
Closed during GAT remediation as a script issue.
