### ISSUE TITLE
LAB07 Assign a test and test results to accessioned samples

### ISSUE THREAD

**Issue by Chavez34** [EIDSS/EIDSS7#210]
**Summary**
Step 10 For two of the new test records select <Test Result> positive.  The <Results entered by (McClure, Troy)  is not displayed

**To Reproduce**
1. Log in as troymcclure
2. Go to Step 10 
3. For two of the new test records select <Test Result> positive.  
4. The <Test Results> entered by" McClure, Troy)  is not displayed

**Expected behavior**
Step 10:  For two of the new test records select <Test Result> positive.  The <Results entered by (McClure, Troy)  should be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/52667706/66335140-5bc29600-e908-11e9-8c1a-2b6a9e6f3c43.png)

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Critical

**Additional context**

**Comment by aatmns** [comment]
Defect confirmed. The "Results Entered by" column is not visible.
However, the test result records were saved successfully in the testing environment.
