### ISSUE TITLE
HPS08: Unable to edit a reopened human disease report

### ISSUE THREAD

**Issue by tonihudson06** [EIDSS/EIDSS7#211]
**Summary**
When one user reopened a case, the other user was unable to edit the case because it saved as read-only except for the "report status" field.

**To Reproduce**
1. Log in as marinasmith
2. select human-->disease report
3.  Enter information for "disease", "report status", "first name", and "last name"
4. Open record for Edward Talbot in edit mode
5. Change report status to "in process"
6. Review case and submit
7. Return to dashboard and logout
8. Login as russelpeters and verify new report

**Expected behavior**
When the record is opened in edit mode, the information is supposed to be editable/modifiable

**Screenshots**

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based): HPS08

**Issue severity (Optional)**
Severity (critical, major, minor, low): Major

**Additional context**

**Comment by nlipskaya** [comment]
Issue is confirmed, but intermittent.
