### ISSUE TITLE
ADM26 - Make fields required  

### ISSUE THREAD

**Issue by Aj-Kakar** [EIDSS/EIDSS7#212]
**Summary**
Updated the system to make age and DOB fields required, but unable to verify. Getting the following error when searching human disease reports:

"A problem has occurred on this web site. Please try again. If this error continues, please contact support."

**To Reproduce**
1. Log in as rykermase 
2. Go to human > disease report
3. Search "HUM" > double click on the first row entry
4. System returns the following error: A problem has occurred on this web site. Please try again. If this error continues, please contact support."

**Expected behavior**

**Screenshots**

![ADM26](https://user-images.githubusercontent.com/52667376/66336378-f1f7bb80-e90a-11e9-8b91-623612f026c8.png)

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by aatmns** [comment]
Not able to recreate this defect in the testing environment.
DOB field has turned required:
![212](https://user-images.githubusercontent.com/32458032/66337932-1acd8000-e90e-11e9-87f2-fee15aaada21.PNG)

**Comment by jkkannan** [comment]
Needs to be retested in GAT.
