### ISSUE TITLE
LAB08 Mark a test for deletion

### ISSUE THREAD

**Issue by Chavez34** [EIDSS/EIDSS7#213]
**Summary**
Step 4.  Select the samples Menu and select <Lab Record Deletion > Delete Test button does not activate

**To Reproduce**
1. Log in as mollyrue
2. Go to Step 4 
3. Check the selection boxes for any two test records.
4. Select the Samples Menu and select Lab Record Deletion >Delete Test; the "Delete Test" button does not activate.

**Expected behavior**

Go to Step 4: 
-Check the selection boxes for any two test records.
-Select the Samples Menu and select Lab Record Deletion >Delete Test; the "Delete Test" button does not activate.

**Screenshots**
![image](https://user-images.githubusercontent.com/52667706/66336744-ae518180-e90b-11e9-8558-18b8d969837c.png)

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Critical

**Additional context**

**Comment by aatmns** [comment]
Not able to replicate the defect.
The Delete Test button is active in the testing environment:
![213](https://user-images.githubusercontent.com/32458032/66338250-bf4fc200-e90e-11e9-8db0-de6907f2cda8.PNG)

The system deleted test records correctly.

**Comment by jkkannan** [comment]
Needs to be retested in GAT.
