### ISSUE TITLE
HPS09: Survivor Record not titled

### ISSUE THREAD

**Issue by tonihudson06** [EIDSS/EIDSS7#214]
**Summary**
In steps #13 and #16 of script HPS09, the person  record #1 (survivor record) isn't distinguished from the superseded record; both are title-less. I was booted out of and had to restart this script multiple times.

**To Reproduce**
1. Log in as jefflisker
 

**Expected behavior**
Surviving and Superseded records should be distinguished through proper labeling 

**Screenshots**

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based): HPS09

**Issue severity (Optional)**
Severity (critical, major, minor, low): Minor

**Additional context**

**Comment by nlipskaya** [comment]
Known issue.
