### ISSUE TITLE
HPS10: Region and Rayon fields not prepopulated

### ISSUE THREAD

**Issue by tonihudson06** [EIDSS/EIDSS7#216]
**Summary**
In step #5 of HPS10, the region and rayon fields were not prepopulated as expected

**To Reproduce**
1. Log in as dianaross
2. Go to Human-->Aggregate Disease Report
3. Click on Add
4. Populate fields per script

**Expected behavior**
Six fields are supposed to prepopulate; two ("region" & "rayon") of the six fields did not prepopulate

**Screenshots**

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based): HPS10

**Issue severity (Optional)**
Severity (critical, major, minor, low): Minor

**Additional context**

**Comment by aatmns** [comment]
Defect confirmed in the testing environment.
Recommendation to mark this as minor.
The system completed the scenario task.
