### ISSUE TITLE
LAB13 Create a batch test

### ISSUE THREAD

**Issue by EBH2001** [EIDSS/EIDSS7#218]
**Summary**
Step 14 - the test result (negative) of batch was not created.

**To Reproduce**
1. Log in as troymcclure
2. Go to Step 13  select "OK" 
3. Go to Step 14  the test result (negative) is not created.

**Expected behavior**
1. Go to Step 13 select "OK"
2. Go to Step 14 test result (negative) created

**Screenshots**
![image](https://user-images.githubusercontent.com/16134915/66400890-4acd5f80-e9b0-11e9-971b-bc575a55296b.png)

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by aatmns** [comment]
Defect confirmed in the testing environment.
