### ISSUE TITLE
HPS14: Problem loading results to dashboard

### ISSUE THREAD

**Issue by tonihudson06** [EIDSS/EIDSS7#219]
**Summary**
In Step #15 of HPS14 when asked to return to the dashboard, received an error message which stated "There was a problem loading items for the dashboard. Please contact an administrator".

**To Reproduce**
1. Log in as johnsnow
2. Go to Human-->ILI aggregate form
3. Select weeks
4. Within ILI grid fill in information for the respective field for the Telavi Central Hospital
5. Select + control
6. Return to ILI Aggregate Record
7. Complete steps 4-6 for Kvareli MPHC and Telavi MPHC
8. Submit & note new form ID
9. Return to dashboard

**Expected behavior**
Epidemiologist dashboard is displayed

**Screenshots**

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based): HPS14

**Issue severity (Optional)**
Severity (critical, major, minor, low): Major

**Additional context**

**Comment by aatmns** [comment]
Unable to replicate the defect in the testing environment.
The dashboard displayed after the save operation.

Record:
![219-1](https://user-images.githubusercontent.com/32458032/66421906-bcb89f80-e9d6-11e9-87ec-7150cdc8ca73.PNG)

Success message:
![219-2](https://user-images.githubusercontent.com/32458032/66421933-c7733480-e9d6-11e9-8f66-164ac891cdee.PNG)

Dashboard displayed:
![219-3](https://user-images.githubusercontent.com/32458032/66421945-ce9a4280-e9d6-11e9-8ba0-a80997ff31a9.PNG)
