### ISSUE TITLE
HPS16 - Unable to print disease reports

### ISSUE THREAD

**Issue by tonihudson06** [EIDSS/EIDSS7#220]
**Summary**
Steps 5-7 in HPS16 did not work. I was unable to print the list of disease reports and save print as a PDF.

**To Reproduce**
1. Log in as johnsnow
2. Go to Human-->Disease Report
3. Search for prompted criteria
4. Select print control
5. Select OK
6. Select print and save as PDF

**Expected behavior**
The system displays a "printing document" message, displays options to select a printer and allows user to save as a PDF. 

**Screenshots**

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based): HPS16

**Issue severity (Optional)**
Severity (critical, major, minor, low): Major

**Additional context**

**Comment by aatmns** [comment]
Unable to replicate defect in the testing environment.
The system generated the printout form:
![220-1](https://user-images.githubusercontent.com/32458032/66422237-541df280-e9d7-11e9-92b7-420ebf6930e1.PNG)

The PDF printout was printed into the PDF form successfully:
[hps16-printout.pdf](https://github.com/EIDSS/EIDSS7/files/3703983/hps16-printout.pdf)
