### ISSUE TITLE
VAS02, VAS04, and VAS05 duplicate records warning message

### ISSUE THREAD

**Issue by jeanmrichards** [EIDSS/EIDSS7#221]
**Summary**
All as michael winston:
VAS 02 step 9 - confirming ASC was saved - when searching I had to try 3x with no results, then I added it again and received duplicate records warning, clicked "no" to avoid creating duplicate record, searched again for the original one I had added and saved, and it was found in search.

VAS 04 step 7 - adding a new species/sample/planned number line - when I clicked submit I get duplicate records warning - I clicked "yes" to save anyway and when I searched in step 9 I see the new line I added and only see one despite duplicate record warning

VAS 05 step 6 - when changing to "closed" and trying to submit, received duplicate record warning and clicked "yes, save anyway" and was kicked out to login screen.

logged in as ellen skylar (admin)
VAS 05 tried again to change to closed and again received the duplicate warning message as ellen. was able to click "yes" and save anyway.

Screenshot attached.

![VAS05 duplicate records](https://user-images.githubusercontent.com/52710250/66403552-c29d8900-e9b4-11e9-8586-afa0e1e363e7.PNG)

**To Reproduce**
1. Log in as 
2. Go to 
3. Click on 

**Expected behavior**

**Screenshots**

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by EBH2001** [comment]
This is a known issue.
