### ISSUE TITLE
LAB14: Validate a test result

### ISSUE THREAD

**Issue by Chavez34** [EIDSS/EIDSS7#222]
**Summary**
Step 9 - select edit icon for any  sample record of the Lab Sample IDs recorded in Step 5. Open test details, and the <Test Status> for any validated sample records is not set to Final.

**To Reproduce**
1. Log in as lisasimpson
2. Go to Step 9 select edit icon for any any sample record of the Lab Sample IDs recorded in Step  5
3. Open test details, and the <Test Status> for validated sample records is not set to Final.

**Expected behavior**

2. Go to Step 9 select edit icon for any any sample record of the Lab Sample IDs recorded in Step  5
3. Open test details, and the <Test Status> for validated sample records isset to Final.

**Screenshots**
![image](https://user-images.githubusercontent.com/52667706/66402901-ad742a80-e9b3-11e9-9041-b4ff356facaf.png)

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by aatmns** [comment]
LAB14.
Not able to replicate in the testing environment.
The system operated as designed.

Selected one lab test to approve:
![222-1](https://user-images.githubusercontent.com/32458032/66415613-fc2cbf00-e9c9-11e9-92b9-8181aba503e8.PNG)

Saved approved lab test:
![222-2](https://user-images.githubusercontent.com/32458032/66415635-0bac0800-e9ca-11e9-9555-12dcc60eac12.PNG)

Verified in the properties:
![222-3](https://user-images.githubusercontent.com/32458032/66415658-18306080-e9ca-11e9-8549-92bad16263d6.PNG)

**Comment by jkkannan** [comment]
Plan to retest tomorrow.
