### ISSUE TITLE
ADM03 Accessory Code

### ISSUE THREAD

**Issue by AllannaAnstaett** [EIDSS/EIDSS7#225]
**Summary**
Currently you can only pick one code. If you are wanting the user to select two then they have to know how to "Shift" to select the second code. 

Suggestion: Adding check boxes so the user can just select multiple accessory codes without jumping through any hoops. 

**To Reproduce**
1. Log in as adamanders
2. Go to Administration->Organizations->New
3. Click on Accessory Code

**Expected behavior**
To be able to click multiple with out using the shift function 

**Screenshots**

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based): ADM03 Administration 

**Issue severity (Optional)**
Severity (critical, major, minor, low): Minor 

**Additional context**

**Comment by aatmns** [comment]
Recommend to mark as a suggestion.
