### ISSUE TITLE
Ad hoc: User notification pages displayed in reverse order from Dashboard

### ISSUE THREAD

**Issue by billfleck** [EIDSS/EIDSS7#227]
**Summary**
User notification pages displayed in reverse order (3-2-1 instead of 1-2-3) from Dashboard.  The pages display correctly (1-2-3) when viewed from other pages (ex - Human - Disease Report).

**To Reproduce**
1. Log in as johnsnow
2. Go to Epi user dashboard
3. Click on Notifications icon

**Expected behavior**
Three pages of notifications will display, 

**Screenshots**
![Notifications backwards](https://user-images.githubusercontent.com/56310473/66406812-38582380-e9ba-11e9-8da7-f2ebc94de5b9.png)

**Additional details:**
 - Build: 98.0
 - Script title (enter ad hoc if not script-based): ad hoc

**Issue severity (Optional)**
Severity (critical, major, minor, low): 

**Additional context**

**Comment by aatmns** [comment]
Defect confirmed in the testing environment.
