### ISSUE TITLE
ADM05: Missing map and incorrect pop up 

### ISSUE THREAD

**Issue by AllannaAnstaett** [EIDSS/EIDSS7#228]
**Summary**
When I go to step 6 and select map nothing pops up. Also after I submit at step 9 it asks if I want to create another record and does not show step 10 as the script describes. 

**To Reproduce**
1. Log in as adamanders
2. Go to Administration->Settlements 
3. Click on Map

**Expected behavior**
I would expect the map to pop up so I could zoom. 
**Screenshots**

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based): ADM06 Administration 

**Issue severity (Optional)**
Severity (critical, major, minor, low): minor

**Additional context**

**Comment by aatmns** [comment]
Map not displaying - not able to replicate in the testing environment.
![228](https://user-images.githubusercontent.com/32458032/66416437-ce487a00-e9cb-11e9-86f9-0a47a256c0b5.PNG)


Creating another record - a confirmed defect.
