### ISSUE TITLE
VAS07 no section title for detailed animals and samples section

### ISSUE THREAD

**Issue by jeanmrichards** [EIDSS/EIDSS7#229]
**Summary**
with step 18, navigate to detailed animals and samples section, there is no section with that title. Upon review of the whole session in step 26 there is also not a section with this title. You can still click add and enter info, but it's not clear what you are adding with no title there.  see screenshot

**To Reproduce**
1. Log in as david robbins
2. Go to script vas07
![VAS 07 detailed animals and samples section](https://user-images.githubusercontent.com/52710250/66407617-7f92e400-e9bb-11e9-9d44-8c85040eefab.PNG)

3. Click on 

**Expected behavior**

**Screenshots**

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by EBH2001** [comment]
Defect confirmed.

**Comment by jkkannan** [comment]
CSS issue
