### ISSUE TITLE
[BUG] Human Aggregate form did not display

### ISSUE THREAD

**Issue by shahina77** [EIDSS/EIDSS7#23]
**Summary**
Human aggregate Disease Report data entry fields are failed to display. Missing data entry fields are: Month, Notification sent by institution, officer and date. So subsequent steps also failed to test for HPS10.

**To Reproduce**
1. Log in as Diana Ross
2. Go to Human --> Aggregate Disease Report and Select ADD control
3. System did not display a Human Aggregate Disease Report for data entry; unable to execute all other steps.

**Expected behavior**
System should display Human Aggregate Disease Report and allow data entry.

Screenshots**

**Additional details:**
 - Build: 77
 - (enter ad hoc if not script-based): HPS10 Human Passive Surveillance 

**Issue severity**
Severity (critical, major, minor, low): Critical
 
**Additional context**
![HPS10](https://user-images.githubusercontent.com/52667472/60833986-8bd58e00-a18d-11e9-815b-20c9540037a7.png)

**Comment by EBH2001** [comment]
Not reproducible in Integration and PreGAT.

**PLEASE SEE ATTACHMENT**
[HPS10_GitHub#23_Enter aggregate report_NotReproducible.docx](https://github.com/EIDSS/EIDSS7/files/3390514/HPS10_GitHub.23_Enter.aggregate.report_NotReproducible.docx)
