### ISSUE TITLE
VAS 07 GAT user permissions (?) issues

### ISSUE THREAD

**Issue by jeanmrichards** [EIDSS/EIDSS7#230]
**Summary**
with step 10, trying to submit the new session, kicked out as david robbins. session did not time out. logged in as ellen skylar and was able to go through steps again and submit successfully. 

On step 25 return to dashboard ellen skylar still gets "notifications" instead of "my investigations". This seems random and with all users. not consistent. Would be very frustrating in real life. 

**To Reproduce**
1. Log in as 
2. Go to 
3. Click on 

**Expected behavior**

**Screenshots**

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by EBH2001** [comment]
Defect confirmed.
