### ISSUE TITLE
LAB17 Approve samples to be destroyed

### ISSUE THREAD

**Issue by Chavez34** [EIDSS/EIDSS7#232]
**Summary**
Step 9. Verification step:  in the same section enter the Lab Sample ID in the search field and select search.The approved samples records display in the Samples tab.  The approved samples records display with <Sample Status> Deleted.

**To Reproduce**
1. Log in as lisasimpson
2. Go to Step 9:  Verification step:  in the same section enter the Lab Sample ID in the search field and select search.
3. The approved samples records display in the Samples tab.  
4. The approved samples records display with <Sample Status> Deleted.

**Expected behavior**
2. Go to Step 9:  Verification step:  in the same section enter the Lab Sample ID in the search field and select search.
3. The approved samples records display in the Samples tab.  
4. The approved samples records display with <Sample Status> Destroyed.

**Screenshots**
![image](https://user-images.githubusercontent.com/52667706/66413365-39428280-e9c5-11e9-941e-92e67544bc49.png)

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by aatmns** [comment]
Not defect. 
The system operated as designed.
Minor issue.
