### ISSUE TITLE
VAS10 adding new avian active surv session same issue with non-visible fields

### ISSUE THREAD

**Issue by jeanmrichards** [EIDSS/EIDSS7#233]
**Summary**
at step 6 with review, you should see all sections and all fields but they are not visible. When you save and submit and then go back in step 9 to verify, you can see all sections and fields. 

**To Reproduce**
1. Log in as thomas wade
2. Go to follow script (see screen shot from previous livestock active surv session script VAS07 - same for avian)
3. Click on 

**Expected behavior**

**Screenshots**

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by jkkannan** [comment]
Related to #231 regarding fields not being expanded in both livestock and avian.
