### ISSUE TITLE
VAS10 thomas wade permissions (?) issue

### ISSUE THREAD

**Issue by jeanmrichards** [EIDSS/EIDSS7#234]
**Summary**
return to dashboard command step 8 shows unaccessioned samples instead of chief epi dashboard. on log in, my investigations showed up where it should have in step 2

**To Reproduce**
1. Log in as 
2. Go to 
3. Click on 

**Expected behavior**

**Screenshots**

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by EBH2001** [comment]
Defect confirmed.
