### ISSUE TITLE
VPS10 unable to submit vet agg disease report

### ISSUE THREAD

**Issue by jeanmrichards** [EIDSS/EIDSS7#235]
**Summary**
nothing happens when you submit in step 10
see steps recorder

**To Reproduce**
1. Log in as ryan johnson
[VPS 10 unable to submit vet aggregate disease report.zip](https://github.com/EIDSS/EIDSS7/files/3703639/VPS.10.unable.to.submit.vet.aggregate.disease.report.zip)

2. Go to 
3. Click on 

**Expected behavior**

**Screenshots**

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by aatmns** [comment]
Defect is confirmed in the testing environment.

**Comment by jkkannan** [comment]
Closed during remediation in Build 99.0.  Script passed.
