### ISSUE TITLE
OM03: Multiple outbreak ID options; neither produce case report for Last name "Talbot"

### ISSUE THREAD

**Issue by tonihudson06** [EIDSS/EIDSS7#236]
**Summary**
Script failure following Step 6 of 29 in OM03. The script directs user to enter in data in the advance search box. When the hyperlinked outbreak is selected multiple outbreak IDs under the cases tab appears (instead of one). Neither of the two outbreak IDs had a recorded case under the last name "Talbot".

**To Reproduce**
1. Log in as johnsnow
2. Go to Outbreak-->outbreak
3. Select Advanced Search
4. Enter search criteria into respective search boxes
5. Select outbreak ID hyperlink
6. Select import control
7. Enter respective search criteria

**Expected behavior**
Search results display an anthrax-GI record for Edward Talbot

**Screenshots**

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based): OM03

**Issue severity (Optional)**
Severity (critical, major, minor, low): Critical

**Additional context**

**Comment by aatmns** [comment]
Defect confirmed in the testing environment.
