### ISSUE TITLE
VEC03 - Vector Surveillance Reporting

### ISSUE THREAD

**Issue by Aj-Kakar** [EIDSS/EIDSS7#237]
**Summary**
Unable to search a vector surveillance session:
<status> in process
<vector type> mosquito 
<disease> west nile fever

**To Reproduce**
1. Log in as jeffjordan
2. Go to vector > surveillance session 
3. search:
<status> in process
<vector type> mosquito 
<disease> west nile fever

**Expected behavior**

**Screenshots**

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by aatmns** [comment]
Unable to replicate in the testing environment.
The record is displayed:
![237](https://user-images.githubusercontent.com/32458032/66418205-94797280-e9cf-11e9-89d3-0e9a5b0aa3b1.PNG)

**Comment by jkkannan** [comment]
Unable to replicate. Close issue.
