### ISSUE TITLE
VAS11 missing fields and pre-populated info

### ISSUE THREAD

**Issue by jeanmrichards** [EIDSS/EIDSS7#238]
**Summary**
step 5 there is no species box (should be species chicken per script) and there is nothing in the disease box (should be prepopulated with AIB) and settlement type should be village (it's blank).

**To Reproduce**
1. Log in as david robbins
2. Go to 
3. Click on 

**Expected behavior**

**Screenshots**

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by EBH2001** [comment]
Minor defect for species box
Defect confirmed for missing disease and settlement type

**Comment by jkkannan** [comment]
Two issues with differing severity--as noted above.
