### ISSUE TITLE
VAS11 no detailed animals and samples section, unable to save 

### ISSUE THREAD

**Issue by jeanmrichards** [EIDSS/EIDSS7#239]
**Summary**
step 12, no section title for this area 
step 13, when you click add anyway and get the pop up box, enter the info as per step 13, you can't save the info. nothing happens when you click save control. 

**To Reproduce**
1. Log in as david robbins
[VAS 11 cant save detailed animal and sample info.zip](https://github.com/EIDSS/EIDSS7/files/3703843/VAS.11.cant.save.detailed.animal.and.sample.info.zip)

2. Go to 
3. Click on 

**Expected behavior**

**Screenshots**

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by EBH2001** [comment]
Defect confirmed for missing section title

Not reproducible for saving sample.
![image](https://user-images.githubusercontent.com/16134915/66422450-b2e36c00-e9d7-11e9-81ab-965a202d2f48.png)

**Comment by jkkannan** [comment]
Reproducible.
