### ISSUE TITLE
VAS12 Linking standalone veterinary Active Surveillance Session to a Campaign

### ISSUE THREAD

**Issue by Chavez34** [EIDSS/EIDSS7#241]
**Summary**

Step 13 - Verification step:>> Session to open a search screen. Enter <Settlement> Baso is not in dropdown 

**To Reproduce**
1. Log in as davidrobbins
2. Go to Step 13 - Verification step:>> Session to open a search screen. Enter <Settlement> Baso is not in dropdown 

**Expected behavior**
2. Go to Step 13 - Verification step:>> Session to open a search screen. Enter <Settlement> Baso is in dropdown 

**Screenshots**
![image](https://user-images.githubusercontent.com/52667706/66421951-d0640600-e9d6-11e9-8dc8-b814e2260e79.png)

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by jkkannan** [comment]
Script issue; was able to search and verify with correct search criteria. Closed out.
