### ISSUE TITLE
LAB03 Accession veterinary samples

### ISSUE THREAD

**Issue by Chavez34** [EIDSS/EIDSS7#242]
**Summary**
Step 5 - Unable to check the selection boxes for the first five unaccessioned samples.

**To Reproduce**
1. Log in as troymcclure
2. Go to Step 5 - Unable to check the selection boxes for the first five unaccessioned samples.

**Expected behavior**
Go to Step 5 - Able to check the selection boxes for the first five unaccessioned samples..

**Screenshots**
![image](https://user-images.githubusercontent.com/52667706/66485087-2dfb5f80-ea76-11e9-9ece-0f0a59b9970e.png)

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by aatmns** [comment]
Unable to reproduce the defect in the testing environment.
The system allowed to check unaccessioned samples for Troy McClure:
![242](https://user-images.githubusercontent.com/32458032/66487995-4457ea00-ea7b-11e9-8fb1-30fb706f4d02.PNG)
