### ISSUE TITLE
ADM23 - Update Animal Disease List

### ISSUE THREAD

**Issue by Aj-Kakar** [EIDSS/EIDSS7#243]
**Summary**
I was unable to verify my new addition of a disease. Also, few fields are not in English, please see screenshot.  

**To Reproduce**
1. Log in as rykermase
2. Go to admin > reference editor > diseases 
3. Click on add
4. add disease and verify 

**Expected behavior**

**Screenshots**

![ADM23](https://user-images.githubusercontent.com/52667376/66486216-26d55100-ea78-11e9-8e4f-8e6f0a17a05c.png)

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by aatmns** [comment]
Unable to replicate the defect.
The system created a new disease record successfully.

Steps:
![243-1](https://user-images.githubusercontent.com/32458032/66488918-c1d02a00-ea7c-11e9-8a74-5ea9d0fbcae7.PNG)

![243-2](https://user-images.githubusercontent.com/32458032/66488929-c5fc4780-ea7c-11e9-831c-bbdc88af4e9f.PNG)

![243-3](https://user-images.githubusercontent.com/32458032/66488936-c98fce80-ea7c-11e9-8179-80a5d2ae138b.PNG)

**Comment by jkkannan** [comment]
Discussion on sort order of diseases; should it be alphabetical or show latest disease added? Req in 6.1 was alphabetical.
