### ISSUE TITLE
LAB05 Mark a sample for deletion

### ISSUE THREAD

**Issue by Chavez34** [EIDSS/EIDSS7#244]
**Summary**
Step 4  - Script error -  spelling error Russel Reading (correct Russel Redding)
Step 5  - William Gates  - not Russel Redding
Step 5. Sample ID is not displayed

**To Reproduce**
1. Log in as troymcclure
2. Go to Steps 4 and 5 and correct script errors
3. Step 5 Sample ID is not displayed

**Expected behavior**
1. Correct Script errors Steps 4 and 5
2. Lab Sample ID should be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/52667706/66486535-cbf02980-ea78-11e9-846c-1587ffa0bcfa.png)

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by aatmns** [comment]
Defect confirmed. The search for "redding" is not operating. Deletion of samples is not operating.

**Comment by aatmns** [comment]
Not able to replicate this defect in the testing environment.
Was able to delete three samples:

![244-1](https://user-images.githubusercontent.com/32458032/66491170-4c665880-ea80-11e9-8e27-35b05761f6cb.PNG)

![244-2](https://user-images.githubusercontent.com/32458032/66491183-512b0c80-ea80-11e9-9d15-06c5c4fbc2c4.PNG)

![244-3](https://user-images.githubusercontent.com/32458032/66491194-55efc080-ea80-11e9-8f0a-55e5c42bdb13.PNG)
