### ISSUE TITLE
No disease report record found

### ISSUE THREAD

**Issue by tonihudson06** [EIDSS/EIDSS7#246]
**Summary**
When prompted to search for a disease report for a particular individual there were no reports found.

**To Reproduce**
1. Log in as marinasmith
2. Go to Human-->Disease Report
3. Enter information to search for disease report

**Expected behavior**
A human disease report for Edward Talbot with Brucellosis-unspecified is listed

**Screenshots**
![image](https://user-images.githubusercontent.com/56262298/66489937-63a44680-ea7e-11e9-8d3a-7e3fc5e7bc2a.png)

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based): HPS08

**Issue severity (Optional)**
Severity (critical, major, minor, low): Major

**Additional context**

**Comment by nlipskaya** [comment]
![image](https://user-images.githubusercontent.com/30051006/66493615-5ab67380-ea84-11e9-94cb-3221ccaa472a.png)

**Comment by jkkannan** [comment]
Spoke to tester and she was able to successfully retrieve report and continue with script.
