### ISSUE TITLE
Lab17 Approve samples to be desroyed

### ISSUE THREAD

**Issue by Chavez34** [EIDSS/EIDSS7#247]
**Summary**
Step 5  Check the selection box for samples matching the following <Action Requested> Sample deletion. The sample record text is not displayed in bold, and the Save control is not enabled. 

**To Reproduce**
1. Log in as lisasimpson
2. Go to Step 5  Check the selection box for samples matching the following <Action Requested> Sample deletion. The sample record text is not displayed in bold and the Save  control is not enabled. 

**Expected behavior**
Go to Step 5  Check the selection box for samples matching the following <Action Requested> Sample deletion. The sample record text displayed in bold and the Save control is enabled. 

**Screenshots**
![image](https://user-images.githubusercontent.com/52667706/66490640-7c612c00-ea7f-11e9-979f-4defd8574a8c.png)

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by aatmns** [comment]
Defect confirmed in the testing environment.
