### ISSUE TITLE
Date of Symptom Onset field was not populated as expected

### ISSUE THREAD

**Issue by tonihudson06** [EIDSS/EIDSS7#248]
**Summary**
When prompted to navigate to the clinical information section, the date of symptom onset is supposed to prepopulate and match with the original disease report but the box did not contain any data

**To Reproduce**
1. Log in as johnsnow
2. Go to Outbreak-->Outbreak
3. Search for specified criteria in the Advanced Search box
5. Select a hyperlinked outbreak ID
6. Import and select a human case
7. Search for a specified case and select the hyperlinked report ID
8. Select edit icon & review the outbreak case summary and notification section
9. Navigate to the case location & clinical information sections

**Expected behavior**
The date of symptom onset is supposed to prepopulate and match the original disease report

**Screenshots**
![image](https://user-images.githubusercontent.com/56262298/66492707-d4e5f880-ea82-11e9-9c73-67813c27831c.png)

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based): OM03

**Issue severity (Optional)**
Severity (critical, major, minor, low): Minor

**Additional context**

**Comment by jkkannan** [comment]
Closed as a data issue.  The original record did not have a date of symptom onset entered.
