### ISSUE TITLE
Case ID not generated as expected

### ISSUE THREAD

**Issue by tonihudson06** [EIDSS/EIDSS7#249]
**Summary**
New case ID not generated upon submitting new report

**To Reproduce**
1. Log in as johnsnow
2. Go to Outbreak-->Outbreak
3. Search for specified criteria in the Advanced Search box
5. Select a hyperlinked outbreak ID
6. Import and select a human case
7. Search for a specified case and select the hyperlinked report ID
8. Select edit icon & review the outbreak case summary and notification section
9. Navigate to the case location & clinical information sections
10. Enter specified case criteria 
11. navigate to outbreak investigation section
12. review and submit

**Expected behavior**
EIDSS success message is displayed with a new case ID generated

**Screenshots**
![image](https://user-images.githubusercontent.com/56262298/66492888-22626580-ea83-11e9-814a-3766df206fef.png)

![image](https://user-images.githubusercontent.com/56262298/66492907-2a220a00-ea83-11e9-8b9b-9590ef7bfab0.png)

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based): OM03

**Issue severity (Optional)**
Severity (critical, major, minor, low): Minor 

**Additional context**

**Comment by jkkannan** [comment]
Confirmed defect.
