### ISSUE TITLE
LAB: Region does not display and report ID does not populate, unable to register new samples

### ISSUE THREAD

**Issue by Chavez34** [EIDSS/EIDSS7#25]
**Summary**
Region does not display and report ID does not populate unable to register new samples in the laboratory module

**To Reproduce**
1. Log in as mollyrue
2. Go to step #6 >Region:  does not populate>Report ID>no report ID generated>Report ID does not populate
2. Click on '.#6>Region>Kakheti (not in drop down)>Report ID does not populate>>> unable to enter subsequent steps

**Expected behavior**

Screenshots**

**Additional details:**
 - Build: 77
 - Script title (enter ad hoc if not script-based): LAB06

**Issue severity**: Critical

**Additional context**

**Comment by EBH2001** [comment]
Not reproducible in Integration build 83.1.

**PLEASE SEE ATTACHMENT**

[LAB06_GitHub#25_Register new sample_NotReproducible.docx](https://github.com/EIDSS/EIDSS7/files/3390528/LAB06_GitHub.25_Register.new.sample_NotReproducible.docx)
