### ISSUE TITLE
Mark a sample as deleted due to clerical error

### ISSUE THREAD

**Issue by Chavez34** [EIDSS/EIDSS7#250]
**Summary**
Step 7 -  1. Enter reason for Deletion > = clerical error
               2. Select Delete control ; the system does not close the modal window.

**To Reproduce**
1. Log in as troymcclure
2. Go to Step 7 - 1. Enter reason for Deletion > = clerical error
                           2. Select Delete control ; the system does not close the modal window.

**Expected behavior**
Go to Step 7 - 1. Enter reason for Deletion > = clerical error
                       2. Select Delete control ; the system closes the modal window.

**Screenshots**
![image](https://user-images.githubusercontent.com/52667706/66492863-14ace000-ea83-11e9-8300-6ada5f40e85b.png)

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by aatmns** [comment]
Unable to reproduce in the testing environment.

Steps:
![250-1](https://user-images.githubusercontent.com/32458032/66494721-1e841280-ea86-11e9-98c1-74630eedc735.PNG)

![250-2](https://user-images.githubusercontent.com/32458032/66494729-22b03000-ea86-11e9-92d2-ee428b645fdc.PNG)

![250-3](https://user-images.githubusercontent.com/32458032/66494742-2643b700-ea86-11e9-9ff6-478c0cdfd501.PNG)

![250-4](https://user-images.githubusercontent.com/32458032/66494757-293ea780-ea86-11e9-886e-2f34ad2a1f28.PNG)
