### ISSUE TITLE
VPS10 Display and script issues 

### ISSUE THREAD

**Issue by billfleck** [EIDSS/EIDSS7#252]
**Summary**
Step 6 display pops up on a really small box that requires continuous scrolling when there is enough window space to accommodate.  

Step 12 reads "Aggregate Disease Report" when the drop down says "Aggregate Report"

**To Reproduce**
1. Log in as 
2. Go to 
3. Click on 

**Expected behavior**

**Screenshots**
![Disease Matrix](https://user-images.githubusercontent.com/56310473/66573982-7a5fa180-eb41-11e9-87ef-d79a9b937a6d.PNG)

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based):

**Issue severity (Optional)**
Severity (critical, major, minor, low): minor

**Additional context**

**Comment by christhompson17** [comment]
This will be partially cleaned up as part of the CSS improvement in December. If the user collapses the navigation menu, it does improve the screen functional area some. Ultimately a scrollbar will probably be necessary due to the app having to be responsive for smaller endpoint devices.
