### ISSUE TITLE
[BUG] Human Aggregate--Unable to retrieve record to edit

### ISSUE THREAD

**Issue by shahina77** [EIDSS/EIDSS7#26]
**Summary**
Failed to display a monthly report when trying to edit the report for Month, Rayon, Kakheti, Kvareli.

**To Reproduce**
1. Log in as dianaross
2. Go to Human--> Aggregate Disease Report
2. Search for report per step 3
4. Select start date of 04/01/2019, search; no report matching those search parameters was retrieved. 

**Expected behavior**
Expect to see monthly report and be able to edit.

Screenshots**

**Additional details:**
 - Build: 77
 - (enter ad hoc if not script-based):HPS11 

**Issue severity**
Severity (critical, major, minor, low): Critical
**Additional context**
![HPS11](https://user-images.githubusercontent.com/52667472/60834597-ffc46600-a18e-11e9-97b2-dc101218d322.png)

**Comment by EBH2001** [comment]
Not reproducible in Integration build 83.1.  Could have very well been a data issue.

**PLEASE SEE ATTACHMENT
[HPS11_GitHub#26_Modify aggregate disease report_NotReproducible.docx](https://github.com/EIDSS/EIDSS7/files/3390756/HPS11_GitHub.26_Modify.aggregate.disease.report_NotReproducible.docx)
**

**Comment by jkkannan** [comment]
Closed during GAT remediation.
