### ISSUE TITLE
AD HOC - System loading error

### ISSUE THREAD

**Issue by Aj-Kakar** [EIDSS/EIDSS7#27]
**Summary**
System keeps resulting in a loading error when clicking on the EIDSS logo.

**To Reproduce**
1. Log in as rykermase
2. Refer to Step recording attached 

**Expected behavior**
No load crashes from navigating around the site. 

Screenshots**
[System loading error.zip](https://github.com/EIDSS/EIDSS7/files/3373235/System.loading.error.zip)

**Issue severity**
Minor to Low

**Build**
79

**Comment by christhompson17** [comment]
Rodney was able to recreate in the Admin module. The issue only seems to occur after a timeout period, and only in the Admin module.
