### ISSUE TITLE
VPSO2/1 Problem with saving and entering Street number and Zip Code

### ISSUE THREAD

**Issue by AnnaSwiatecka** [EIDSS/EIDSS7#274]
**Summary**
Unable to use saved name of the farm's street and zip code

**Details**
Script ID (or enter ad hoc if ad hoc):VPSO2
Username: Adjara RVO
Build: 7.0.264.2
Severity (optional): medium

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to Farm/Livestock Add
2. Click on farm Address

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by easleyte** [comment]
Close:  Was able to create an Avian Farm and verified that all information was retained
