### ISSUE TITLE
LAB01 Bug 2

### ISSUE THREAD

**Issue by CarolChapman1** [EIDSS/EIDSS7#276]
**Summary**
Barcode not accessible after accession

**Details**
Script ID (or enter ad hoc if ad hoc): LAB01 Lab
Username: AdjaraHumanZDLTech
Build: 264.2
Severity (optional):M

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by aatmns** [comment]
Defect confirmed in the preGAT environment.
Unable to print the barcode of an existing sample.
