### ISSUE TITLE
Unable to Create Human Disease Report 

### ISSUE THREAD

**Issue by shahina77** [EIDSS/EIDSS7#278]
**Summary**
Unable to Create Human Disease Report 

**Details**
HPS03 Human Passive Surveillance  (or enter ad hoc if ad hoc):
Username: LanchkhutiDistrictVet
Build: 
Severity (optional): Critical 

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**
Diseased Report should be created from existing case information  

**Screenshots**

**Additional context**

**Comment by jkkannan** [comment]
Unable to add a disease report IF Personal ID Type = Unknown and ID field was not populated.
User was able to add disease reports to other person records.
Planned for fix in next build.

**Comment by shahina77** [comment]
Issue has been resolved
