### ISSUE TITLE
VPS03 Veterinary Passive Surveillance - Livestock an Avian Farm

### ISSUE THREAD

**Issue by AnnaSwiatecka** [EIDSS/EIDSS7#279]
**Summary**
Unable to add Zip code

**Details**
Script ID (or enter ad hoc if ad hoc): VPSO23
Username: Adjara Rvo
Build: 7.0264.2
Severity (optional): medium

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to Add New Person (Farm Owner)
2.Address

**Expected behavior**
Expected to be able to enter saved zip code

**Screenshots**

**Additional context**

**Comment by EBH2001** [comment]
![image](https://user-images.githubusercontent.com/16134915/169879036-d87544ff-7518-4f27-bd67-9d37a2fc99a1.png)

**Comment by EBH2001** [comment]
After looking at the script closely, it asks for the user to create a new Person record.  This is a known defect, user cannot create a new Person record from the Farm record.

**Comment by easleyte** [comment]
Close:  Was able to create a new veterinary farm record with a new farm owner and verify that entered information was retained.
