### ISSUE TITLE
ADMIN: New user group "non-passive surveillance" did not display in drop-down when creating a new employee (Admin Bug 003)

### ISSUE THREAD

**Issue by NatalieShapiro** [EIDSS/EIDSS7#282]
**Summary**
I was not able to add an individual to a newly created user group under "Admin --> Employees" because it wasn't a drop down option.

**Details**
Script ID (or enter ad hoc if ad hoc): ADM02 Administration, Step 9
Username: NCDCAdmin
Build: 7.0.264.2
Severity (optional): 

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to Admin, Employees, Add, Fill out details, under user group (account management), look for Non-Passive Surveillance 

**Expected behavior**
I would expect the new user group to show. 

**Screenshots**

**Additional context**

**Comment by NatalieShapiro** [comment]
Overall, I cannot add an employee to the new user group I created. I also tried under Administration>Security>User Groups. I searched for the person (jerry smith) and he didn't come up.

**Comment by jkkannan** [comment]
Retest script tomorrow
