### ISSUE TITLE
VPS04 - Update Veterinary farm Record

### ISSUE THREAD

**Issue by AnnaSwiatecka** [EIDSS/EIDSS7#283]
**Summary**
No confirmation that data was saved. After saving the data, it looked like the saving process was going on for 4 min. (the arrows of sign button were moving). After interrupting the saving, the data was saved.

**Details**
Script ID (or enter ad hoc if ad hoc): VPS04
Username: Adjara Rvo
Build: 
Severity (optional): medium

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to farm information and farm address, edit
2. Click on save

**Expected behavior**
A clear termination of saving process

**Screenshots**

**Additional context**

**Comment by aatmns** [comment]
Unable to reproduce.
The success message was displayed after the save:
![image](https://user-images.githubusercontent.com/32458032/169880463-9bebc97e-b5b8-4c1c-98c7-5dcb108cec57.png)

**Comment by jkkannan** [comment]
Retest on 5/24
