### ISSUE TITLE
ADM04: Deactivating employee's access to secondary site did not work (Admin Bug 004)

### ISSUE THREAD

**Issue by NatalieShapiro** [EIDSS/EIDSS7#285]
**Summary**
I unchecked jsmith01's access to Adjara Human ZDL (wasn't active under account management). However, when I logged into his account, it still showed under the "user - organization menu."

**Details**
Script ID (or enter ad hoc if ad hoc): ADMO4 Admin - step 6
Username: jsmith01
Build: 7.0.264.2
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Log in as jsmith01 (password EIDSStesting2022!) and see accounts listed at top. Log in as NCDC admin, and look him up under employees and see that "Adjara Human ZDL" is not supposed to be active. 

**Expected behavior**
I would expect not to see Adjara Human ZDL based on the scripts. 

**Screenshots**

**Additional context**

**Comment by NatalieShapiro** [comment]
**ENVIRONMENT ISSUES** Leaving open until #398 398 is solved. Can't verify with a new employee record. When I try to add a secondary site to a new employee record, it won't allow me to save because of an error with the personal ID type. Jsmith01 was fixed but this was an old record. This worked on in the GAT environment but not in external environment.

**Comment by NatalieShapiro** [comment]
**Cannot validate fix. New issues. See bug #398.**

**Comment by jkkannan** [comment]
Could not reproduce 1 Aug; walk-through on 2 Aug AM.

**Comment by NatalieShapiro** [comment]
@jkkannan I can't validate this script because there is a blocker ("Personal ID Type") when creating a new employee. I need an employee with two sites and I also need their password, which forces me to create a new account.

**Comment by NatalieShapiro** [comment]
Closing due to workaround IDed by Jaya. Validated fix.
