### ISSUE TITLE
VPS05 - Printing issue- the list printed doesn't match the list on the dashboard

### ISSUE THREAD

**Issue by AnnaSwiatecka** [EIDSS/EIDSS7#286]
**Summary**
 the list printed from pdf doesn't match the list on the dashboard (on the dasbboard 4 items are listed, on the printed version we received 10 records

**Details**
Script ID (or enter ad hoc if ad hoc): VPS05
Username: ADJARA  RVO
Build: 7.0.264.2
Severity (optional): Severe

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to farm searching, select criteria and print
2. Click on print

**Expected behavior**
Printed list (pdf) should match the list on the dashboard

**Screenshots**

**Additional context**

**Comment by EBH2001** [comment]
Not reproducible in PreGAT, build 265.9
![image](https://user-images.githubusercontent.com/16134915/169889986-f6a22296-da64-47fe-b175-18c6f0068f14.png)

**Comment by SrinivasaGoli** [comment]
Resolved.
