### ISSUE TITLE
Lab01 BUG 6

### ISSUE THREAD

**Issue by CarolChapman1** [EIDSS/EIDSS7#289]
**Summary**
Storage location showed Freezer, but no shelf, rack, or box menu- screen froze. Could not save or cancel

**Details**
Script ID (or enter ad hoc if ad hoc):LAB01
Username: AdjaraHumanZDLTech
Build: 264.2
Severity (optional):M

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by aatmns** [comment]
Defect is confirmed.
