### ISSUE TITLE
ADM04 Administration - Modify existing Org.

### ISSUE THREAD

**Issue by Aj-Kakar** [EIDSS/EIDSS7#29]
**Summary**

Script AMD04 wanted the user to update the Org information. The search functionality returned no results, unable to proceed with the rest of the script. 

**To Reproduce**
1. Log in as rykermase
2. Refer to Step recording attached 

**Expected behavior**

User should be able to search for an organization and update the organization information.

Screenshots**

[Can't find Org.zip](https://github.com/EIDSS/EIDSS7/files/3373275/Can.t.find.Org.zip)

**Issue severity**
Low

**Build**
79

**Comment by christhompson17** [comment]
This may not be a bug, this item needs to be checked by the data team to determine if "Institute of Internal Diseases" is in the DB. If it is not, then this is not a bug, and is a GAT data issue. Did confirm with @Aj-Kakar  that searches for other institutes that were displaying in the grid did work. Likely not a bug.
