### ISSUE TITLE
General

### ISSUE THREAD

**Issue by CarolChapman1** [EIDSS/EIDSS7#290]
**Summary**
Same sample entered several times with same ID- I destroyed same samples by autoclave, incineration and deleted for clerical error

**Details**
Script ID (or enter ad hoc if ad hoc): Lab01 and Lab02
Username: ADJARAHUMANZDLTECH
Severity (optional):H

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. 9look in records to see multiple samples with same name
2. Click on… 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jkkannan** [comment]
Retest using Imereti Human ZDL; load unaccessioned human samples today for testing 5/24.

**Comment by RyanLloyd1** [comment]
Multiple samples no longer entered - issue resolved; however, samples seem to disappear upon accepting/accessioning - see #403
