### ISSUE TITLE
VPS07 - Problem with saving Avian Disease Report

### ISSUE THREAD

**Issue by AnnaSwiatecka** [EIDSS/EIDSS7#291]
**Summary**
After creation of the Avian Disease Report, "Save" button can't complete the saving action (moving arrows). After coming back to farm Dashboard - no record saved.

**Details**
Script ID (or enter ad hoc if ad hoc): VPS07
Username: GURIA RVO
Severity (optional): medium

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to Farm Record; Add Avian (Avian Disease Report)
2. Click on Save

**Expected behavior**
After pushing Save button it should report "Record Saved"

**Screenshots**

**Additional context**

**Comment by aatmns** [comment]
Defect is confirmed and reproduced.
No Radzen error displayed.
![image](https://user-images.githubusercontent.com/32458032/169884699-6f78b7c5-18eb-4570-b103-e807be07588a.png)

**Comment by jkkannan** [comment]
Retest 5/24

**Comment by jkkannan** [comment]
Tester reports unable to save an ADR on 27 May

**Comment by AnnaSwiatecka** [comment]
Able to create the Avian report in GAT environment
