### ISSUE TITLE
VPS08 - Able to create double record for the same farm

### ISSUE THREAD

**Issue by AnnaSwiatecka** [EIDSS/EIDSS7#292]
**Summary**
No communicate that the duplicate was created

**Details**
Script ID (or enter ad hoc if ad hoc): VPS08
Username: KEDA RAYON VO
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Create the farm with the same data comparing to existing file
2. Click on save

**Expected behavior**
Communicate about double record should show up.

**Screenshots**

**Additional context**

**Comment by aatmns** [comment]
Defect confirmed.
No duplicate warning message was displayed.
![image](https://user-images.githubusercontent.com/32458032/169885811-a4a8ec14-3c8e-4144-a7f2-6bf7a3fd54a3.png)

**Comment by aatmns** [comment]
Issue is resolved.
The system correctly displays a duplicate record warning.
![image](https://user-images.githubusercontent.com/32458032/183890629-f3af0e4e-2625-47c5-99e2-67c638e4e270.png)

**Comment by easleyte** [comment]
Close:  System displayed the warning and allowed me to create the farm record
