### ISSUE TITLE
  System shutdown 

### ISSUE THREAD

**Issue by shahina77** [EIDSS/EIDSS7#296]
**Summary**
Unable to de-duplicate two person records into a single person record: system shutdown when clicked administration for deduplication  A clear and concise description of the issue.

**Details**
HPSO6 (or enter ad hoc if ad hoc):
Username: NCDCEPI
Severity (optional):

** chief epidemiologist >Search Person >select person record with a disease report>create a new person record with sale last and different first name>Create a new disease report > Select Administration > kicked out 
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jkkannan** [comment]
Check system functions for NCDCEpi; retest 5/24

**Comment by shahina77** [comment]
Issue has been resolved
