### ISSUE TITLE
ADMIN: Cannot give *new* user permissions to a disease (Admin Bug 007)

### ISSUE THREAD

**Issue by NatalieShapiro** [EIDSS/EIDSS7#299]
**Summary**
I created two employees, Allison Baird and Bubby Walsh. When I go to permissions in the disease editor for "test disease", I cannot find them via search to give them permissions.

**Details**
Script ID (or enter ad hoc if ad hoc): ADM11 Administration 
Username: NCDCAdmin
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Search for "Test disease" in disease editor, click on permissions button, click on add, add person type and search for actor names "Allison Baird" or "Bubby Walsh"

**Expected behavior**
I expect to see Allison and Bubby in the search results. 

**Screenshots**

**Additional context**

**Comment by jkkannan** [comment]
Retest tomorrow; may be an issue with organization not the same between new users and administrator.

**Comment by NatalieShapiro** [comment]
Closing as this was an issue between users versus admin org - however, I think there may be a separate issue since the new disease was duplicated in the disease record options (raising for awareness).
