### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by QuliyevaB** [EIDSS/EIDSS7#3]
I want to inform you following the link (http://192.255.51.93/Azerbaijan) I created an account to use the beta site, but there was an error on the system. For more details I add screenshot file.

![20180527_182646 1](https://user-images.githubusercontent.com/39673062/40587115-24220456-61dc-11e8-96d9-0175de41a46b.jpg)
![Uploading 20180527_182431[1].jpg…]()

**Comment by DenBerry** [comment]
QuliyevaB Please try link again. (http://192.255.51.93/Azerbaijan)

**Comment by sheagraffo** [comment]
If link is working, please close this ticket.
