### ISSUE TITLE
Brucellosis search results not displayed.

### ISSUE THREAD

**Issue by Chavez34** [EIDSS/EIDSS7#30]
**Summary**
Brucellosis search results did not display only samples under "Disease" with Brucellosis.

**To Reproduce**
1. Log in as troymcclure
2. Go to  Steps below
3. Click on Laboratory >Samples

Step 1. Select laboratory sample displays only samples with disease that contains Brucellosis.
![image](https://user-images.githubusercontent.com/52667706/60893258-9c8a1080-a22e-11e9-8312-374210e5697a.png)
Step 2. Type Brucellosis into the search bar.
![image](https://user-images.githubusercontent.com/52667706/60893382-d4915380-a22e-11e9-8856-1a05379a392c.png)
Step 3. Should display results that are only Brucellosis - no results found.
![image](https://user-images.githubusercontent.com/52667706/60893588-2934ce80-a22f-11e9-9808-67ade167c8fb.png)

**Expected behavior**
Display results showing only Brucellosis 
Screenshots**
Above.

**Additional details:**
 - Build: 80
 - Script title Lab 07, Assign a test to a sample

**Issue severity**
Severity: Major

**Additional context**
N/A

**Comment by aatmns** [comment]
7/12/2019, Anatoliy
Defect replicated.
![301](https://user-images.githubusercontent.com/32458032/61156714-0f5eea00-a4c2-11e9-8a90-98f47a165de4.PNG)
