### ISSUE TITLE
ADMIN: You can't add an employee to a user group via the employee role and permissions tab. (Admin Bug 008)

### ISSUE THREAD

**Issue by NatalieShapiro** [EIDSS/EIDSS7#300]
**Summary**
You can add an employee to a user group via admin > security > user groups. However, you can't add a user group when looking up an employee via organization > employees> search and then editing that person's permission/role. You get a prompt "The record with Table Aaron NCDC already exists." **THIS BUG CAN REPLACE ADMIN BUG 003** #282. 

**Details**
Script ID (or enter ad hoc if ad hoc): ADM02, Administration
Username: NCDCAdmin
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to organization > employees > search for an employee (Aaron Table) > try to add "Non-Passive Surveillance Users" as a user group. 

**Expected behavior**
Expect to be able to add a user group via the employees tab as well as user group tab.

**Screenshots**

**Additional context**

**Comment by aatmns** [comment]
Unable to reproduce to defect stated.
Created user group.
Assigned permissions
Selected three icons and a grid.
Save user group record.
Created new User
Added new user group to the user's record.
Save the user.
Logged as a user.
Three selected icons were displayed.
Grid was missing
Opened Human AS campaign in edit mode
Opened Human aggregate record in edit mode.

![300-1](https://user-images.githubusercontent.com/32458032/170089680-832da021-11f4-4be9-9d94-ba92d21781f9.png)


![300-2](https://user-images.githubusercontent.com/32458032/170088985-50b9ec70-06f0-46e0-b843-98bc91d56550.png)
-4e2a-b0c8-a5f1da8d4efb.png)

![300-3](https://user-images.githubusercontent.com/32458032/170089010-5585d1ef-4be1-422e-b3b3-093b3101c672.png)

![300-4](https://user-images.githubusercontent.com/32458032/170089081-259f61b5-b8a5-4506-a0fe-b7435797fe71.png)

![300-5](https://user-images.githubusercontent.com/32458032/170089099-829c2043-47d4-4a30-ba93-e1ec88ba454b.png)

![300-5](https://user-images.githubusercontent.com/32458032/170089512-626af26b-1362-46db-b2ba-086326803a7f.png)


![300-6](https://user-images.githubusercontent.com/32458032/170089111-94c127ca-0753-44a1-abe4-4312aa322722.png)

![300-7](https://user-images.githubusercontent.com/32458032/170089124-3233a2af-6eff-4da4-93df-b68bc10a520b.png)

![300-8](https://user-images.githubusercontent.com/32458032/170089144-0d77355d-6cd9-4a1d-be6a-0a08da2ee84d.png)

![300-9](https://user-images.githubusercontent.com/32458032/170089158-d92b61d9-d42f-4c3d-9e85-56dd0b0415bc.png)

![300-10](https://user-images.githubusercontent.com/32458032/170089168-79116c97-79fa-4b03-a175-2059de154b69.png)

![300-11](https://user-images.githubusercontent.com/32458032/170089181-68b3e134-278a-455d-bda2-05704f89dc79.png)

**Comment by NatalieShapiro** [comment]
Confirmed workflow with Jaya - this bug is no longer an issue.
