### ISSUE TITLE
VPS14 - No able to print the report list 

### ISSUE THREAD

**Issue by AnnaSwiatecka** [EIDSS/EIDSS7#303]
**Summary**
No able to report the list of reports.

**Details**
Script ID (or enter ad hoc if ad hoc):VPS14
Username: 
Severity (optional): M

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to Avian Disease Report List for your farm
2. Click on Print

**Expected behavior**
Printing of the list of reports

**Screenshots**

**Additional context**

**Comment by aatmns** [comment]
Defect is confirmed. Print feature is not yet ready:
![303-1](https://user-images.githubusercontent.com/32458032/170101188-d8f10bd4-87a5-4b36-9566-b5e60ee5f81d.png)

**Comment by jkkannan** [comment]
Verified; planned for one of next two builds.
