### ISSUE TITLE
VPS17 - Unable to print Avian disease report

### ISSUE THREAD

**Issue by AnnaSwiatecka** [EIDSS/EIDSS7#308]
**Summary**
 Unable to print Avian disease report

**Details**
Script ID (or enter ad hoc if ad hoc): VPS17
Username: Keda Rayon Vo
Severity (optional): Medium

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to Report Review
2. Scroll down - no print button

**Expected behavior**
Print button on the bottom of the page does not exists

**Screenshots**

**Additional context**

**Comment by easleyte** [comment]
Close:  "VPS17 Script Veterinary Passive Surveillance/De-duplicate existing two Avian Disease records within the same farm" worked as scripted:  successful in de-duplicating two avian disease report records.
