### ISSUE TITLE
VPS19 - Able to edit most of the fields of the report as a Chief Epizootiologist

### ISSUE THREAD

**Issue by AnnaSwiatecka** [EIDSS/EIDSS7#309]
**Summary**
Able to edit and change most of the fields as a Chief Epizootiologist

**Details**
Script ID (or enter ad hoc if ad hoc):VPS19
Username: ADJARA RVO
Severity (optional): Severe

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to Avian Disease report
2. Click on details of the report - only Report Status Field should be active 

**Expected behavior**
only Report Status Field should be active - most of the fields were active

**Screenshots**

**Additional context**

**Comment by jkkannan** [comment]
Test against CLOSED LDR/ADR--select fields remain editable including farm/flock/species grid.
