### ISSUE TITLE
Human Active--The system unable to show data entry box for 'planed number'

### ISSUE THREAD

**Issue by shahina77** [EIDSS/EIDSS7#31]
**Summary**
The system unable to show data entry box for 'planed number' and unable to perform the reaming steps of the script
**To Reproduce**
1. Log in as 
2. Go to 
3. Click on 

**Expected behavior**
The system should show all data entry fields  and should all entered data and submit button
[HPS 01`.zip](https://github.com/EIDSS/EIDSS7/files/3373344/HPS.01.zip)
. 

Screenshots**

**Additional details:**
 - Build: 80
 - Script title (enter ad hoc if not script-based): HAS01

**Issue severity**
Severity (critical, major, minor, low):
Critical
**Additional context**

**Comment by EBH2001** [comment]
Not reproducible in Integration build 83.4

**PLEASE SEE ATTACHMENT
[HAS01_GitHub#31_Human Active Surveillance Campaign_NotReproducible.docx](https://github.com/EIDSS/EIDSS7/files/3401821/HAS01_GitHub.31_Human.Active.Surveillance.Campaign_NotReproducible.docx)
**

**Comment by jkkannan** [comment]
Closed during GAT remediation.
