### ISSUE TITLE
ADMIN: Requiring "Date of Notification" under Interface Editor did not require this field in the human disease report. (Admin Bug 011)

### ISSUE THREAD

**Issue by NatalieShapiro** [EIDSS/EIDSS7#311]
**Summary**
I required "Date of Notification" under Interface Editor (Human) per ADM18 and when I went to create a new disease report, it didn't require this field to submit.

**Details**
Script ID (or enter ad hoc if ad hoc): Script, ADM18 Administration 
Username: NCDCAdmin
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Check Interface Editor (Human Notification > Date of Notification to ensure it's required) 2. Create a human disease record and see if date of notification is required 

**Expected behavior**
I expected the disease record to ensure that I entered date of notification (red asterisk was also not there). 

**Screenshots**

**Additional context**

**Comment by jkkannan** [comment]
Verified in GAT; changes in LDR are reflected in application and changes in IE are retained so problem is with HDR

**Comment by NatalieShapiro** [comment]
Fixed. Closing out.
