### ISSUE TITLE
HAR03: Unable to print human disease report from review page 

### ISSUE THREAD

**Issue by shahina77** [EIDSS/EIDSS7#314]
**Summary**
HAR03: Unable to print human disease report from review page 

**Details**
HAR03 (or enter ad hoc if ad hoc):
Username: VaniDistrictEpi
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jkkannan** [comment]
Verified; planned in next build.
