### ISSUE TITLE
VPS22 - report saved as Confirmed (Disease Classification) but in the list of reports is still suspected

### ISSUE THREAD

**Issue by AnnaSwiatecka** [EIDSS/EIDSS7#315]
**Summary**
report saved as Confirmed (Disease Classification) but in the list of reports (search) is still suspected

**Details**
Script ID (or enter ad hoc if ad hoc): VPS22
Username: GURIA RVO
Severity (optional): medium

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to Disease Report Case Classification and check in the classification in Search results 
2. Case classification should be the same

**Expected behavior**
The same case slassification

**Screenshots**
Screenshots saved on DTRA 7

**Additional context**

**Comment by mkornegay** [comment]
Resolved with changeset 7938 and will be included in release 7.0.267.x
