### ISSUE TITLE
VPS21 and other required interpretation of avian and livestock disease - unable to interpret the disease reports

### ISSUE THREAD

**Issue by AnnaSwiatecka** [EIDSS/EIDSS7#316]
**Summary**
unable to interpret the disease reports

**Details**
Script ID (or enter ad hoc if ad hoc): VPS21 
Username: Adjara and Keda District Vet
Severity (optional): severe

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to disease report and use interpretation of data options
2. Informed that we are not able to do that

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by aatmns** [comment]
Defect is confirmed.
![image](https://user-images.githubusercontent.com/32458032/170304669-1ceee411-cae8-4d95-bf9d-93444571731b.png)
