### ISSUE TITLE
VPS24 Print not ready yeat

### ISSUE THREAD

**Issue by AnnaSwiatecka** [EIDSS/EIDSS7#317]
**Summary**
Not able to print results list from searching

**Details**
Script ID (or enter ad hoc if ad hoc): VPS24
Username: Keda Rayon
Severity (optional): m

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by aatmns** [comment]
Defect is confirmed in the GAT environment.

**Comment by mvb00** [comment]
What Search Page are yo utrying to print?

**Comment by easleyte** [comment]
Close:  Confirmed site alerts were displayed, the system displayed the correct list of records, and I was able to print the list
