### ISSUE TITLE
ADMIN: Cannot upload .csv file to statistical data, error states that one of the lines has an error and it will not let me continue. (Admin Bug 013)

### ISSUE THREAD

**Issue by NatalieShapiro** [EIDSS/EIDSS7#318]
**Summary**
I went through this bug with someone in the room. For ADM22, when I try to upload the .csv file on my computer and press "load", it says "Line 1, Column 16 invalid statistical type." Supposedly it's supposed to allow for ten errors in data (but displays them for awareness) but there is only one error and it prevents me from uploading the document. I cannot press "save." 

**Details**
Script ID (or enter ad hoc if ad hoc): ADM22
Username: NCDCAdmin
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to Admin > Statistical Data> Enter Dates 1/1/2021 - 12/31/2021 (per script) > Upload CVS file from computer > Press Load Data > Save after error pop-up

**Expected behavior**
I expected to be able to load the data.

**Screenshots**

**Additional context**

**Comment by jkkannan** [comment]
Retest with no errors to see if any upload is possible.  This may impact severity.

**Comment by NatalieShapiro** [comment]
Closed during iGAT.

**Comment by NatalieShapiro** [comment]
Closed during iGAT.
