### ISSUE TITLE
VPS25 (and previous scripts (291 connected)Unable to delete the Livestock Disease report

### ISSUE THREAD

**Issue by AnnaSwiatecka** [EIDSS/EIDSS7#319]
**Summary**
Unable to delete the Livestock Disease report Error :Unable to delete this record as it contains child object

**Details**
Script ID (or enter ad hoc if ad hoc): VPS25
Username: ADJARA RVO
Severity (optional): S

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to disease report review 
2. Click on detele

**Expected behavior**
Not able to delete the report

**Screenshots**

**Additional context**

**Comment by jkkannan** [comment]
Tester to retest using LDR with minimum data to see if reproducible.

**Comment by AnnaSwiatecka** [comment]
Able to delete "simple report" without any additional data.  reports with data included - unable to delete (include child object)

**Comment by AnnaSwiatecka** [comment]
Able to delete report without samples/herd info in External enviornment
