### ISSUE TITLE
ADM05 - Create new settlement 

### ISSUE THREAD

**Issue by Aj-Kakar** [EIDSS/EIDSS7#32]
**Summary**
After entering the settlement information, the system asks users to click on review to review the entered data but the review button doesn't work. The system does not proceed to the review screen. 

I manually selected review from the right hand navigation to proceed forward. After reviewing the information I was asked to submit the information where I got an error submitting the settlement entry. 

**To Reproduce**
1. Log in as rykermase
2. Go to Settlement under administration
3. Fill in the settlement information
4. Manually select review
5. Submit the settlement record 

**Expected behavior**

System should allow users to review information and submit their entry.

Screenshots**
![unable to add settlement](https://user-images.githubusercontent.com/52667376/60894817-70bc5a00-a231-11e9-94a2-38a5e98991e0.PNG)

**Issue severity**
Minor

**Build**
79

**Comment by christhompson17** [comment]
This is actually 2 bugs:
1. The issue with the "next" button and having to click on "Review" form the nav menu is a known issue.
2. The error is a Major bug as opposed to critical as the record did still save.

**Comment by EBH2001** [comment]
Not reproducible in Integration build 83.4

**PLEASE SEE ATTACHMENT
[ADM05_GitHub#32_Add_New_Settlement_NotReproducible.docx](https://github.com/EIDSS/EIDSS7/files/3401699/ADM05_GitHub.32_Add_New_Settlement_NotReproducible.docx)
**
