### ISSUE TITLE
ADMIN: Site alerts not showing up for changes in reference tables. (Admin Bug 014)

### ISSUE THREAD

**Issue by NatalieShapiro** [EIDSS/EIDSS7#320]
**Summary**
After doing ADM23, I did not receive any site alerts in my notification portal. 

**Details**
Script ID (or enter ad hoc if ad hoc): ADM23
Username: NCDCAdmin
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Make changes to Reference Tables then check site alerts 

**Expected behavior**
Per business rules, I was told I should receive site alerts for any reference table modifications - even if I'm making the modifications myself. 

**Screenshots**

**Additional context**

**Comment by aatmns** [comment]
Defect confirmed. No site alert was displayed for modifying reference tables.

**Comment by NatalieShapiro** [comment]
Closed.
