### ISSUE TITLE
VPS27 - Unable to save the report 

### ISSUE THREAD

**Issue by AnnaSwiatecka** [EIDSS/EIDSS7#321]
**Summary**
Unable to save the report (saving not completed)

**Details**
Script ID (or enter ad hoc if ad hoc): VPS27
Username: Adjara Rvo
Severity (optional): M

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to Disease report Livestock
2. Click on save

**Expected behavior**
Report saved

**Screenshots**

**Additional context**

**Comment by aatmns** [comment]
Unable to reproduce the stated defect. Able to save two livestock disease reports.
Defect. The Deduplication sub-menu is missing "Livestock Report" sub-menu.

**Comment by jkkannan** [comment]
Tester to retest to see if reproducible
