### ISSUE TITLE
HAR09: Able to find an existing Weekly Reporting Form records after deleting the report as a chief epidemiologist 

### ISSUE THREAD

**Issue by shahina77** [EIDSS/EIDSS7#322]
**Summary**
Able to find/see an existing Weekly Reporting Form records after deleting the report as a chief epidemiologist 

**Details**
Script ID (or enter ad hoc if ad hoc): HAR09
Username: NCDCEpi
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… login NCDCEpi
2. Click on… Select Human >Weekly Reporting Form for searching an existing WRF >Open the WRF in the view mode > select delete > Confirm delete > Return dashboard > search the WRF by reporting ID > WRF is existed  

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by EBH2001** [comment]
Not reproducible in PreGAT, build 267.21.  After deletion and returned back to Weekly Form search page, I cleared all fields and search by the Report ID.  No results were returned.
![image](https://user-images.githubusercontent.com/16134915/170329347-37e227e7-73d3-41bb-a17c-64e5a45a57e7.png)

**Comment by aatmns** [comment]
The system correctly deleted a Weekly Reporting Form record in GAT.

**Comment by jkkannan** [comment]
Tester to reproduce

**Comment by shahina77** [comment]
The system correctly deleted a Weekly Reporting Form record in GAT retesting but the remnant of the report does appear in the search results.
