### ISSUE TITLE
VPS28 - no print button on the Disease Report Summary (Livestock)

### ISSUE THREAD

**Issue by AnnaSwiatecka** [EIDSS/EIDSS7#323]
**Summary**
no print button on the Disease Report Summary

**Details**
Script ID (or enter ad hoc if ad hoc): VPS28
Username: Keda rayon
Severity (optional): m

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to Disease Report Summary, scroll down
2. Click on… No print sign

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by aatmns** [comment]
Defect is confirmed in the GAT environment.

**Comment by easleyte** [comment]
Closed:  successfully printed Disease Report record with all data displayed
