### ISSUE TITLE
Lab11 Step11- reject sample to be destroyed

### ISSUE THREAD

**Issue by CarolChapman1** [EIDSS/EIDSS7#324]
**Summary**
Under approvals tab-Checked sample (Kahlo Frida) for destruction-hit reject-save-ok - sample still in approvals list as marked for routine destruction- Adjara lab director

**Details**
Script ID (or enter ad hoc if ad hoc):Lab11
Username: 
Severity (optional):C

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by aatmns** [comment]
Defect was observed during the testing.
Defect is confirmed:
![image](https://user-images.githubusercontent.com/32458032/170356386-45c020ca-d900-4fc4-820f-ea8831200ef4.png)
