### ISSUE TITLE
LAB11 Verification-test status

### ISSUE THREAD

**Issue by CarolChapman1** [EIDSS/EIDSS7#326]
**Summary**
Script calls for accepting and rejecting tests and samples- end verification indicates that testing -test status should state "Final" for approved samples, and "deleted" for deleted samples- and test   status should indicate "deleted"  for test records- testing tab does not have records

**Details**
Script ID (or enter ad hoc if ad hoc):
Username: 
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jkkannan** [comment]
You update a sample to approve its deletion but the sample does not reflect that. Check screenshots.

**Comment by RyanLloyd1** [comment]
Issue persists

**Comment by RyanLloyd1** [comment]
Varied outcomes - approved test results can either (1) Move/Update in Testing tab to final (2) Move to My Favorites tab as final (3) Disappear from all tabs

**Comment by RyanLloyd1** [comment]
Closed.
