### ISSUE TITLE
HAR12: Site alert is not displayed for the newly created human ILI aggregate form record

### ISSUE THREAD

**Issue by shahina77** [EIDSS/EIDSS7#330]
**Summary**
Site alert is not displayed for the newly created human ILI aggregate form record

**Details**
Script ID (or enter ad hoc if ad hoc): HAR12
Username: LINCHKHUTDISTRICTEPI
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… Return dashboard > click site alert 
2. Click on… 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by EBH2001** [comment]
Reproducible in PreGAT, build 267.21
![image](https://user-images.githubusercontent.com/16134915/170329787-2003f452-119d-4446-93c9-575fcbe6a22c.png)
![image](https://user-images.githubusercontent.com/16134915/170329838-02b4c6b4-caca-44c0-a0ce-b5af3242f903.png)
