### ISSUE TITLE
Admin_User Guide_en_ADM_EDT_Use_Parameter_Type_2022v2 - The Add button is not showing on the Parameter Type details pop-up

### ISSUE THREAD

**Issue by karlasomera** [EIDSS/EIDSS7#332]
**Summary**
The Add button does not show up on Step two on page 2 from the user guide.  Unable to complete remaining steps.

**Details**
Script ID (or enter ad hoc if ad hoc):
Username: karlasomera
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to…Configuration then parameter type Menu Editor  
2. Click on… select one of the elipses and it should take you to the Parameter Type details3. Then an ADD button should appear on the fixed Present Values.  Unable to complete the remaining steps until the add button is added.

**Expected behavior**
TO have the add button to complete the type window for the Fixed Present Values

**Screenshots**
Screen shot located on my computer under Pics label “Karla Screen shots” under the name Add Button…..”
**Additional context**

**Comment by EBH2001** [comment]
Not reproducible in PreGAT, build 267.21
[image](https://user-images.githubusercontent.com/16134915/170328244-45f69d0e-5aa3-4042-ba72-53db05e288a9.png)

**Comment by karlasomera** [comment]
Close this ticket.  Recommend the User Guide to include the extra step to Identify the Parameter type (Reference/Fixed Preset Values) for the add button to appear.
