### ISSUE TITLE
HAR14: Unable to find an existing human ILI aggregated form record as a chief epidemiologist 

### ISSUE THREAD

**Issue by shahina77** [EIDSS/EIDSS7#333]
**Summary**
Searching by the Form ID of an existing an existing human ILI aggregated form record - search result shows no entries 

**Details**
Script ID (or enter ad hoc if ad hoc): HAR14
Username: NCDCEpi
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… Login to EIDSS under chief epidemiologist
2. Click on… Select human > ILI Aggregate Form> search by Form ID 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jkkannan** [comment]
Unable to reproduce in preGAT or GAT.

**Comment by jkkannan** [comment]
Walk-through tomorrow with tester

**Comment by shahina77** [comment]
Able to find an existing form by adjusting search time frame -

**Comment by shahina77** [comment]
Issue has been resolved
