### ISSUE TITLE
VAS13 - Unable to delete the Veterinary Active Surveillance session

### ISSUE THREAD

**Issue by AnnaSwiatecka** [EIDSS/EIDSS7#340]
**Summary**
Unable to delete the Veterinary Active Surveillance session

**Details**
Script ID (or enter ad hoc if ad hoc): VAS13
Username: Guria RVO
Severity (optional): m

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to Surveillance Session and delete
2. Click on delete

**Expected behavior**
Deleted record;

**Screenshots**

**Additional context**

**Comment by EBH2001** [comment]
Reproducible in PreGAT.  After clicking delete it just stays on the details page
![image](https://user-images.githubusercontent.com/16134915/170367610-eedd8007-6bb2-4fd8-9258-f8489b48b75f.png)
![image](https://user-images.githubusercontent.com/16134915/170367701-4f80b191-b682-4296-b11e-4f12cd2831f1.png)

**Comment by AnnaSwiatecka** [comment]
Unable to delete the session "contains child object"

**Comment by NatalieShapiro** [comment]
Closed. This script worked.
