### ISSUE TITLE
ADMIN: Changing user permissions in the systems functions does not work. (Admin Bug 016)

### ISSUE THREAD

**Issue by NatalieShapiro** [EIDSS/EIDSS7#341]
**Summary**
I tried to take away permissions for Aaron Table (persons list), however it did not work. Look at steps to reproduce below. This bug was verified. 

**Details**
Script ID (or enter ad hoc if ad hoc): ADM25 Administration
Username: NCDC Admin
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Under NCDCAdmin, check that Aaron Table does not have permissions to access the persons list (under Admin > Security > System Functions > Persons List > look up name). Then log into "atable01" (password: EIDSStesting2022!) and see if you can access the persons list. 

**Expected behavior**
I expected to not see the persons list when logged in as atable01. 

**Screenshots**

**Additional context**

**Comment by karlasomera** [comment]
Recommend closing this bug.  All verification steps were met.
