### ISSUE TITLE
ADMIN: Label for default region and rayon is "Administrative Level 1" and "Administrative Level 2" under NCDCAdmin. (Admin Bug 017)

### ISSUE THREAD

**Issue by NatalieShapiro** [EIDSS/EIDSS7#345]
**Summary**
Labels should say default region/rayon - Jaya confirmed. Additionally, user preferences should be considered in script since that's another location that can control this feature?  

**Details**
Script ID (or enter ad hoc if ad hoc): ADM27, Administration
Username: NCDCAdmin
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to Administration > System Preferences and look at the labels for those two fields 

**Expected behavior**
I expected to see "default region in search panels" and not "default administrative level 1 in search panels" 

**Screenshots**

**Additional context**

**Comment by aatmns** [comment]
The issues is resolved.
System Preferences page has correct labels:
![image](https://user-images.githubusercontent.com/32458032/183940317-8cb2a3ea-61f4-4d54-9140-d62a6a224cc6.png)

**Comment by karlasomera** [comment]
After running this script, I am able to see the label to be Region and Rayon.  Recommend closing this bug.
