### ISSUE TITLE
VAS15 - After saving the Active Surveillance session and coming back to this session, the species type is not saved

### ISSUE THREAD

**Issue by AnnaSwiatecka** [EIDSS/EIDSS7#347]
**Summary**
After saving the Active Surveillance session and coming back to this session, the species type is not saved

**Details**
Script ID (or enter ad hoc if ad hoc): VAS15
Username: Keda Rayon
Severity (optional): m

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to Create Veterinary Active Surveillance session
2. Save the session and use :"Return to Active Surveillance Session" button

**Expected behavior**
All the data should be saved 

**Screenshots**

**Additional context**

**Comment by aatmns** [comment]
The issue is resolved.
Prior to the saving:
![image](https://user-images.githubusercontent.com/32458032/183975408-0ad5e097-97c2-4c70-8af9-c69e61d6c0e7.png)


After saving the record:
![image](https://user-images.githubusercontent.com/32458032/183975379-72cc5160-a651-4799-b652-f5419bdf8e62.png)

**Comment by aatmns** [comment]
The issue is resolved.
Records are retained.
![image](https://user-images.githubusercontent.com/32458032/184003729-30026f39-7272-489d-8e30-f47832ab10de.png)

**Comment by easleyte** [comment]
Close:  Script worked as written:
