### ISSUE TITLE
HAS04: Did not generate human active surveillance session ID for a newly created session

### ISSUE THREAD

**Issue by shahina77** [EIDSS/EIDSS7#348]
**Summary**
Did not generate human active surveillance session ID for a newly created session

**Details**
Script ID (or enter ad hoc if ad hoc): HAS04
Username: Kedadistrictepi
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… Login under epi > select huamn > AS session> click add> entered data for session and saved > return to AS session 
2. Click on… 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by EBH2001** [comment]
Not reproducible in PreGAT (NOTE:  I selected an existing Person record as the "Add" new Person does not work)
![image](https://user-images.githubusercontent.com/16134915/170364735-951a6ea9-8380-43a1-a413-fc4f60bcd708.png)
