### ISSUE TITLE
Facility Details

### ISSUE THREAD

**Issue by srbatni** [EIDSS/EIDSS7#35]
**Summary**
The facility patient first sought care in facility details tab only listed 4 choices.

**To Reproduce**
1. Log in as: Russell Peters 
2. Go to: Human Disease Report
3. Click on: Facility Details

**Expected behavior**
Expected Gurjaani District Polyclinic to be a drop down selection under Facility patient first sought care.

Screenshots**

**Additional details:**
 - Build: v7 79.0
 - Script title (enter ad hoc if not script-based): HSP 03

**Issue severity**
Severity (critical, major, minor, low): Minor

**Additional context**

**Comment by christhompson17** [comment]
DB team needs to confirm if this data exists in the GAT DB. If it does not, this is not a bug, and is a GAT data issue or a script issue.
