### ISSUE TITLE
VAS16 - Session created under campaign doesn't show up under the campaign

### ISSUE THREAD

**Issue by AnnaSwiatecka** [EIDSS/EIDSS7#350]
**Summary**
Session created under campaign doesn't show up under the campaign

**Details**
Script ID (or enter ad hoc if ad hoc): VAS16
Username: Adjara Rvo
Severity (optional): M

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to Campaign page 
2. Look for sessions lists

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by easleyte** [comment]
Closed:  Successful at creating and linking a surveillance session within a campaign record
