### ISSUE TITLE
ADMIN_HUM Active Surveillance Session_User Guide Unable to delete

### ISSUE THREAD

**Issue by karlasomera** [EIDSS/EIDSS7#355]
**Summary**
Unable to delete a Human Active Surveillance Session

**Details**
Script ID (or enter ad hoc if ad hoc):
Username: KarlaSomera
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… Human then Active surveillance session then search a session to delete
2. Click on… select a session ID.  Once selected the session information page is displayed.  Go to the navigation on right hand side select the review tab then scroll to the bottom of the page and  the delete button is not showing up.  

**Expected behavior**
User to be able to delete session

**Screenshots**

**Additional context**

**Comment by EBH2001** [comment]
Reproducible in PreGAT, build 267.21.  Permissions are set correctly for Chief Epidemiologist
![image](https://user-images.githubusercontent.com/16134915/170369730-79823e9d-538a-4c72-95d9-16bb94b0a242.png)
![image](https://user-images.githubusercontent.com/16134915/170369947-d2d2106a-38d8-452d-9d19-2f137bebd8a3.png)

**Comment by karlasomera** [comment]
Able to follow the user guide to delete the human Active Surveillance Session.  This issue has been tested on both environments (The external/GAT).  Defect is closed.
