### ISSUE TITLE
VPS08 - After de-duplication of Avian farm both farms are missing

### ISSUE THREAD

**Issue by AnnaSwiatecka** [EIDSS/EIDSS7#357]
**Summary**
After de-duplication of Avian farm both farms are missing
**Details**
Script ID (or enter ad hoc if ad hoc):
Username: Keda Rayon
Severity (optional): S

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to Administration and farm deduplication
2. Click on deduplicate

**Expected behavior**
One farm should be retained

**Screenshots**

**Additional context**

**Comment by jkkannan** [comment]
Tester to retry tomorrow
