### ISSUE TITLE
Re-test of VPS25 - retesting successful (issue with deleting of report); new issue identified with the report; unable to open the Livestock report from the farm information window

### ISSUE THREAD

**Issue by AnnaSwiatecka** [EIDSS/EIDSS7#359]
**Summary**
 unable to open the Livestock report from the farm information window

**Details**
Script ID (or enter ad hoc if ad hoc): VPS25
Username: Adjara Rvo 
Severity (optional): M

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to Farm Information
2. Click on Disease report link or edit button 

**Expected behavior**
The disease report should open 

**Screenshots**

**Additional context**

**Comment by aatmns** [comment]
Ability to view or edit Livestock Disease reports is not functioning in the Farm record.
However, ability to view or edit Livestock Disease reports are operating from the Livestock Search Results grid.

**Comment by easleyte** [comment]
Close:  all worked as expected
