### ISSUE TITLE
The system failed to display the human active surveillance campaign in edit format and unable to perform the remaining steps of the script. 

### ISSUE THREAD

**Issue by shahina77** [EIDSS/EIDSS7#36]
**Summary**
The system failed to display the human active surveillance campaign in edit format and unable to perform the remaining steps of the script.  

**To Reproduce**
1. Log in as 
2. Go to 
3. Click on 

**Expected behavior**
The system should display the human active surveillance campaign in edit format. 
[HAS02.zip](https://github.com/EIDSS/EIDSS7/files/3373400/HAS02.zip)

Screenshots**

**Additional details:**
 - Build: 80
 - Script title (enter ad hoc if not script-based):

**Issue severity**
Severity (critical, major, minor, low):
Critical
**Additional context**
HAS02

**Comment by christhompson17** [comment]
QA has confirmed that this is a permission issue, other EIDSS users are able to see the form in edit mode.
