### ISSUE TITLE
ADMIN: In Flexible Form Designer, adding a new parameter record under a "successor" record is not reflected in Human Disease Report.  (Admin Bug 

### ISSUE THREAD

**Issue by NatalieShapiro** [EIDSS/EIDSS7#360]
**Summary**
While following ADM37, I created a successor record (copied Rabies template) and retitled it "Test Illness That Causes Crying." I added Rabies as a determinant and a new parameter "Crying." When I switched to the epi account and created a Human Disease Report, but "crying" did not come up as a a clinical sign. **However**, adding "crying" to an existing template (HCS 0-5 Children Mortality GG) showed up under clinical signs. This bug is related to creating copies of templates and then adding parameters. 

**Details**
Script ID (or enter ad hoc if ad hoc): ADM37, Administration
Username: NCDCAdmin, NCDCEpi
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):

**For Successor Record:**
1. As NCDCAdmin, check parameters for "Test Illness That Causes Crying" under Flexible Form Designer to ensure "crying" is listed and "rabies" is a determinant.  
2. Log into NCDCEpi, then create a human disease report, select "rabies" as a disease, move onto the human clinical signs section and see that "crying" is not listed as an option

**For Existing Record (this works):**
1. As NCDCAdmin, check parameters for "HCS 0-5 Children Mortality GG" under Flexible Form Designer to ensure "crying" is listed as the last field in the form. 
2. Log into NCDCEpi, then create a human disease report, select "0-5 Children Mortality" as the disease, move onto the human clinical signs section and see that "crying is listed as an option"

**Expected behavior**
When creating a Human Disease Report under NCDCEpi and selecting "Rabies" as the disease, I expected to see "crying" as an option for a clinical sign. 

**Screenshots**

**Additional context**

**Comment by aatmns** [comment]
Issue is confirmed within the Flexible Form Designer.
The updated Template is not displayed in the Human Disease Report.

**Comment by NatalieShapiro** [comment]
I just tried this again with a "successor/copy" record - HCS 0-5 Children Mortality GG (copy) and added purple fingers for yellow fever and it worked?

**Comment by jkkannan** [comment]
Retest 2 Aug

**Comment by NatalieShapiro** [comment]
![Determinant Bug](https://user-images.githubusercontent.com/105503558/182387390-7ee73efa-e8f8-4af9-a1d0-cd3ef810efe9.PNG)

**Comment by NatalieShapiro** [comment]
![Error Copying Template in GAT Internal](https://user-images.githubusercontent.com/105503558/182387448-2f978ca9-5b98-4ba2-8b5c-c3c6df6f910e.PNG)

**Comment by karlasomera** [comment]
Recommend updating the script to show that the Template/Parameter has a determinate in order to show under disease in the Human person report.  Script ADM37 has passed all verification steps and Bug can be closed in GitHub. Also recommend to provide what process the team is taking to include the updates to the scripts.
