### ISSUE TITLE
ADM-Create an Aliquot or Derivative - User Guide en_LAB_SMP_CreateAliquot_2022

### ISSUE THREAD

**Issue by karlasomera** [EIDSS/EIDSS7#361]
**Summary**
When creating aliquots/Derivatives  go to the carrot on each aliquot/derivative and the store levels of the freezer appears.  When selecting a physical location the system allows for different samples to be added to the same location.    User guide Step 6 Page 2 through step 14.  

**Details**
Script ID (or enter ad hoc if ad hoc):
Username: KarlaSomera
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… Laboratory and  select samples.  Then select a sample to create aliquot/derivatives
2. Click on… in the same page go to the carrot to maximize and add the sample to a location where the selection does not remain orange or show the unavailable location (Step 12) 

**Expected behavior**
The Freezer selection should show the orange selection for other aliquots/derivative samples to avoid adding two different samples in one location.  

**Screenshots**
Screenshots are available on computer under GAT folder -> Screenshots that represent each step taken.  
**Additional context**

**Comment by aatmns** [comment]
The Create Aliquot Quick User guide has a correct workflow presented in creating aliquots and derivatives.

**Comment by karlasomera** [comment]
This issue is not ready to be closed.  The aliquot /Derivatives are still not working correctly.  User is able to save sample aliquot/derivatives to the same location .  Screen shots are saved in my computer for your reference.

**Comment by karlasomera** [comment]
This major bug has been retested on external and GAT environments.  Able to assign a location in the freezer once.  The symbols on the assigned location was validated.  This Major bug can be closed with a recommendation on the freezer views.  Recommend adding the letters on the left hand side and numbers on top to be consistent of both views.  I have attached the pictures for your reference.  I will close this ticket this afternoon after the group discussion.  

![Capture 2_freezer_KPS](https://user-images.githubusercontent.com/104407068/182409368-4fd8aa02-148e-4883-9e1a-3f43fa9a7fc1.PNG)
![Capture 1_Freezer_KPS](https://user-images.githubusercontent.com/104407068/182409386-94039955-557d-4728-b188-5e0d657e44a1.PNG)

**Comment by karlasomera** [comment]
Added new bug for the recommendation of keeping consistent  labeling.  See bug number 441
