### ISSUE TITLE
Outbreak Management: Modifications to flexible form outbreak parameters are not reflected when entering a new case. (Outbreak Bug 001)

### ISSUE THREAD

**Issue by NatalieShapiro** [EIDSS/EIDSS7#362]
**Summary**
When following OMM02, the modifications I made to the flexible form outbreak parameters did not work. Specifically, I added "Test Parameter 1" and "Test Parameter 2." I also deleted "Comments." When I followed the steps to enter a new outbreak, these change in parameters were not reflected under "Outbreak Investigation." 

**Details**
Script ID (or enter ad hoc if ad hoc): OMM02, Outbreak Management
Username: GuriaRegionalVet **Note that the script says "Chief Epidemiologist" but I tried both Chief Epi and Chief Epizootologist 
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Check flexible form for "Outbreak Livestock Case CM" to ensure that the parameter modifications are displayed ("Test Parameter 1, Test Parameter 2)2. 
2. Go to outbreak "OUTTBTBZ220027" and create a new case. Look under "Outbreak Investigation" tab to see that the changes aren't reflected. 

**Expected behavior**
I expected to see the flexible form modifications when entering a new case. 

**Screenshots**

**Additional context**

**Comment by aatmns** [comment]
Issue is confirmed in preGAT.

**Comment by NatalieShapiro** [comment]
In both external and GAT environment, I can't click on the outbreak parameters icon. Therefore, I can't validate this script.

**Comment by jkkannan** [comment]
Recommend walk-through 2 Aug.

**Comment by NatalieShapiro** [comment]
Verified that this is closed.
