### ISSUE TITLE
ADM- User Guide En_LAB_SMP_Enter_2022 - Farm name disappears when sample is saved 

### ISSUE THREAD

**Issue by karlasomera** [EIDSS/EIDSS7#363]
**Summary**
When adding a Sample to the Lab module the name of a farm is not populating.

**Details**
Script ID (or enter ad hoc if ad hoc):
Username: karlasomera
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… Laboratory then Samples.  Select register New Sample and add all require fields of Sample.  Add sample and screen refreshes displaying the new Sample in bold letters.  Then click save to save the record

**Expected behavior**
For the Farm name to populate on the sample grid.

**Screenshots**

**Additional context**
The farm name is removed when the user saves the record

**Comment by aatmns** [comment]
The Enter Sample Quick Guide has a correct workflow of entering new sample records.

**Comment by karlasomera** [comment]
Close ticket.
