### ISSUE TITLE
OMM05 - unable to edit Case location data (street, house, building, etc.) in Outbreak Summary

### ISSUE THREAD

**Issue by AnnaSwiatecka** [EIDSS/EIDSS7#368]
**Summary**
Unable to edit/enter Case location data (street, house, building, etc.) in Outbreak Summary. WIndows are no active.

**Details**
Script ID (or enter ad hoc if ad hoc): OMM05
Username: KEDA Rayon VO
Severity (optional): M

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to Outbreak Summary/Case location
2. Click on Street/House/Building/Apt

**Expected behavior**
Able to enter the data 

**Screenshots**

**Additional context**

**Comment by aatmns** [comment]
Issue is confirmed in preGAT.
