### ISSUE TITLE
OMM05 - Unable to add animals in Outbreak Summary Farm/Herd Species 

### ISSUE THREAD

**Issue by AnnaSwiatecka** [EIDSS/EIDSS7#369]
**Summary**
Unable to add animals in Outbreak Summary Farm/Herd Species; unable to add any other data in the case report

**Details**
Script ID (or enter ad hoc if ad hoc): OMM05
Username: Keda Rayon Vo
Severity (optional): S

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to Outbreak summary/Farm/Herd/Soecies
2. Click on Plus

**Expected behavior**
Should be able to add the animals 

**Screenshots**

**Additional context**

**Comment by aatmns** [comment]
Issue cannot be reproduced in preGAT.
Able to enter Livestock species for the Livestock Outbreak Case:
![370-1](https://user-images.githubusercontent.com/32458032/170542767-be024a1a-c298-44e1-89c1-71addfab55d0.png)
