### ISSUE TITLE
Hospital Name

### ISSUE THREAD

**Issue by srbatni** [EIDSS/EIDSS7#37]
**Summary**
Telavi District Hospital was not listed as drop down choice under hospital name in facility details tab.
**To Reproduce**
1. Log in as Russell Peters
2. Go to: Human Disease Report
3. Click on: Facility Details

**Expected behavior**
Telavi District Hospital should be one of the drop down name choices in Hospital Name.

Screenshots**

**Additional details:**
 - Build: v7 79.0
 - Script title (enter ad hoc if not script-based): HSP03

**Issue severity**
Severity (critical, major, minor, low): Minor

**Additional context**

**Comment by christhompson17** [comment]
Likely missing GAT data, however data team should confirm if the data already resides in the DB to determine if this is a bug or a GAT data issue.
