### ISSUE TITLE
OMM05 - No alert and green check mark in the table on the left side even when required fields don't have data

### ISSUE THREAD

**Issue by AnnaSwiatecka** [EIDSS/EIDSS7#371]
**Summary**
No alert and green check mark in the table on the left side even when required fields don't have data

**Details**
Script ID (or enter ad hoc if ad hoc): oMM05
Username:  Keda Ryon
Severity (optional): M

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to Outbreak Summary/Outbreak Investigation
2. Click on next

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by aatmns** [comment]
Unable to reproduce in the preGAT.
Veterinary case was created and saved in the Outbreak Session.
![image](https://user-images.githubusercontent.com/32458032/170544006-672ab97d-26e2-45bd-92a3-6397bda180d8.png)

Farm ID is retained:
![image](https://user-images.githubusercontent.com/32458032/170544208-10561934-2e06-4dc9-823b-c770ce7654b9.png)
