### ISSUE TITLE
ADMIN User Guide_en_VEC_VDD_Enter_2022.PDF - Missing add button

### ISSUE THREAD

**Issue by karlasomera** [EIDSS/EIDSS7#372]
**Summary**
A clear and concise description of the issue.
The Add button is not populating to add a vector Surveillance Session

**Details**
Script ID (or enter ad hoc if ad hoc):
Username: karlasomera
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… Vector then click on surveillance Session
2. Click on… unable to click on the add button as stated on the User guide

**Expected behavior**
Click on add to crate a blank Vector Surveillance Session screen.

**Screenshots**
Screenshot located in the GAT folder under screenshots

**Additional context**

**Comment by jkkannan** [comment]
Review user guide vs documentation as to workflow.

**Comment by karlasomera** [comment]
Retested this issue on both (External/GAT) environments and found no additional concerns.  Recommend looking at the user guide to reflect the right visuals.
