### ISSUE TITLE
OMM08 - Unable to update existing case; multiple issues observed

### ISSUE THREAD

**Issue by AnnaSwiatecka** [EIDSS/EIDSS7#375]
**Summary**
 Unable to update existing case; unable to edit any data using existing and previously saved cases and not being able to modify any data ,received the error that data is missing in all the sections in the window when required fields are empty, the system marked them as completed (green), received the error that data is missing in all the sections

**Details**
Script ID (or enter ad hoc if ad hoc): oMM08
Username: Adjara RVO
Severity (optional): S

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to existing outbreak case
2. Click on edit button

**Expected behavior**
Should be able to edit/update the Outbreak summary

**Screenshots**

**Additional context**

**Comment by aatmns** [comment]
Unable to reproduce in preGAT.
Opened an existing veterinary outbreak case. Modified:
Notification, Farm info, Clinical Info, Vaccinations, Case Monitoring, Contacts, Samples, Lab Tests. 
Saved the record.
![375-11](https://user-images.githubusercontent.com/32458032/170552521-3d3e37c6-2c0e-42af-bbb4-f88ebcf8852f.png)
Updates retained.
![375-12](https://user-images.githubusercontent.com/32458032/170552539-8d4b1a4e-c748-4c20-9f34-440c35c71f51.png)

![375-21](https://user-images.githubusercontent.com/32458032/170552570-624bdc42-6e96-443e-b12d-fcee0c3ed2ba.png)
![375-31](https://user-images.githubusercontent.com/32458032/170552585-51a9eb76-b389-4d80-8662-b20582613757.png)
![375-41](https://user-images.githubusercontent.com/32458032/170552596-8100806f-fd2c-4f3d-b2ba-43b96e380939.png)
![375-51](https://user-images.githubusercontent.com/32458032/170552614-7ec68dcb-cfad-41f9-80cb-0d56b5060d40.png)
![375-51](https://user-images.githubusercontent.com/32458032/170552627-7c0227b2-e9d2-459b-9fe9-cd197d6f8e78.png)
![375-52](https://user-images.githubusercontent.com/32458032/170552648-6e059837-a0a5-4133-ad94-7210de3e80fe.png)
![375-61](https://user-images.githubusercontent.com/32458032/170552661-503f5652-40bb-4d81-b9cf-f4ebd46592f7.png)
![375-62](https://user-images.githubusercontent.com/32458032/170552674-0ea872b9-c540-451d-82ad-269e533dafca.png)
![375-71](https://user-images.githubusercontent.com/32458032/170552688-d47aadb1-87fa-4b8c-afef-ac17b9066c47.png)
![375-72](https://user-images.githubusercontent.com/32458032/170552700-08e3e6c4-b57b-453c-a5ba-a061376a959a.png)
![375-8](https://user-images.githubusercontent.com/32458032/170552709-3607a7c2-d7af-4625-bae9-9da3a2f43103.png)

**Comment by aatmns** [comment]
Observed defect in GAT environment.

**Comment by AnnaSwiatecka** [comment]
Re-tested and was able to complete the script - no issue
