### ISSUE TITLE
OMM12 - Unable to convert an existing case with contact

### ISSUE THREAD

**Issue by AnnaSwiatecka** [EIDSS/EIDSS7#376]
**Summary**
Unable to update an existing case with contact

**Details**
Script ID (or enter ad hoc if ad hoc): OMM12
Username: Adjara Rvo
Severity (optional): M

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to existing case
2. Click on contact

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by aatmns** [comment]
Unable to reproduce in preGAT.
Opened an existing veterinary outbreak case. Modified:
Notification, Farm info, Clinical Info, Vaccinations, Case Monitoring, Contacts, Samples, Lab Tests.
Saved the record.
For details see screenshots from #375.

**Comment by AnnaSwiatecka** [comment]
Successful in external environment.

**Comment by AnnaSwiatecka** [comment]
Successful in GAT enviornment.
