### ISSUE TITLE
VAR02 - Unable to search for any existing Aggregate Reporting 

### ISSUE THREAD

**Issue by AnnaSwiatecka** [EIDSS/EIDSS7#378]
**Summary**
Unable to search for any existing Aggregate Reporting 

**Details**
Script ID (or enter ad hoc if ad hoc): VAR02
Username: Keda
Severity (optional): S

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to Aggregate Report
2. Click on Search

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by aatmns** [comment]
Unable to replicate search issues in preGAT:
![image](https://user-images.githubusercontent.com/32458032/170554650-ed510193-49c5-4d12-959e-2abc4cd60f5b.png)

**Comment by aatmns** [comment]
Defect is confirmed in the GAT environment.
