### ISSUE TITLE
VAS09 - Unable to modify Existing Vet Active Surveillance Session - no able to add herd and sample

### ISSUE THREAD

**Issue by AnnaSwiatecka** [EIDSS/EIDSS7#379]
**Summary**
Unable to modify Existing Vet Active Surveillance Session - no able to add herd and samples

**Details**
Script ID (or enter ad hoc if ad hoc): VAS09
Username: Keda
Severity (optional): M

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to Veterinary Active Surveillance Sessions
2. Click on existing session and update the data; Add farm; Add herd

**Expected behavior**
Should be able to add the herd and samples

**Screenshots**

**Additional context**

**Comment by aatmns** [comment]
Issue is replicated in preGAT.

**Comment by aatmns** [comment]
Issue is confirmed in preGAT. Unable to add any additional species to a herd.
