### ISSUE TITLE
Samples were not displayed in order to select for deletion

### ISSUE THREAD

**Issue by Chavez34** [EIDSS/EIDSS7#38]
**Summary**

Samples were not displayed in order to select for deletion

**To Reproduce**
1. Log in as mollyrue
2. Go to Select Laboratory > Testing

To Reproduce:
Step 1. Select Laboratory>Testing
Step 2 Testing tab of the laboratory manual displayed.
Step 3. Samples selected for testing
Step 4. No results were displayed
![image](https://user-images.githubusercontent.com/52667706/60895519-d230f880-a232-11e9-8c6d-f24f8acb8515.png)

**Expected behavior**
The system should display the lab sample IDs selected for deletion.

Samples were not displayed in order to select for deletion

Screenshots**

Above

**Additional details:**
 - Build: 80
 - Script title: Lab08, Mark a Test for Deletion

**Issue severity**
Severity Major

**Additional context**
N/A

**Comment by aatmns** [comment]
7/12/2019, Anatoliy
Defect replicated.
![381](https://user-images.githubusercontent.com/32458032/61157622-a6c53c80-a4c4-11e9-861d-f88ab2b99602.PNG)
