### ISSUE TITLE
VAS10 - Veterinary Active Surveillance - Livestock - able to add herd, unable to add samples

### ISSUE THREAD

**Issue by AnnaSwiatecka** [EIDSS/EIDSS7#380]
**Summary**
Veterinary Active Surveillance - Livestock - able to add herd, unable to add samples

**Details**
Script ID (or enter ad hoc if ad hoc): VAS10
Username: Adjara rvo
Severity (optional): M

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to Session - Detailed Information - Add herd - Add samples (switched from Epizootiologist to Chief Epizootiologist)
2. Click on Add samples; unable add species to the Species field

**Expected behavior**
Should be able to add samples

**Screenshots**

**Additional context**

**Comment by aatmns** [comment]
Unable to replicate in the preGAT environment.
Able to add samples from a farm in the Vet Active Surveillance Session:
![image](https://user-images.githubusercontent.com/32458032/170556349-4b174877-f3a0-4642-9dd5-b6c6794129f5.png)

**Comment by AnnaSwiatecka** [comment]
Able to add sample
