### ISSUE TITLE
Lab01 Poor condition print barcode

### ISSUE THREAD

**Issue by CarolChapman1** [EIDSS/EIDSS7#381]
**Summary**
Tried to accession sample in poor condition and print barcode from Accession tab- froze 3 times

**Details**
Script ID (or enter ad hoc if ad hoc):LAB01
Username: Adjaratech
Severity (optional): M

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by RyanLloyd1** [comment]
Issue resolved
