### ISSUE TITLE
OMM02 - unable to create the outbreak after searching - Add button not active

### ISSUE THREAD

**Issue by AnnaSwiatecka** [EIDSS/EIDSS7#387]
**Summary**
OMM02 - unable to create the outbreak after searching - Add button not active

**Details**
Script ID (or enter ad hoc if ad hoc): OMMO2
Username: Adjara RVO
Severity (optional): M

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to Search Outbreak- search
2. Click on Add

**Expected behavior**
Should be able to create the outbreak

**Screenshots**

**Additional context**

**Comment by jkkannan** [comment]
Severity: recommended minor by tester; need to reproduce

**Comment by AnnaSwiatecka** [comment]
Retesting in both environment successfully completed
