### ISSUE TITLE
AD Hoc

### ISSUE THREAD

**Issue by CarolChapman1** [EIDSS/EIDSS7#388]
**Summary**
Accessioned sample as reject- got pop-up that indicated a note was needed to reject- opened sample status comment from icon. I was able to enter a comment, but the system froze- I could not save or cancel- because a comment is mandatory, I could not save the accession

**Details**
Script ID (or enter ad hoc if ad hoc):
Username: Adjarahumantech
Severity (optional):major

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jkkannan** [comment]
Recommended severity of critical.  Pending investigation

**Comment by RyanLloyd1** [comment]
Resolved. Close issue.
