### ISSUE TITLE
Sample Detail--sent to organization

### ISSUE THREAD

**Issue by srbatni** [EIDSS/EIDSS7#39]
**Summary**
The Sent to Organization list does not contain a list of laboratories only. Simply states NCDC

**To Reproduce**
1. Log in as: Russell Peters
2. Go to: Human Disease Report 
3. Click on: Samples 

**Expected behavior**
The note in the testing plan states that the Sent to Organization Field should contain a list of laboratories only. However, this only states NCDC

Screenshots**
![image](https://user-images.githubusercontent.com/52708365/60896830-def62200-a21b-11e9-893c-e3fc7fee7081.png)

**Additional details:**
 - Build: v7 79.0
 - Script title (enter ad hoc if not script-based): HSP03

**Issue severity**
Severity (critical, major, minor, low): Low

**Additional context**

**Comment by christhompson17** [comment]
The Data team needs to confirm if this data is in the DB or if this is a missing GAT data issue.
