### ISSUE TITLE
VAR05 - Veterinary Aggregate Report - not saving

### ISSUE THREAD

**Issue by AnnaSwiatecka** [EIDSS/EIDSS7#390]
**Summary**
Veterinary Aggregate Action Report - not saving

**Details**
Script ID (or enter ad hoc if ad hoc):VAR05
Username: Keda Rayon
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to Report Review
2. Click on Save

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by AnnaSwiatecka** [comment]
Still data was not save in external and Gat environment

**Comment by jkkannan** [comment]
Discrepancy between environments--partial save in GAT, completely not saving in matrix in External.  Not yet verified.
