### ISSUE TITLE
Ad Hoc Lab-testing tab

### ISSUE THREAD

**Issue by CarolChapman1** [EIDSS/EIDSS7#391]
**Summary**
Tried to edit test status from both drop down menu and edit screen. visibly updated, but switched back to original status when Save was hit

**Details**
Script ID (or enter ad hoc if ad hoc):
Username: 
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jkkannan** [comment]
Tester was editing test status from Preliminary to In Progress from the grid and from the edit menu.  Saw issue in both cases. 
Recommended severity of major pending investigation.

**Comment by RyanLloyd1** [comment]
Closed.
