### ISSUE TITLE
ADM04: Under employee creation, "Personal ID Type" should be listed as a required field and field does not save when selected. (iGAT Admin Bug 01) 

### ISSUE THREAD

**Issue by NatalieShapiro** [EIDSS/EIDSS7#398]
**Summary**
Personal ID has a red asterisk and is a required field. However, Personal ID Type should also have a red asterisk since they are related. Originally, I thought this was just a bug with a required field. However, when I select the Personal ID Type and save the employee details, the Personal ID type doesn't save. This is causing issues when adding a secondary site to an existing employee record + trying to deactivate secondary sites.

**Same issues below in both GAT + External environment.**

(1) New Employee Record + Adding Secondary Site: Tried creating a new employee record and adding a secondary site. When adding another site, it deleted the primary site and I had re-add the secondary site (minor new bug #406 ). Then when I tried to deactivate a site, I ran into an error with the personal ID type (personal ID is invalid).

(2) Existing Employee Record + Adding a Secondary Site: I tried adding a secondary site to an existing employee record and encountered the same personal ID error above "personal ID field is invalid."

**Details**
Script ID (or enter ad hoc if ad hoc): ADM04
Username: NCDCAdmin
Severity (optional): TBD

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Admin > Employee > Add 
2. **FOR REQUIRED FIELD BUG**: Try to submit a record with a personal ID but leave personal ID type blank. You will get an error and it won't let you save. (2) Then select the personal ID type, save. **FOR SECONDARY SITE BUGS**: (1) New Employee Record + Adding Secondary Site: Tried creating a new employee record and adding a secondary site. When adding another site, it deleted the primary site and I had re-add the secondary site (minor new bug #406 ). Then when I tried to deactivate a site, I ran into an error with the personal ID type (personal ID is invalid). (2) Existing Employee Record + Adding a Secondary Site: I tried adding a secondary site to an existing employee record and encountered the same personal ID error above "personal ID field is invalid."

**Expected behavior**
I expect "Personal ID Type" to have a red asterisk and for the selection to save. I expect the "Personal ID Type" to save. I expect to be able to add a secondary site to the employee. I expect to be able to deactivate a secondary site.

**Screenshots**

**Additional context**

**Comment by NatalieShapiro** [comment]
This issue also prevents the testing of ADM06.

**Comment by jkkannan** [comment]
Able to reproduce.
