### ISSUE TITLE
VAR01 (Wareagle) - red checkmark by Report Details with all data entered

### ISSUE THREAD

**Issue by AnnaSwiatecka** [EIDSS/EIDSS7#399]
**Summary**
After searching of the created report with all the required data entered, a red checkmark was present on the right side of the screen by the section "Report details". I doesn't affect data entered or next steps.

**Details**
Script ID (or enter ad hoc if ad hoc): VAR01 (Wareagle)
Username: kedadistrictvet
Severity (optional): minor

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jkkannan** [comment]
Tester reported this also occurs in GAT.

**Comment by AnnaSwiatecka** [comment]
Successfully retested.
