### ISSUE TITLE
VAR01 (Wareagle) - three columns in Vet Aggregate Case are not active

### ISSUE THREAD

**Issue by AnnaSwiatecka** [EIDSS/EIDSS7#400]
**Summary**
In Disease Matrix Section three last columns (Animals sick/Disinfection and Notes are not active)

**Details**
Script ID (or enter ad hoc if ad hoc): VAr01
Username: Kedadistrict Vet
Severity (optional):Major

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jkkannan** [comment]
Verified in External.
