### ISSUE TITLE
VAR10 - Vet Agg Action Summary Report - not able to print (PeratonDev and GAT)

### ISSUE THREAD

**Issue by AnnaSwiatecka** [EIDSS/EIDSS7#405]
**Summary**
Not able to print Vet Agg Action report 

**Details**
Script ID (or enter ad hoc if ad hoc): VAR10  (peratonDev)
Username: GuriaRegionalvet
Severity (optional): Major

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by easleyte** [comment]
Close:  Script VAR10 (405) Veterinary Aggregate Reporting/Create Veterinary Aggregate Action Summary Record worked as scripted:  Successful in creating and printing a Veterinary Aggregate Action Report Summary record.
