### ISSUE TITLE
ADM04: Adding a secondary site to a new employee removes the original organization (iGAT Bug 02).

### ISSUE THREAD

**Issue by NatalieShapiro** [EIDSS/EIDSS7#406]
**Summary**
When creating a new employee with two sites, the original organization entered disappears and has to be re-entered. 

**Details**
Script ID (or enter ad hoc if ad hoc): ADM04
Username: NCDCAdmin
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Admin > Employee >Add 2. Create employee with NCDC as the org 3. Add an additional site under user groups and permissions. *Notice NCDC disappears and has to be re-entered. 
**Expected behavior**
I expect NCDC to remain under organizations since I did not remove it and it was the original organization.

**Screenshots**

**Additional context**

**Comment by karlasomera** [comment]
Recommend closing this bug....  The system was able to deactivate the second Org and it remained in the Users account.  T
