### ISSUE TITLE
LAB14: My Favorite - Register New Sample - Patient/Farm Search locks up application

### ISSUE THREAD

**Issue by RyanLloyd1** [EIDSS/EIDSS7#407]
**Summary**
When registering a new sample under My Favorites and attempting to select patient/farm using search the application seems to lock up and you need to refresh to be able to do anything again.

**Details**
Script ID (or enter ad hoc if ad hoc): LAB14
Username: ImeretiHumanZDLTech
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to My Favorites
2. Click on Register New Sample
3. Attempt to use Search function to add Patient/Farm name

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by RyanLloyd1** [comment]
Additionally the pop-up frame when hitting "+" quickly disappears

**Comment by jkkannan** [comment]
Unable to reproduce in External environment. May require walk-through.

**Comment by RyanLloyd1** [comment]
Cannot reproduce either issue now in either environment
