### ISSUE TITLE
OMM11: Unable to save imported cases into an existing outbreak  

### ISSUE THREAD

**Issue by shahina77** [EIDSS/EIDSS7#409]
**Summary**
Save button is not working

**Details**
OMM11
Username: 
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**
Imported case should saved  

**Screenshots**

**Additional context**

**Comment by jkkannan** [comment]
Tester to review this and previously entered bug--one is for create and one is for import.
