### ISSUE TITLE
Case Investigation: Details

### ISSUE THREAD

**Issue by srbatni** [EIDSS/EIDSS7#41]
**Summary**
Latitude and Longitude fields were not prepopulated as noted.

**To Reproduce**
1. Log in as: Russell Peters Epidemiologist
2. Go to: Human Disease Report
3. Click on: Case Investigation: Details

**Expected behavior**
GAT testing script notes that latitude and longitude should be prepopulated if the region, rayon, and settlement were noted. However, this information was not prepopulated.

Screenshots**

**Additional details:**
 - Build: v7 79.0
 - Script title (enter ad hoc if not script-based): HPS03

**Issue severity**
Severity (critical, major, minor, low): Minor

**Additional context**

**Comment by christhompson17** [comment]
Data team needs to confirm if this data is in the DB, or if this is a GAT data issue.
