### ISSUE TITLE
VAS09 (GAT-5G) - after adding the, in the tests list, in the column "test results", test name is displayed

### ISSUE THREAD

**Issue by AnnaSwiatecka** [EIDSS/EIDSS7#410]
**Summary**
after adding the test in the column "test results", test name is displayed; also in the Test Results Details page there is no Test Result listed; in addition Test Status indicated that test didn't start 

**Details**
Script ID (or enter ad hoc if ad hoc):VAS09
Username: KedaDistrictVet
Severity (optional): major

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jkkannan** [comment]
Able to reproduce in Auto 2.

![image](https://user-images.githubusercontent.com/35157698/182215475-f3e0b672-ae05-423e-98f7-3d9bf7202284.png)

**Comment by AnnaSwiatecka** [comment]
Retested - fixed
