### ISSUE TITLE
OMM11: Duplicated the female contacts after adding the case contact 

### ISSUE THREAD

**Issue by shahina77** [EIDSS/EIDSS7#411]
**Summary**
Duplicated case contacts after adding the case contacts, male case is not duplicated  

**Details**
OMM11
Username: NCDCEpi 
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by aatmns** [comment]
No duplicated contact records displayed in the Human Outbreak Case withing Outbreak Session OUTTBTBZ220009.
![image](https://user-images.githubusercontent.com/32458032/182609015-ccaf9ada-755e-44e2-8e96-1e0dc5dd9208.png)

Added a third contact:
![image](https://user-images.githubusercontent.com/32458032/182609260-90dee9d8-b9a5-46e1-a318-699e6178a20b.png)

Saved the Human Outbreak Case:
![image](https://user-images.githubusercontent.com/32458032/182609360-337514f5-d9ff-4769-b31c-48fd68e9c6cf.png)

Returned to the Contacts:
Three records are displayed as intended:
![image](https://user-images.githubusercontent.com/32458032/182609527-4ddbb628-3cd7-4073-a63e-c487201c27ee.png)
