### ISSUE TITLE
VAS10 - While working on Test Result Details "Rule in/Rule Out window), the screen become frozen and requires refresh of page (data is lost after refresh)

### ISSUE THREAD

**Issue by AnnaSwiatecka** [EIDSS/EIDSS7#413]
**Summary**
While working on Test Result Details "Rule in/Rule Out window), the screen become frozen and requires refresh of page (data is lost after refresh) - tried twice (frozen twice)

**Details**
Script ID (or enter ad hoc if ad hoc): VASS10
Username: Guria RVO
Severity (optional): minor

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jkkannan** [comment]
Walk-through on 2 August.

**Comment by AnnaSwiatecka** [comment]
tested and was able to Rule-in Rule-out the test with no issue !
