### ISSUE TITLE
Person record is not saved

### ISSUE THREAD

**Issue by shahina77** [EIDSS/EIDSS7#414]
**Summary**
HPS01 - person record is not saved- save button was loading but did not saved the person record

**Details**
HPS01
Username: 
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jkkannan** [comment]
Walk-through planned for 2 August.

**Comment by shahina77** [comment]
Was able to recreate in both environments
