### ISSUE TITLE
VPS07 Adding Avian Report to the farm and alert is showing up that "the record will be lost if I leave the page"

### ISSUE THREAD

**Issue by AnnaSwiatecka** [EIDSS/EIDSS7#417]
**Summary**
Adding Avian Report to the farm and alert is showing up that "the record will be lost if I leave the page" after saving data (data not changed after the saving)

**Details**
Environment: (GAT or External): GAT
Script ID (or enter ad hoc if ad hoc): VPS07
Username: Guria RVO
Severity (optional): minor (data is saved)

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by easleyte** [comment]
VPS07, #417:  Delete an Existing Veterinary Farm Record with Disease Reports.  Worked as scripted....unable to delete a farm record with a disease report.

Strange Message....what does "child objects" mean?

![Screenshot (11)](https://user-images.githubusercontent.com/111596877/193121204-27a0a0ae-9ae8-43d9-a99a-0fdc8a97b47f.png)
