### ISSUE TITLE
LAB04: Search function - hitting enter doesn't execute search

### ISSUE THREAD

**Issue by RyanLloyd1** [EIDSS/EIDSS7#418]
**Summary**
Performing simple search - hitting enter doesn't execute the search but prompt below search field states that the results are present. Search function works fine when you click the magnifying glass.

**Details**
Environment: (GAT or External): External
Script ID (or enter ad hoc if ad hoc): LAB04
Username: Adjara Tech
Severity (optional): Low/Minor

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to Laboratory > Samples 
2. Click in simple search field and enter "anthrax"
3. Hit Enter

**Expected behavior**
Hitting enter after populating search field executes search and displays search results

**Screenshots**

**Additional context**

**Comment by RyanLloyd1** [comment]
![LAB04 Search](https://user-images.githubusercontent.com/110361057/182384952-da1c889b-db2e-4371-9c68-36ff879b1dc5.PNG)

**Comment by jkkannan** [comment]
Changed from bug to enhancement; enter is not required to start search (only magnifying glass) but could be confusing to users.

**Comment by aatmns** [comment]
Selecting "enter" key on a keyboard initiates a search in the simple search text box.
Not considered for a software change request.

**Comment by herashchenkoa** [comment]
The issue has been addressed and verified in EIDSS Release v7.0.427. The bug is closed.
