### ISSUE TITLE
LAB04: Sample Test Result Final and Dated but no Test Started Date entered

### ISSUE THREAD

**Issue by RyanLloyd1** [EIDSS/EIDSS7#419]
**Summary**
When looking at a testing record, the sample test result is labeled as final and there is a result date but there is no Test Started Date entered

**Details**
Environment: (GAT or External): External 
Script ID (or enter ad hoc if ad hoc): LAB04
Username:  Adjara Tech
Severity (optional): Minor

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to Laboratory > Testing
2. Click on Lab Sample ID SAD070220221
3. Look at Test Details > Test Result, Test Status, Result Date / Test Started Date

**Expected behavior**
Application should not allow a Test Result to be entered without a Test Started Date

**Screenshots**
![image](https://user-images.githubusercontent.com/110361057/182389091-613247b3-4340-4a49-8ef6-c2ec3e66fd3e.png)

**Additional context**

**Comment by jkkannan** [comment]
Approved and implemented.
