### ISSUE TITLE
LAB Ad-Hoc: Tabs don't consistently display proper number of items

### ISSUE THREAD

**Issue by RyanLloyd1** [EIDSS/EIDSS7#421]
**Summary**
Laboratory tabs occasionally show incorrect number of items

**Details**
Environment: (GAT or External): External
Script ID (or enter ad hoc if ad hoc): ad hoc
Username: Adjara and Imereti Tech
Severity (optional): Minor

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to Laboratory and click one of the tabs (Sample, Testing, etc.) 
2. Verify that the number listed in the tab is equivalent to the number of items in the given area

**Expected behavior**
Tabs should show correct number of items.

**Screenshots**
![image](https://user-images.githubusercontent.com/110361057/182392501-6a799e07-3ca2-409f-8667-b26869712ae3.png)
![image](https://user-images.githubusercontent.com/110361057/182417343-83f06bae-faa9-409d-8eb3-d4c564e45851.png)

**Additional context**

**Comment by jkkannan** [comment]
For review tomorrow; believe this is behaving as expected per requirements (i.e. samples # = not accessioned)

**Comment by RyanLloyd1** [comment]
Confirmed that tabs display numbers for items with pending actions. Recommend making pending action items default to beginning of the list (it does for Unaccessioned Samples but not for In Progress Testing).
