### ISSUE TITLE
LAB04: Testing items not showing without using search

### ISSUE THREAD

**Issue by RyanLloyd1** [EIDSS/EIDSS7#422]
**Summary**
Items in testing tab disappeared after viewing a testing record. Logged out and logged back and items still not showing. Can use search function to display items.

**Details**
Environment: (GAT or External): External
Script ID (or enter ad hoc if ad hoc): LAB04
Username: Adjara Tech
Severity (optional): Minor/Major

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to Laboratory > Testing
2. View number of items within tab
3. Perform search for "Positive" to display that there are items that should be showing

**Expected behavior**
Items that have moved to Testing should appear within tab without needing to perform a search

**Screenshots**
![image](https://user-images.githubusercontent.com/110361057/182394472-857bed33-b189-411b-a3f9-3d7ec1809cd6.png)
![image](https://user-images.githubusercontent.com/110361057/182394737-d42e02f7-9566-456d-9eec-467c4ec71ae8.png)

**Additional context**
They were showing initially, this may be difficult to replicate but it persists even when logging out and logging back in to Adjara Tech.

**Comment by jkkannan** [comment]
Tester to retest and attempt to reproduce tomorrow.

**Comment by RyanLloyd1** [comment]
Cannot replicate, potentially a server/PC issue during testing. Closed.
