### ISSUE TITLE
ADM16: Site alerts not working when making changes to matrices (iGAT Bug 03)

### ISSUE THREAD

**Issue by NatalieShapiro** [EIDSS/EIDSS7#423]
**Summary**
During ADM16, I made changes to a matrix (copied, changed name, added and deleted records) but I did not receive any site alerts. 

**Details**
Environment: (GAT or External):  External
Script ID (or enter ad hoc if ad hoc): ADM16
Username: NCDCAdmin
Severity (optional): Minor

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Execute ADM16 and verify on step 10 that you don't receive any site alerts. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by NatalieShapiro** [comment]
Site reports also didn't show up when creating a human disease report for HPS02 (external environment).

**Comment by karlasomera** [comment]
For this Bug The alert is showing when making changes to the Matrix.  So I would agree that this bug can be closed out.  In addition a new bug was encountered while running this script.  Will create a new bug for the team to work on.

**Comment by karlasomera** [comment]
See new bug ticket 456 if additional information is needed
