### ISSUE TITLE
HPS02: Screen froze + unable to save test details in a human disease report.

### ISSUE THREAD

**Issue by NatalieShapiro** [EIDSS/EIDSS7#425]
**Summary**
I went to enter details about the tests under a human disease report and after filling out all mandatory fields, the screen froze.

**Details**
Environment: (GAT or External): External
Script ID (or enter ad hoc if ad hoc): HPS02, Step 13
Username: NCDCEpi + NCDCAdmin
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Create a human disease report and enter test details and try to save. Fill out all mandatory fields. 

**Expected behavior**
I expected to be able to save the test details.

**Screenshots**

**Additional context**

**Comment by aatmns** [comment]
Unable to reproduce issue as stated in the same environment (external) with the same user (NCDCepi).

Steps:
1 Selected any Person record- Jason Borne.
2 Added a disease report to this Person.
3 Defined required fields.
![hps02-1](https://user-images.githubusercontent.com/32458032/182410448-70c29797-6b69-4c90-9ac5-04aced32f171.png)

4 Added a sample:
![hps02-2](https://user-images.githubusercontent.com/32458032/182411026-7016250a-b904-473c-a943-2d6fe3c03de0.png)

5 Sample record is saved:
![hps02-3](https://user-images.githubusercontent.com/32458032/182411198-823e7ebe-e15a-492e-ac67-5e52fa4ffa98.png)

Added a test record:
![hps02-4](https://user-images.githubusercontent.com/32458032/182411253-0d25a614-7494-433e-970b-4c2ba7086036.png)

Test record is saved:
![hps02-5](https://user-images.githubusercontent.com/32458032/182411276-b3956813-7fab-4dba-ac51-53e6b9ef6401.png)

Saved the Human Disease Report:
![hps02-6](https://user-images.githubusercontent.com/32458032/182411495-a41cc17c-dbe2-4e39-9cc7-b184e3c1a570.png)
