### ISSUE TITLE
LAB05: Test Assignments not all saving

### ISSUE THREAD

**Issue by RyanLloyd1** [EIDSS/EIDSS7#427]
**Summary**
When trying to save multiple test assignments simultaneously, all do not save.

**Details**
Environment: (GAT or External): External
Script ID (or enter ad hoc if ad hoc): LAB05
Username: Adjara
Severity (optional): Minor/Major

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to Laboratory>Samples and assign multiple tests to sample
2. Click on Testing tab to save tests and observe which ones saved

**Expected behavior**
All assigned tests should save.

**Screenshots**
![LAB05 Sample Test Add 1](https://user-images.githubusercontent.com/110361057/182414842-10db4219-7d2f-4b5a-a3a4-1029ec0876dc.PNG)
![LAB05 Sample Test Add 2](https://user-images.githubusercontent.com/110361057/182414861-4080c703-ae7f-4195-97bf-3343220158f4.PNG)

**Additional context**
The number of tests that save seems to vary, first attempt I tried to save 3 tests for the same sample and only one saved. Second attempt, I tried to save 2 tests each for 2 different samples and only the two tests for one of the samples saved.

**Comment by jkkannan** [comment]
For reinvestigation with tester on 3 Aug.

**Comment by RyanLloyd1** [comment]
Confirmed the only assigned tests that show are for samples that are accessioned within the last 14 days. Issue closed as end users can decide on date range requirement, if any, and tests are being saved as expected.
