### ISSUE TITLE
HAS03: Unable to enter data for sample details for an active surveillance session to be added to an active surveillance campaign

### ISSUE THREAD

**Issue by shahina77** [EIDSS/EIDSS7#429]
**Summary**
Unable to enter data for sample details for an active surveillance session to be added to an active surveillance campaign 

**Details**
 External and internal 
Script HAS03
Username: NCDCEPI
Severity (optional): 

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… human >active surveillance campaign>add button >Entered session information (Region, Ryan, and session start date)>click add to include sample details> unable to proceed 
2. Click on… 

**Expected behavior**
Sample details data can be entered 

**Screenshots**

**Additional context**

**Comment by jkkannan** [comment]
Reproducible.
