### ISSUE TITLE
Case Investigation

### ISSUE THREAD

**Issue by srbatni** [EIDSS/EIDSS7#43]
**Summary**
Case investigation details was prepopulated with the wrong rayon.

**To Reproduce**
1. Log in as: Russell Peters, Epidemiologist
2. Go to: Human Disease Report
3. Click on: Case Investigation: Details 

**Expected behavior**
The Rayon field should not have been prepopulated and it was prepopulated with the wrong region.

Screenshots**

**Additional details:**
 - Build: v7 79.0
 - Script title (enter ad hoc if not script-based): HPS03

**Issue severity**
Severity (critical, major, minor, low): Low

**Additional context**

**Comment by jkkannan** [comment]
Need  to verify if true defect or script issue.  Region and rayon should be blank per script but were prepopulated and rayon had to be changed to the correct values in script.
