### ISSUE TITLE
REP34 Reports Module - Unable to Run an Archive Report

### ISSUE THREAD

**Issue by karlasomera** [EIDSS/EIDSS7#430]
**Summary**
Unable to run a report with the archived data when selected.  I was able to run this report on the GAT environment.  

**Details**
Environment: (GAT or External): This issue occurs in the external environment
Script ID (or enter ad hoc if ad hoc): REP34 Reports Module
Username: NCDCEPI
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… Reports then Human reports then Monthly Morbidity and Mortality reports
2. Click on… Define a subset of achieve data and run report
3. See screenshot attached that is received when running the report.

**Expected behavior**
To receive a report with Archive information.  

**Screenshots**
See screenshot added for your reference
![Capture4_REP34 Report Module_KPS](https://user-images.githubusercontent.com/104407068/182451125-ec84b54b-5707-40a2-be1c-c86c787e9b94.PNG)

**Additional context**

**Comment by karlasomera** [comment]
Added a better capture of the error received.  

![Capture4_REP34 Report Module_KPS](https://user-images.githubusercontent.com/104407068/182451759-a9b5fe96-d2d6-446b-99e1-58bee5a6b9df.PNG)

**Comment by aatmns** [comment]
The issue is resolved.

**Comment by karlasomera** [comment]
Ran the script to create a use Archive report and system produced the report  for Human Monthly Morbidity and Mortality.  Recommend to close bug.
