### ISSUE TITLE
VPS14 and 17 - unable to save data in Farm Epi Information in Avian Disease Report

### ISSUE THREAD

**Issue by AnnaSwiatecka** [EIDSS/EIDSS7#432]
**Summary**
unable to save data in Farm Epi Information in Avian and Livestock Disease Report (in addition in livestock: control measures were not saved); in external environment "Saving" function was not working properly

**Details**
Environment: (GAT or External): GAT and External
Script ID (or enter ad hoc if ad hoc): VPS14/17
Username: Keda Rayon 
Severity (optional): major

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to Farm/Add Avian/steps of disease report including Farm Epi information
2. Go to review and Save and Return to Disease Report or Return to Dashboard

**Expected behavior**

**Screenshots**
Screenshots (pre and post on DTRA4)

**Additional context**

**Comment by jkkannan** [comment]
Related/secondary bug for investigation (may be due to data not saving to DB as prereq)--when printing LDR/ADR, data that was entered in system was not reflected in PDF for printing.

**Comment by easleyte** [comment]
Close:  Script VPS 14 "Search for Avian Disease Report Records" worked as scripted:  successful in finding and printing Disease Report Records.
