### ISSUE TITLE
VAR04: Disease Report search columns list Region twice rather than Region / Rayon

### ISSUE THREAD

**Issue by RyanLloyd1** [EIDSS/EIDSS7#433]
**Summary**
When performing a Veterinary Aggregate Disease Report search, the results page has two region columns rather than region then rayon.

**Details**
Environment: (GAT or External): External
Script ID (or enter ad hoc if ad hoc): VAR04
Username: ImeretiRegionalVet
Severity (optional): Minor

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to Veterinary > Aggregate Report
2. Perform a search for a Veterinary Aggregate Disease Report
3. View columns listed in search results

**Expected behavior**
The second region column should be rayon.

**Screenshots**
![image](https://user-images.githubusercontent.com/110361057/182630446-19ac8f92-f711-4b3b-b458-d66a75ffb79d.png)

**Additional context**

**Comment by jkkannan** [comment]
Confirmed issue.

**Comment by RyanLloyd1** [comment]
Issue resolved, closed.
