### ISSUE TITLE
VAS01 - No alert after deleting Active Surveillance Campaign

### ISSUE THREAD

**Issue by AnnaSwiatecka** [EIDSS/EIDSS7#434]
**Summary**
No alert after deleting Active Surveillance Campaign

**Details**
Environment: (GAT or External): GAT
Script ID (or enter ad hoc if ad hoc): VAS01
Username: Adjara
Severity (optional): minor

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jkkannan** [comment]
Tested against VAS06, Delete Active Surveillance Campaign script, rather than script specified in bug above and tester reported via email that it worked.
