### ISSUE TITLE
VAS01 - "Duplicate records are not allowed" alert when editing Disease/Sample Type window in Veterinary Active Surveillance Campaign

### ISSUE THREAD

**Issue by AnnaSwiatecka** [EIDSS/EIDSS7#435]
**Summary**
Duplicate records are not allowed" alert when editing Disease/Sample Type window in Veterinary Active Surveillance Campaign. After this error unable to add any diseases. Editing function of disease section doesn't work.

**Details**
Environment: (GAT or External): both
Script ID (or enter ad hoc if ad hoc):VAS01
Username: adjara regional vet
Severity (optional): major

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by aatmns** [comment]
The issue is resolved.

**Comment by easleyte** [comment]
Close:  defect not detected on 8/26/2022
