### ISSUE TITLE
Case Investigation: Risk Factors

### ISSUE THREAD

**Issue by srbatni** [EIDSS/EIDSS7#44]
**Summary**
Word naming field listed cow not cattle. Not a big deal, but different from script.

**To Reproduce**
1. Log in as: Russell Peters
2. Go to: Human Disease Report Andrew Taylor
3. Click on: Case Investigation: Risk Factors

**Expected behavior**
Case investigation: risk factors under type of animal lists cow; script says cattle. Not a big deal but naming convention issue.

Screenshots**

**Additional details:**
 - Build: v7 79.0
 - Script title (enter ad hoc if not script-based): HPS03

**Issue severity**
Severity (critical, major, minor, low): Low

**Additional context**

**Comment by christhompson17** [comment]
Script issue, not a bug. The flexible form is pulled from the official Georgian DB.
