### ISSUE TITLE
OMM03: Disease report can be edited after being imported to an outbreak session (iGAT Bug 05).

### ISSUE THREAD

**Issue by NatalieShapiro** [EIDSS/EIDSS7#440]
**Summary**
During OMM03 verification steps, "Search for the original disease report by disease and date entered and verify that it is read-only and cannot be edited" does not work. Fields can still be edited in the disease report after import into an outbreak session.

**Details**
Environment: (GAT or External): External
Script ID (or enter ad hoc if ad hoc): OMM03
Username: NFAVetEpi
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Import a disease report into an outbreak session then go back to that same disease report and edit the fields (& save).

**Expected behavior**
I expect that the fields to be locked in the disease report after creating an outbreak session.

**Screenshots**

**Additional context**

**Comment by AnnaSwiatecka** [comment]
Script successfully tested
