### ISSUE TITLE
LAB Ad Hoc: Cannot properly create a derivative of a derivative 

### ISSUE THREAD

**Issue by RyanLloyd1** [EIDSS/EIDSS7#442]
**Summary**
Sample derivatives seem to still have the seed sample type which limits the types of derivatives that can be created. For example, a culture derivative from a stool seed sample is not allowed to create a DNA extract derivative because that derivative is not linked to stool samples. 

**Details**
Environment: (GAT or External): External
Script ID (or enter ad hoc if ad hoc): ad hoc
Username: AdjaraHumanZDLTech
Severity (optional): Minor

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to an accessioned stool sample and create a culture derivative
2. Click on culture derivative and attempt to create a DNA extract derivative 

**Expected behavior**
Derivative limitations should be adjusted to the derivative type rather than the original sample type. 

**Screenshots**
![image](https://user-images.githubusercontent.com/110361057/182676626-daeb52ef-3a34-401f-a0d1-a8911229a936.png)

**Additional context**

**Comment by RyanLloyd1** [comment]
User administrator can add derivative types to sample and modify sample types.

Recommend default settings allows for derivative options to be determined by derivative type rather than original sample type, if possible.

**Comment by jkkannan** [comment]
Approved and implemented.
