### ISSUE TITLE
Unable to enter information in specific areas of new Livestock and Avian Disease Reports

### ISSUE THREAD

**Issue by easleyte** [EIDSS/EIDSS7#446]
**Summary**
When attempting to enter data for a new Avian/Livestock Disease Report, I was unable to enter any data within the Farm/Herd/Species and the Species Investigation sections.  Within the Animal Details section, I was unable to enter both Species and Age and within the Sample section, I was unable to enter a Species.

**Details**
Environment: (GAT or External): 
Script ID (or enter ad hoc if ad hoc):
Username: 
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jkkannan** [comment]
Logged in as user KedaDistrictVet.

**Comment by easleyte** [comment]
Close....worked as expected
