### ISSUE TITLE
Unable to modify Accession Date

### ISSUE THREAD

**Issue by Chavez34** [EIDSS/EIDSS7#45]
**Summary**
Unable to modify Accession Date

**To Reproduce**
1. Log in as lisasimpson
2. Go to Laboratory>Samples

Step 1. Select (Edit) patient sample rejected status displayed.
Step 2. Select Sample Status and accept in good condition. and save.
Step 3. Select Accession Date/time system does not displayed modified date from: 7/8/2019, instead displays 6/9/2019.
Step 4. Select Save and sample tab is displayed
Step 5. Verification steps confirm rejected sample is correct to accept in good condition.
Step 6. Accession Date/Time is not confirmed: display; should display 7/2/2019

![image](https://user-images.githubusercontent.com/52667706/60899724-f1328900-a238-11e9-8253-a92c8965aa50.png)

**Expected behavior**
Correct sample status from "rejected" to "accept in good condition" and modify Accession date.

Screenshots**
Above

**Additional details:**
 - Build: 77
 - Script title Lab 09, Correct sample status from rejected to accepted and modify the Accession Date. 

**Issue severity**
Severity:  Minor

**Additional context**
N/A

**Comment by aatmns** [comment]
7/12/2019, Anatoliy
Defect confirmed.
There is no possibility to change the accessioned date for the rejected sample in the Sample/Test Details window.
![451](https://user-images.githubusercontent.com/32458032/61158596-6adfa680-a4c7-11e9-8c5f-d36d82486d40.PNG)
