### ISSUE TITLE
VAS09:  Two Known Issues

### ISSUE THREAD

**Issue by easleyte** [EIDSS/EIDSS7#453]
**Summary**
Known Issues: 
1.   No site alerts displayed for interpreted lab test results 
2.   When adding a new test, the Filter Sample by Disease box is checked

**Details**
VAS09
Username: AdjaraRegionalVet
Build: 
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
3. Click on… 

**Expected behavior**

**Screenshots**
![Screenshot (8)](https://user-images.githubusercontent.com/111596877/188157891-5215b692-9585-40d7-8124-d20dd3f74ff0.png)

**Additional context**

**Comment by easleyte** [comment]
Close:  Script:  "VAS09 Veterinary Active Surveillance:  Update an existing Veterinary Active Surveillance Session with samples collected" worked as scripted.....all steps verified.

**Comment by herashchenkoa** [comment]
According to the comment above: as scripted, all steps verified. The issue will be closed.
