### ISSUE TITLE
VAR03 - after searching the Vet Agg Report and moving between Report Details and Veterinary Agg Report, error with numbers is showing up

### ISSUE THREAD

**Issue by AnnaSwiatecka** [EIDSS/EIDSS7#457]
**Summary**
VAR03 - after searching the Vet Agg Report and moving between Report Details and Veterinary Agg Report, error with numbers is showing up

**Details**
Script ID (or enter ad hoc if ad hoc): VAR03
Username: Keda Districtvet; Lanchkhuti
Build: 
Severity (optional): minor

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by aatmns** [comment]
An error displayed:
![VAR03_numeric_error_displayed_for_investigation](https://user-images.githubusercontent.com/32458032/197564978-3538c031-128e-415b-90e6-be91e9e6d19b.PNG)

**Comment by aatmns** [comment]
To be retested in day 2.

**Comment by jkkannan** [comment]
Message appears when template field is blank when it should be populated; however, user can select a template from dropdown.

**Comment by AnnaSwiatecka** [comment]
Retested on multiple Vet Aggregate Disease Reports - no error was generated
