### ISSUE TITLE
Entry of 

### ISSUE THREAD

**Issue by Chavez34** [EIDSS/EIDSS7#46]
**Summary**
A clear and concise description of the issue.

**To Reproduce**
1. Log in as 
2. Go to 
3. Click on 

**Expected behavior**

Screenshots**

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based):

**Issue severity**
Severity (critical, major, minor, low):

**Additional context**

**Comment by jkkannan** [comment]
Appears to be truncated entry of #51.  Removed bug label; only label is duplicate.

**Comment by christhompson17** [comment]
Closing due to incomplete duplicate.
