### ISSUE TITLE
Case Investigation: Contact List

### ISSUE THREAD

**Issue by srbatni** [EIDSS/EIDSS7#48]
**Summary**
Script notes in case investigation contact list when add control that Jason Burns' record should be in the grid. It was not.

**To Reproduce**
1. Log in as: Russell Peters Epidemiologist
2. Go to: Human Disease Report
3. Click on: Case Investigation: Contact List

**Expected behavior**
Jason Burns' record should have been displayed in the modal window under search person. It was not.

Screenshots**

**Additional details:**
 - Build: v7 79.0
 - Script title (enter ad hoc if not script-based): HPS03

**Issue severity**
Severity (critical, major, minor, low): Low

**Additional context**

**Comment by christhompson17** [comment]
Need Data team to confirm if "Jason Burns" exists in the DB. If he does not, this is a GAT data issue and not a bug.
