### ISSUE TITLE
PIN doesn't work in GG version

### ISSUE THREAD

**Issue by TulendinovT** [EIDSS/EIDSS7#488]
**Summary**
PIN doesn't work in GG version when create new Person

**Details** 
Country: GG
Scenario (or enter ad hoc if ad hoc): HPS01
If ad hoc, Category (Function, customization, localization, migration, integration): 
Username: UAT03
Build: Build: 7.0.337.9
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to the Person form
2. Go to the Information tab
3. Click on Personal ID Type
4. Choose the "PIN" value
5. Personal ID = any PIN number
6. Date of Birth: Choose Date of birth

**Expected behavior**
PIN should be work. Ok button is not active after choose Person on the PIN page
![PIN](https://user-images.githubusercontent.com/128576220/226842775-71a69fea-c184-4ea8-976b-c663f3309b15.jpg)

**Screenshots**

**Additional context**

**Comment by herashchenkoa** [comment]
This issue has been addressed. Please verify to confirm that they issue is resolved.

**Comment by bakuradzebakuradze** [comment]
The problem has been resolved, This issue is closed

**Comment by herashchenkoa** [comment]
Based on the comment below from WG, the issue is closed.
