### ISSUE TITLE
Drop-down menu doesn't work correctly. GG version

### ISSUE THREAD

**Issue by GiorgiBakhtadze** [EIDSS/EIDSS7#490]
**Summary**
Drop-down menu doesn't work correctly in Farm Epi information tab in Vet DR

**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):VPS20
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: Bakhtadze
Build: 7.0.337.9 
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to the step 6
2. Choose: Disease Brucellosis - Abortus
3. Farm/Herd/Species: Cow/Bull
4. Go to Farm Epi Inform tab
5. All fields with drop-down menu in this tab doesn't work correctly

**Expected behavior**

Drop-down menu in this tab should be work correctly. Should be possible choose any values in those fields.

**Screenshots**
See attachment

**Additional context**
Add any other context about the problem here.[VetDR_Drop-down menu in Epi form.docx](https://github.com/EIDSS/EIDSS7/files/11050613/VetDR_Drop-down.menu.in.Epi.form.docx)

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.411. Please verify to confirm that the issue was resolved.

**Comment by schegelidze** [comment]
It is fixed, but can't close because I am not Author and Giorgi Bakhtadze can't close it.

**Comment by herashchenkoa** [comment]
Closing the bug as fixed based on the user's feedback.
