### ISSUE TITLE
issue about person, human application does not allow us to drop down the settlement type and settlement list

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#494]
**Summary**
when creating person, human application does not allow us to drop down the settlement type and settlement list At different times

**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc): Function
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build:  7.0.342.14
Severity (optional): Significant

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… Human>Person
2. Click on… region, district (rayon)  settlement type, and settlement

**Expected behavior**
allow us to drop down the settlement type and settlement list At different times

**Screenshots**
If applicable, add screenshots to help explain your problem.  Please blur or cover any personally identifiable information in any screenshots.
![image](https://user-images.githubusercontent.com/128576431/230599089-55089787-2d63-45b3-8e27-5e37cbdb5f97.png)

**Additional context**

**Comment by herashchenkoa** [comment]
This issue has been addressed. Please verify to confirm that the issue was resolved.
