### ISSUE TITLE
Human>Person Find in PIN System 

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#496]
**Summary**
When we register a person in Georgian and use the Find in PIN System, the person is searched in English, so the surname and first name are transferred into English.

**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc): General Issue
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: 
Severity (optional): High

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… Human>Person
2. Click on… Find in PIN System

**Expected behavior**
The person should be found in the Georgian language Find in PIN System and saved in Georgian 

**Screenshots**
If applicable, add screenshots to help explain your problem.  Please blur or cover any personally identifiable information in any screenshots.

**Additional context**

**Comment by bakuradzebakuradze** [comment]
Severity (optional): High

**Comment by herashchenkoa** [comment]
The issue is not reproducible in EIDSS Release v7.0.427. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The issue is closed
