### ISSUE TITLE
In the v7 Georgian version, "Find in PIN System" is not translated

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#497]
**Summary**
In the v7 Georgian version, "Find in PIN System" is not translated, Where should it be written "ძებნა სამოქალაქო რეესტრში"
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc): Function
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: 
Severity (optional): Low

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… Human>Person
2. Click on… 

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem.  Please blur or cover any personally identifiable information in any screenshots.

**Additional context**

**Comment by bakuradzebakuradze** [comment]
The issue is the same and has not changed
![497](https://github.com/EIDSS/EIDSS7/assets/128576431/12ee5e79-cf4d-41e5-91c2-825830cbabae)
Severity: Low

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.411. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The issue was resolved, this issue is closed
