### ISSUE TITLE
Problem with login in Beta-environment

### ISSUE THREAD

**Issue by zlatarasulzade** [EIDSS/EIDSS7#5]
MoH EIDSS WG members could not sign in beta environment by given link (http://192.255.51.93/Azerbaijan) because of http-error. (please see attached screenshot)

![beta_env_error](https://user-images.githubusercontent.com/36696557/43569800-9e6448cc-9649-11e8-82ae-00ac2b6425d6.jpg)

**Comment by DenBerry** [comment]
The EIDSS Beta Site (http://192.255.51.93/Azerbaijan) is up and running.

**Comment by sheagraffo** [comment]
If link is working, please close this issue.  Thanks.

**Comment by zlatarasulzade** [comment]
Link is working. Thank you.
