### ISSUE TITLE
AMD11 Administration - Manage Personal Identification (ID) Types

### ISSUE THREAD

**Issue by Aj-Kakar** [EIDSS/EIDSS7#50]
**Summary**

Missing drop down for "Personal Identification Types Matrix".

**To Reproduce**
1. Log in as rykermase
2. Refer to Step recording attached 

**Expected behavior**
User should be able to select Personal Identification Types Matrix from the drop down menu.

Screenshots**
[Missing Dropdown in Configuration.zip](https://github.com/EIDSS/EIDSS7/files/3373660/Missing.Dropdown.in.Configuration.zip)

**Issue severity**
Minor 

**Build**
79

**Comment by christhompson17** [comment]
This is a confirmed bug. This requirement was added to the sprint requirements at a much later date and is missing from the system.

**Comment by EBH2001** [comment]
Not reproducible in Integration build 83.4

**PLEASE SEE ATTACHMENT**

[ADM11_GitHub#50_Add_Personal_ID_Type_NotReproducible.docx](https://github.com/EIDSS/EIDSS7/files/3401974/ADM11_GitHub.50_Add_Personal_ID_Type_NotReproducible.docx)

**Comment by jkkannan** [comment]
Closed during GAT remediation.  Dropdown is now present.
