### ISSUE TITLE
human>person>Citizenship>Passport Number 

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#505]
**Summary**
"Passport number" should have been written in case of citizenship of a foreign country 

**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc): Function
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: 
Build: 7.0.343.47 
Severity (optional): Important

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… human>person>Citizenship> passport number
2. Click on… 

**Expected behavior**
A passport number is written in case of citizenship of a foreign country

**Screenshots**
If applicable, add screenshots to help explain your problem.  Please blur or cover any personally identifiable information in any screenshots.

**Additional context**

**Comment by herashchenkoa** [comment]
"Passport number" field is available for entering data in case of citizenship of a foreign country; the field is optional and not mandatory.

**Comment by bakuradzebakuradze** [comment]
The problem has been resolved, This issue is closed
