### ISSUE TITLE
Human>Person>Address >Permanent Address translation

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#506]
**Summary**
Human>Person>Address >Permanent Address is not translated 
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc): 
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: 7.0.343.47
Severity (optional): important 

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… Human>Person>Address 
2. Click on… 

**Expected behavior**
Human>Person>Address >Permanent Address is not translated as "მუდმივი მისამართი"

**Screenshots**
If applicable, add scre
![12](https://user-images.githubusercontent.com/128576431/230905130-f474782f-f1a1-4941-9376-4e7aede49478.PNG)
enshots to help explain your problem.  Please blur or cover any personally identifiable information in any screenshots.

**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.411. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The problem has been resolved, this issue is closed
