### ISSUE TITLE
Human>Person>Address > Alternate Address translation

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#507]
**Summary**
Human>Person>Address > Alternate Address is not translated

**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: 7.0.343.47
Severity (optional): Important

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… Human>Person>Address >  Alternate Address
2. Click on… 

**Expected behavior**
Human>Person>Address > Alternate Address is not translated as "ალტერნატიული მისამართი"

**Screenshots**
![333](https://user-images.githubusercontent.com/128576431/230905668-381bcacb-24a4-45e1-8315-0d63512ad52a.PNG)
If applicable, add screenshots to help explain your problem.  Please blur or cover any personally identifiable information in any screenshots.

**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been resolved in EIDSSv7 build 7.0.402. Please verify.

**Comment by bakuradzebakuradze** [comment]
The issue has been resolved in EIDSSv7 build 7.0.402.
