### ISSUE TITLE
human>person>Employment/School Does the Person currently attend school? translation

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#511]
**Summary**
human>person>Employment/School Does the Person currently attend school? should be translated as " დადის ეს პირი ამჟამად სასწავლო დაწესებულებაში? "

**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): Function
Username: bakuradze
Build: 7.0.343.47
Severity (optional): Low

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… human>person>Employment/School 
2. Click on… Does the Person currently attend school?  

**Expected behavior**
Does the Person currently attend school? should be translated as " დადის ეს პირი ამჟამად სასწავლო დაწესებულებაში? "

**Screenshots**
If applic
![წწწ](https://user-images.githubusercontent.com/128576431/231168956-5cdba29c-45f5-4c92-b5d0-cd3011004997.PNG)
able, add screenshots to help explain your problem.  Please blur or cover any personally identifiable information in any screenshots.

**Additional context**

**Comment by bakuradzebakuradze** [comment]
The issue is not resolved   Build: 7.0.402
![511](https://github.com/EIDSS/EIDSS7/assets/128576431/0dcbc1c4-0b62-4084-9fe1-9139386a4e1d)

Human>person>Employment/School Does the Person currently attend school? should be translated as " დადის ეს პირი ამჟამად სასწავლო დაწესებულებაში? "

Severity: Low

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.411. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The problem has been resolved, This issue is closed
