### ISSUE TITLE
human>person>Employment/School School Name translation 

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#512]
**Summary**
human>person>Employment/School School Name should be translated as "სასწავლო დაწესებულების სახელწოდება" 
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): Function
Username: bakuradze
Build: 7.0.343.47
Severity (optional): important

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… human>person>Employment/School 
2. Click on… Does the Person currently attend school? >School Name

**Expected behavior**
School Name should be translated as "სასწავლო დაწესებულების სახელწოდება"

**Screenshots**
If applicable, 
![rrrr](https://user-images.githubusercontent.com/128576431/231170210-f207ac35-c4d5-44c2-942a-7fca0d13e493.PNG)
add screenshots to help explain your problem.  Please blur or cover any personally identifiable information in any screenshots.

**Additional context**

**Comment by bakuradzebakuradze** [comment]
The issue is not resolved
![512](https://github.com/EIDSS/EIDSS7/assets/128576431/0712b3cf-302f-4f55-9353-f5c917996989)
human>person>Employment/School School Name should be translated as "სასწავლო დაწესებულების სახელწოდება"
Severity: Low

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.411. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The problem has been resolved, This issue is closed
