### ISSUE TITLE
Contact Information: Relation

### ISSUE THREAD

**Issue by srbatni** [EIDSS/EIDSS7#52]
Under relation, neighbor was not a drop down field.

**To Reproduce**
1. Log in as Russell Peters
2. Go to Human Disease Report
3. Click on Contact List grid

**Expected behavior**
Neighbor should have been a drop down selection. It was not.

Screenshots**

**Additional details:**
 - Build: v7 79.0
 - Script title (enter ad hoc if not script-based): HPS03

**Issue severity**
Severity (critical, major, minor, low): Low

**Additional context**

**Comment by christhompson17** [comment]
Sent to DB team to determine if this is a bug or not available reference data in the GG DB.

**Comment by christhompson17** [comment]
Reviewed by DB team. These items had been soft deleted in the DB and would not have displayed. Not a bug.
