### ISSUE TITLE
human>person>employment/school Does the Person currently attend school? section  School Name box 

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#520]
**Summary**
human>person>employment/school Does the Person currently attend school? section  School Name box  The field does not accept textual information after memorization, it displays question marks instead of text. Must remember both numerical and textual information
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): function
Username: bakuradze 
Build: 
Severity (optional): Medium 

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… human>person>employment/school Does the Person currently attend school? section  School Name box 
2. Click on… 

**Expected behavior**
Must remember both numerical and textual information 

**Screenshots**
![image](https://user-images.githubusercontent.com/128576431/231448577-5a63453f-edf3-44a0-9e1e-9be32a26e125.png)

**Additional context**

**Comment by bakuradzebakuradze** [comment]
Severity (optional): Medium

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.427. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
We enter the person by editing, we write the data of the school, we remember it, then we search for the person from the beginning, where the saved data related to the school is no longer visible.
![თერჯოლა](https://github.com/EIDSS/EIDSS7/assets/128576431/314938ee-4590-4628-a25e-0f377e41e4fd)
![თერჯოლა1](https://github.com/EIDSS/EIDSS7/assets/128576431/b320e2f6-1b3b-4232-81a9-68ec05de5e1c)
![დადის სასწავლო](https://github.com/EIDSS/EIDSS7/assets/128576431/27e51b9f-d60c-4052-9de2-36ba683476e0)
![არ იმახსოვრებს](https://github.com/EIDSS/EIDSS7/assets/128576431/5263c3a9-ad4a-4c33-b9b4-bc849f5f1fc6)

**Comment by bakuradzebakuradze** [comment]
The issue is closed
