### ISSUE TITLE
Human Disease Report>Notification>disease is a mandatory field after saving the case it does not allow us to change it after saving in v7 and in v6 is as well mandatory field but gives us permission to change it after saving 

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#522]
**Summary**
Human Disease Report>Notification>disease is a mandatory field after saving the case it does not allow us to change it after saving in v7 and in v6 Human Disease Report>Notification>disease is as well mandatory field but gives us permission to change it after saving 
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc): 
If ad hoc, Category (Function, customization, , migration, integration) (optional): Function
Username: bakuradze
Build: 7.0.343.47
Severity (optional): important 

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… Human Disease Report>Notification>disease enter any disease save and try to change  
2. Click on… 

**Expected behavior**
to have permission change saved notifiable diseases  

**Screenshots**
![nitifable](https://user-images.githubusercontent.com/128576431/231700106-00f50aa3-8e00-4926-892a-4e4f6079e265.PNG)

**Additional context**

**Comment by TulendinovT** [comment]
Logic of Connecting DR is removed, the bug should be obsolete and closed. Could you please confirm.

**Comment by bakuradzebakuradze** [comment]
I checked and it still doesn't allow us to change the previously specified disease
![დდდ](https://github.com/user-attachments/assets/9f24c5d8-25da-4dad-970d-093922bf03df)

**Comment by bakuradzebakuradze** [comment]
The issue remains open

**Comment by bakuradzebakuradze** [comment]
The issue is closed
