### ISSUE TITLE
Human Aggregate Disease Report  

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#523]
**Summary**
When searching for an aggregated report, specifying a time interval (for example, January-February 2023), the end date of the interval must be entered as 01.04.23, not 31.03.23 If we do not specify the last date, then it brings fixed data and then displays a warning.
In the English version, it does not do so, probably the problem is in the date format in the Georgian version (Georgian day.month.year and in English month.day.year) 
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): Function
Username: bakuradze
Build: 
Severity (optional): high

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… Human Aggregate Disease Report  
2. Click on…  searching for an aggregated report, specifying a time interval

**Expected behavior**

**Screenshots**
![Capture](https://user-images.githubusercontent.com/128576431/231720687-b92b2563-b5eb-4666-b61a-53b1185729d0.PNG)

**Additional context**

**Comment by bakuradzebakuradze** [comment]
Severity (optional): high

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.427. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The issue is closed
