### ISSUE TITLE
The dating in the v7 program is probably completely should be inspected. When translating into Georgian language, to be in Georgian order and not in English, the date should be Georgian day.month.year and not month.day year

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#524]
**Summary**
The dating in the v7 program is probably completely should be inspected. When translating into the Georgian language, date to be in Georgian order and not in English, the date should be in Georgian day. month. year and not month.day. year
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): Function
Username: bakuradze
Build: 
Severity (optional): Critical

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… The dating in the v7 program is probably completely inspected. When translating into the Georgian language, the date to be in Georgian order and not in English, the date should be in Georgian day. month. year and not month.day. year
2. Click on… 

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem.  Please blur or cover any personally identifiable information in any screenshots.

**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.480. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The problem is resolved
