### ISSUE TITLE
Human Aggregate Disease Report data table 

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#525]
**Summary**
Human Aggregate Disease Report data table, column disease, and ICD-10 are not frozen when Dragging left or right, the user can not see which disease cases are entered in the next box because the disease and ICD-10 code are not seen  

**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): function
Username: bakuradze
Build: 7.0.343.47 
Severity (optional): Medium
 
**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… Human Aggregate Disease Report data table, 
2. Click on… Dragging left or right to see the data 

**Expected behavior**

**Screenshots**
![data](https://user-images.githubusercontent.com/128576431/231734702-9b05c3e7-6c38-4d71-9cf6-940f00530648.PNG)
![data2](https://user-images.githubusercontent.com/128576431/231734942-ca40c8da-1b89-4c08-972b-2eb1301ae7ad.PNG)

**Additional context**

**Comment by bakuradzebakuradze** [comment]
The issue is partially resolved because the white background looks bad visually, maybe the diseases and ICD codes can be placed in the boxes 
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/8756ac46-0e41-406e-8485-546ee36a3f25)

**Comment by bakuradzebakuradze** [comment]
Severity (optional): Medium

**Comment by bakuradzebakuradze** [comment]
The issue was resolved but it needs a translation
<img width="936" alt="Screenshot 2023-12-26 130533" src="https://github.com/EIDSS/EIDSS7/assets/128576431/a2be8aa0-9d25-4b32-815e-3ddad765ecc9">

**Comment by herashchenkoa** [comment]
Based on the user's feedback, the bug described in this issue is resolved. Thus, this bug will be closed.
For the issue related to missing translation a new issue was opened https://github.com/EIDSS/EIDSS7/issues/877
