### ISSUE TITLE
While saving a human person or human disease cases most of the time program stuck

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#527]
**Summary**
While saving a human person or human disease cases most of the time the program stuck

**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): Function
Username: bakuradze
Build: 
Severity (optional): high

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… human person or human disease cases and save 
2. Click on… 

**Expected behavior**
the program should be fast not so slow

**Screenshots**
If applicable, add screenshots to help explain your problem.  Please blur or cover any personally identifiable information in any screenshots.

**Additional context**

**Comment by bakuradzebakuradze** [comment]
Severity (optional): high

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.411. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The issue was resolved, this issue is closed
