### ISSUE TITLE
Error system time out

### ISSUE THREAD

**Issue by srbatni** [EIDSS/EIDSS7#53]
**Summary**
After hitting save in the contact information modal window, the system timed out with an Error message

**To Reproduce**
1. Log in as: Russell Peters
2. Go to: Human Disease Report
3. Click on: Contact Information Modal Window

**Expected behavior**
Contact information window closed and system populates entered data as a new row in the Contact List. Instead, the system timed out when I hit save and I received an Error Message.

Screenshots**
![image](https://user-images.githubusercontent.com/52708365/60901767-5d09f700-a223-11e9-81ce-d97229e15f1c.png)

**Additional details:**
 - Build: v7 79.0
 - Script title (enter ad hoc if not script-based): HPS03

**Issue severity**
Severity (critical, major, minor, low): Critical

**Additional context**

**Comment by jkkannan** [comment]
Closed during GAT remediation.  Able to edit/add contacts. Related to #151 as well.
