### ISSUE TITLE
the result of viewing the aggregated report. I tried several different places and dates.

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#535]
**Summary**
 the result of viewing the aggregated report. I tried several different places and dates.
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: 
Severity (optional): high

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/128576431/232755651-583287f9-860d-489d-9076-30f92f1fceef.png)

**Additional context**

**Comment by bakuradzebakuradze** [comment]
Severity (optional): high

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.411. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The problem has been resolved, This issue is closed
