### ISSUE TITLE
human disease report> Notification>Current location of patient>Hospital Name table of contents does not work table of contents

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#536]
**Summary**
human disease report> Notification>Current location of patient>Hospital Name table of contents does not work table of contents
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc): HPS02
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: 7.0.343.47
Severity (optional): 

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… human disease report> Notification>Current location of patient>Hospital Name
2. Click on… 

**Expected behavior**
to work table of contents

**Screenshots**
If applicable, add screenshots to help explain your problem.  Please blur or cover any personally identifiable information in any screenshots.

**Additional context**

**Comment by aherashchenko** [comment]
Update based on the discussion with WG on May 10, 2023:: WG mentioned that there is a list of Hospital values in v6.1 that shall be transferred in v7.

**Comment by herashchenkoa** [comment]
This issue will be addressed as part of the approved Change Control Board (CCB) №4 meeting on February 13, 2024, and will be included in the feature EIDSSv7 releases.

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.480. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The problem is resolved but the translation is not correct
