### ISSUE TITLE
HPS05 Changing the final case classification to No Case

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#539]
**Summary**
On the report panel, it shows me the case in the process, when we open the case in the classification of the final case, it shows me to be changed as not a case, and despite being closed, it still shows the same way despite refreshing
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc): HPS05 
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: 
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem.  Please blur or cover any personally identifiable information in any screenshots.

**Additional context**

**Comment by aherashchenko** [comment]
Update based on the discussion with WG on May 10, 2023: 
Unable to save Disease Report when 'Final Case Classification' is set to 'Not a Case' and 'Case status' is set to 'Closed '. 
Review tab | Click the Save button | A message to create Connected Disease Report (CDR) opens | Click 'No' | Message to create CDR closes | As a result the case is not saving. Only the option to create a CDR remains.

**Comment by bakuradzebakuradze** [comment]
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/27d7e0a7-65ab-4076-8240-c14c2b7b5e92)

**Comment by TulendinovT** [comment]
Logic of Connecting DR is removed, the bug should be obsolete and closed. Could you please confirm.
