### ISSUE TITLE
VPS01 calendar auto populate with today's date

### ISSUE THREAD

**Issue by jeanmrichards** [EIDSS/EIDSS7#54]
**Summary**
when I try to choose the date of the "start of signs" for the herd (any herd - same issue with all new herds I added) and click on the calendar symbol and then try to choose the back arrow to go back to June it auto selects today's date and closes out before I can get to June. If I go back in it gives me the time to go back and choose a date in June, but if it's empty to begin with, no date selected, then it wants to auto populate with the highlighted date for today. There is a work around -more of an annoyance.

**To Reproduce**
1. Log in as ryan johnson
see attached

**Expected behavior**
Expected the calendar to allow me to choose a specific date but before I can get there it chooses for me and closes.

Screenshots**
see attached

**Additional details:**
 - Build: 79.0
 - VPS01

**Issue severity**
Severity (critical, major, minor, low): low

**Additional context**
[VPS01 calendar auto populate.zip](https://github.com/EIDSS/EIDSS7/files/3373967/VPS01.calendar.auto.populate.zip)

**Comment by jeanmrichards** [comment]
Uploading VPS01 calendar auto populate.zip…]()

**Comment by christhompson17** [comment]
Was able to reproduce. Priority assigned.
