### ISSUE TITLE
HPS05 Change the case status to closed does not work

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#541]
**Summary**
HPS05 Change the case status to closed does not work
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc): HPS05
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build:  
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem.  Please blur or cover any personally identifiable information in any screenshots.

**Additional context**

**Comment by herashchenkoa** [comment]
This issue is not reproducible. It is possible to change the case status to closed. Please verify.

**Comment by bakuradzebakuradze** [comment]
The problem has been resolved, This issue is closed
