### ISSUE TITLE
HPS05 Go to the review page and select the [Save] button

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#542]
**Summary**
HPS05 Go to the review page and select the [Save] button does not work
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc): HPS05 
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: 
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem.  Please blur or cover any personally identifiable information in any screenshots.

**Additional context**

**Comment by herashchenkoa** [comment]
This issue has been addressed. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The problem has been resolved, This issue is closed
