### ISSUE TITLE
HPS05 sample field does not work and risk factors does not exists for hepatitis A

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#543]
**Summary**
The HPS05 sample field does not let me add a sample  and risk factors do not exist for hepatitis A
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: HPS05 
Severity (optional): low

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem.  Please blur or cover any personally identifiable information in any screenshots.

**Additional context**

**Comment by jkkannan** [comment]
Determinant of disease for flexible form for risk factors is not present. Please hold off on testing flexible forms until determinants are in place; we will notify users at that time.

**Comment by aherashchenko** [comment]
Based on the UAT support meeting on June 13, 2023, Risk Factors for hepatitis A appear but are now not migrated correctly, the fields are in the wrong order.

**Comment by bakuradzebakuradze** [comment]
Sample field is working and risk factors are presented for hepatitis A but the risk factors questionnaire questions are messed up

**Comment by bakuradzebakuradze** [comment]
Severity: low

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.411. Please verify to confirm that the issue was resolved.
