### ISSUE TITLE
human>person work school section is filled but do not transfer it in human disease report Neither in English nor in Georgian version

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#544]
**Summary**
human>person work school section is filled but do not transfer it in human disease report Neither in English nor in Georgian version
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: 
Severity (optional): high

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/128576431/232786098-87ca6b2d-b28a-4557-94b6-bf11494152c3.png)
![image](https://user-images.githubusercontent.com/128576431/232786122-efe1a8d0-505e-462b-93fa-2c86cb5e8e10.png)

**Additional context**

**Comment by bakuradzebakuradze** [comment]
Severity (optional): high

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.480. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
the issue is closed
