### ISSUE TITLE
Georgian v7 Human Disease Report>Notification>Notification Sent by Name He lets you to save, but then this addition is nowhere to be seen.

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#545]
**Summary**
Georgian v7 Human Disease Report>Notification>Notification Sent by Name He lets you to save, but then this addition is nowhere to be seen. The same was done in the v7 English version end addition was done correctly and seen after Checking in the Georgian version to
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: 7.0.345.54
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… Human Disease Report>Notification>Notification Sent by Name
2. Click on… 

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem.  Please blur or cover any personally identifiable information in any screenshots.

**Additional context**

**Comment by herashchenkoa** [comment]
It is possible to create and then search and select for the person for Notification Sent by Name. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The problem has been resolved, This issue is closed
