### ISSUE TITLE
Georgian v7 Human Disease Report>Notification>samples>Collected by Officer box does not work

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#546]
**Summary**
Georgian v7 Human Disease Report>Notification>samples>Collected by Officer box lets you to save, but then this addition is nowhere to be seen end search by name or surname does not work you have to scroll and find the preferred person

**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: 7.0.345.54
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… Human Disease Report>Notification>samples>Collected by Officer box
2. Click on… 

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem.  Please blur or cover any personally identifiable information in any screenshots.

**Additional context**

**Comment by herashchenkoa** [comment]
The issue is not reproducible in EIDSS Release v7.0.427. Please verify to confirm that the issue was resolved.
