### ISSUE TITLE
Vector surveillance Session search screen data entry fields for disease (ASF) is not listed and ASF failed to display after following the search criteria . 

### ISSUE THREAD

**Issue by shahina77** [EIDSS/EIDSS7#55]
**Summary**
Vector surveillance Session search screen data entry fields for disease (ASF) is not listed and ASF failed to display after following the search criteria . 

**To Reproduce**
1. Log in as 
2. Go to 
3. Click on 

**Expected behavior**
Vector surveillance Session with ASF disease should display. 

Screenshots**

**Additional details:**
 - Build: 80
 - Script title (enter ad hoc if not script-based):

**Issue severity**
Severity (critical, major, minor, low):
Critical 
**Additional context**
VEC02
[VEC02.zip](https://github.com/EIDSS/EIDSS7/files/3373759/VEC02.zip)

**Comment by christhompson17** [comment]
This is a script issue. The script asks the tester to search for "ASF" in the drop down, when in reality the script should have read "African Swine Fever".
