### ISSUE TITLE
Human Aggregate Disease Report > Printing a list of human aggregate disease cases report

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#550]
**Summary**
Printing a list of human aggregate disease cases report  records from the search results grid does not work it brings an error  
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc): HAR01
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: 
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem.  Please blur or cover any personally identifiable information in any screenshots.

**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.427. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The issue is closed
