### ISSUE TITLE
HAS03 Human Active Surveillance Session Session ID HASTBTBZ230014 > Disease Reports nothing is display in this section 

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#553]
**Summary**
HAS03 Human Active Surveillance Session Session ID HASTBTBZ230014 > Disease Reports Nothing is displayed in this section 

**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):HAS03 
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: 7.0.345.54
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… Human Active Surveillance Session Session ID HASTBTBZ230014  Disease Reports
2. Click on… 

**Expected behavior**

**Screenshots**
![1654](https://user-images.githubusercontent.com/128576431/233988536-dd0cd88d-81cb-44f3-b7f5-64c645fc6033.PNG)

**Additional context**

**Comment by herashchenkoa** [comment]
Based on the rules, the system shall allow creating of the new human disease report only from a laboratory test result tab that is marked as “indicative” for a non-aggregate disease. Once Human Disease Reports are created, they will be visible on the Disease Reports tab.

**Comment by bakuradzebakuradze** [comment]
The issue has been resolved
