### ISSUE TITLE
OMM01 Outbreak Session>Outbreak Summary>Variables are not translated

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#554]
**Summary**
OMM01 Outbreak Session>Outbreak Summary>Variables are not translated

**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):  
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build:  7.0.345.54 
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/128576431/233999832-22ff983e-a8be-4ed9-8c8f-ae85349fa369.png)

**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been resolved in EIDSSv7 build 7.0.402. Please verify.

**Comment by bakuradzebakuradze** [comment]
The issue has been resolved
