### ISSUE TITLE
program translation problem 

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#555]
**Summary**
program translation problem as we wear working with v7 program translated itself see screenshot

**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakurade
Build: 
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/128576431/234001670-7e5ee3f2-d5bd-446e-ad16-334d224c045d.png)

**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSSv7 build 7.0.402. GG translations of the EIDSSv6.1 User Interface elements were extracted and matched them against the EIDSSv7 User Interface elements. Fields or messages missing translations were translated or quality checked by BV’s in-country teams. Please verify.

**Comment by bakuradzebakuradze** [comment]
The issue has been resolved
