### ISSUE TITLE
OMM01 Outbreak Session Person ID PER23001265332 review List of Symptoms and Date of Disease are not translated

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#556]
**Summary**
OMM01 Outbreak Session Person ID PER23001265332 review List of Symptoms and Date of Disease is not translated
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: 7.0.345.54 
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/128576431/234003501-d04625c1-f83b-4382-9b67-137a3790340c.png)

**Additional context**

**Comment by bakuradzebakuradze** [comment]
translated

**Comment by herashchenkoa** [comment]
The issue has been resolved in EIDSSv7 build 7.0.402. Please verify and close the issue.

**Comment by bakuradzebakuradze** [comment]
The issue has been resolved
