### ISSUE TITLE
In the tabs of risk factors (e.g. measles, rubella, mumps, pertussis), the date of vaccination is recorded in the Georgian version with the European date (month/day/year). In the English version, when the date was registered, when it was transferred to the Georgian version, that date worked, and in the Georgian version, if we enter, e.g. 30.12.2016, the system does not understand and does not remember the incident, although it does not give a warning.

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#558]
**Summary**
In the tabs of risk factors (e.g. measles, rubella, mumps, pertussis), the date of vaccination is recorded in the Georgian version with the European date (month/day/year). In the English version, when the date was registered, when it was transferred to the Georgian version, that date worked, and in the Georgian version, if we enter, e.g. 30.12.2016, the system does not understand and does not remember the incident, although it does not give a warning.
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: 
Severity (optional): critical

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem.  Please blur or cover any personally identifiable information in any screenshots.

**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.411. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The issue is closed
