### ISSUE TITLE
When registering nosocomial pneumonia, the human disease report, by whom the notification is received, the list of receiving persons, half in Latin, half in Georgian

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#559]
**Summary**
When registering nosocomial pneumonia, in the human disease report by whom the notification is received, the list of receiving persons, half in Latin, half in Georgian
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc): 
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: 7.0.347.7
Severity (MANDATORY): important

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… human disease report by whom the notification is received
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/128576431/235302264-a14e4c7f-c32c-4934-b90d-41612ced1308.png)

**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been resolved in EIDSSv7 build 7.0.402. Please verify.

**Comment by bakuradzebakuradze** [comment]
The issue has been resolved
