### ISSUE TITLE
human disease report Current location of patient hospital and hospital name search box there are only three hospital name 

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#561]
**Summary**
human disease report Current location of patient hospital and hospital name search box there are only three hospital name 
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: 
Severity (MANDATORY): high

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… human disease report Current location of patient hospital and hospital name
2. Click on… 

**Expected behavior**
![image](https://user-images.githubusercontent.com/128576431/235302787-29b74ecf-f1e1-4b20-bd02-4c4e91162ae7.png)
**Screenshots**
If applicable, add screenshots to help explain your problem.  Please blur or cover any personally identifiable information in any screenshots.

**Additional context**

**Comment by bakuradzebakuradze** [comment]
Severity (MANDATORY): high

**Comment by herashchenkoa** [comment]
This issue will be addressed as part of the approved Change Control Board (CCB) №4 meeting on February 13, 2024, and will be included in the feature EIDSSv7 releases.

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.480. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
the issue is closed
