### ISSUE TITLE
human disease report>Clinical Information-Symptoms> Date of Symptoms Onset>(month of March) 01.03.23 he will remember 1.3.23 instead. This problem also occurs elsewhere, where dates are written, for example, the date of hospitalization 

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#562]
**Summary**
human disease report>Clinical Information-Symptoms> Date of Symptoms Onset  (month of March) 01.03.23 he will remember 1.3.23 instead. This problem also occurs elsewhere, where dates are written, for example, the date of hospitalization
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: 
Severity (MANDATORY): the most critical issue

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/128576431/235303191-90f6ac2c-7049-4df9-9fee-85527b0eebf6.png)

**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.411. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The problem has been resolved, This issue is closed
