### ISSUE TITLE
Human Disease Report>Clinical Information-Facility Details>Hospitalization>Hospital Name search box There are only three hospital names

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#563]
**Summary**
Human Disease Report>Clinical Information-Facility Details>Hospitalization>Hospital Name search box There are only three hospital names
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: 
Severity (MANDATORY): high

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… Human Disease Report>Clinical Information-Facility Details>Hospitalization>Hospital Name search box 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/128576431/235303442-0d969813-899a-4cf2-8cbc-0d22244bbff3.png)

**Additional context**

**Comment by bakuradzebakuradze** [comment]
Severity (MANDATORY): high

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.427. Please verify to confirm that the issue was resolved.
Hospital Name field is now converted to the textbox without drop-down list as it was in EIDSSv6.1 so that users are able to enter any value.

**Comment by bakuradzebakuradze** [comment]
The issue is closed
