### ISSUE TITLE
Human Disease Report > Notification>date of diagnosis was entered but it did not save and disappeared

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#564]
**Summary**
Human Disease Report > Notification>date of diagnosis was entered but it did not save and disappeared

**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: 
Severity (MANDATORY): high

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… Human Disease Report > Notification>date of diagnosis
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/128576431/235303761-02ddbad7-6e51-4e65-a02e-cbe6467ac4ed.png)

**Additional context**

**Comment by bakuradzebakuradze** [comment]
Severity (MANDATORY): high

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.480. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
the issue is closed
