### ISSUE TITLE
Human Disease Report>Clinical Information-Facility Details>Date of Hospitalization was entered but did not save and disappeared 

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#565]
**Summary**
Human Disease Report>Clinical Information-Facility Details>Date of Hospitalization was entered but did not save and disappeared 
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: 
Severity (MANDATORY): high

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem.  Please blur or cover any personally identifiable information in any screenshots.

**Additional context**

**Comment by bakuradzebakuradze** [comment]
Severity (MANDATORY): high

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.480. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
the issue is closed
