### ISSUE TITLE
HAS04 Human Active Surveillance Session>Check steps: Verify that a site notification appears on the screen for a newly created record of an active human supervision session>not visible  

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#566]
**Summary**
HAS04 Human Active Surveillance Session>Check steps: Verify that a site notification appears on the screen for a newly created record of an active human supervision session>not visible  
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc): HAS04
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: 
Severity (MANDATORY): Critical

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem.  Please blur or cover any personally identifiable information in any screenshots.

**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been resolved in EIDSSv7 build 7.0.402. Please verify.
