### ISSUE TITLE
Vector surveillance session form displayed with autopupulated data for Rayon and failed to display disease 'Plague' after selecting all search criteria. 

### ISSUE THREAD

**Issue by shahina77** [EIDSS/EIDSS7#57]
**Summary**
Vector surveillance session form displayed with autopupulated data for Rayon and failed to display disease 'Plague' after selecting all search criteria. 
**To Reproduce**
1. Log in as 
2. Go to 
3. Click on 

**Expected behavior**
Vector surveillance session with disease -->Plague should display.   

Screenshots**

**Additional details:**
 - Build: 80
 - Script title (enter ad hoc if not script-based):

**Issue severity**
Severity (critical, major, minor, low):

**Additional context**
VEC03
[VEC03.zip](https://github.com/EIDSS/EIDSS7/files/3373782/VEC03.zip)

**Comment by christhompson17** [comment]
Data team needs to confirm is the data is in the DB, or if this is a GAT data issue.

**Comment by MaheshwarDeo** [comment]
The attached screen shot file shows that the user can select "Plague" from disease drop down list - This it either "GAT data" issue, if the VSS record being searched should be there for user to search OR it is a search form design issue - Search builds filter with "AND" clause and not "OR" clause. All filter fields should match with the record for it to display in search results.

**Comment by aatmns** [comment]
7/22/19 Anatoliy,
Retested the complete search capability for vector surveillance session using
"Status"
"Vector Type"
"Region"
"Rayon"
and "Disease". 
![1](https://user-images.githubusercontent.com/32458032/61648636-d111b980-ac7d-11e9-9a8d-8be3f5ec29ca.PNG)

The system correctly found the record. 2.png
![2](https://user-images.githubusercontent.com/32458032/61648640-d4a54080-ac7d-11e9-9330-924fae5e9af1.PNG)

Recommend closing defect as not reproducible.
