### ISSUE TITLE
HAS05>Human Active Surveillance Session>procedure >Search for a person's disease report using the person information from step 4 or the report ID from step 11> The result could not be found

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#573]
**Summary**
HAS05>Human Active Surveillance Session>procedure >Search for a person's disease report using the person information from step 4 or the report ID from step 11> The result could not be found
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc): HAS05
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: 
Severity (MANDATORY): high
**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem.  Please blur or cover any personally identifiable information in any screenshots.

**Additional context**

**Comment by bakuradzebakuradze** [comment]
Severity (MANDATORY): high

**Comment by herashchenkoa** [comment]
The issue has been tested using different scenarios and is not reproducible in EIDSS Release v7.0.427. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The issue is closed
