### ISSUE TITLE
HPS11>Human Passive Epidemiological Surveillance Print Human Disease Report>procedure>Select the "Print" button and print the emergency notification form> Result >does not print

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#576]
**Summary**
HPS11>Human Passive Epidemiological Surveillance Print Human Disease Report>procedure>Select the "Print" button and print the emergency notification form> Result >does not print
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc): HPS11
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: 
Severity (MANDATORY): Critical

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/128576431/235309263-e21c3070-a512-42a5-b299-ddc43cd5fe68.png)

**Additional context**

**Comment by herashchenkoa** [comment]
This issue has been addressed. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The problem has been resolved, This issue is closed
