### ISSUE TITLE
INT01 Were you able to enter a person with a verified PIN from the Personal Identification System of the Civil Registry Agency? We could not

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#578]
**Summary**
INT01 Were you able to enter a person with a verified PIN from the Personal Identification System of the Civil Registry Agency? We could not
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc): INT01 
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: 
Severity (MANDATORY): Critical

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem.  Please blur or cover any personally identifiable information in any screenshots.

**Additional context**

**Comment by aherashchenko** [comment]
Update based on the discussion with WG on May 10, 2023: As of May 10, 2023 the issue does not occur.

**Comment by jkkannan** [comment]
Closed based on report from WG that issue does not occur.
