### ISSUE TITLE
Diseases caused by poxviruses>Clinical Information-Symptoms >The English version has the order of the variables correctly> It is very messy in the Georgian version

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#580]
**Summary**
Diseases caused by poxviruses>Clinical Information-Symptoms >The English version has the order of the variables correctly> It is very messy in the Georgian version
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: 
Severity (MANDATORY): high

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/128576431/235310762-373ea07c-f7e3-4fa7-9ee0-06420d7a4cd3.png)
![image](https://user-images.githubusercontent.com/128576431/235310766-bf5ff883-dce6-44c1-ad79-6961cbb2b537.png)

**Additional context**

**Comment by bakuradzebakuradze** [comment]
![image](https://user-images.githubusercontent.com/128576431/235310809-3807d010-42ae-454a-9a2c-d951674a82c3.png)
![image](https://user-images.githubusercontent.com/128576431/235310810-59a46659-fd69-4a24-b099-6d013498fe39.png)

**Comment by bakuradzebakuradze** [comment]
Severity (MANDATORY): high

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.411. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The problem has been resolved, This issue is closed
