### ISSUE TITLE
risk factors for extrapulmonary TB are not transferred 

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#583]
**Summary**
risk factors for extrapulmonary TB are not transferred 
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: 
Build: 
Severity (MANDATORY): Low

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**

![ტუბ ფილტვგარეშე](https://user-images.githubusercontent.com/128576431/235312732-34354f25-9cd0-45ea-b1c9-5f1cf794adf8.PNG)

**Comment by bakuradzebakuradze** [comment]
risk factors are presented for extrapulmonary TB 
risk factors questionnaire questions are messed up   Severity: low

**Comment by herashchenkoa** [comment]
The issue with the order has been addressed. Please verify to confirm that the issue was resolved.
