### ISSUE TITLE
Comparative Report of several years by month>Diagnoses are not visible at the top of the table in v7 as it is in v6

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#585]
**Summary**
Comparative Report of several years by month>Diagnoses are not visible at the top of the table in v7 as it is in v6

**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): Function
Username: bakuradze
Build: 
Severity (MANDATORY): medium

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… Comparative Report of several years by month 
2. Click on… generate a report

**Expected behavior**

**Scre
![v6](https://user-images.githubusercontent.com/128576431/235429269-7403b642-fa90-47a1-818e-5d6b09f53bcc.PNG)
enshots**
![v7](https://user-images.githubusercontent.com/128576431/235429277-2de456ec-b7f7-461e-847d-82d95f1f4fd3.PNG)

**Additional context**

**Comment by bakuradzebakuradze** [comment]
Severity (MANDATORY): high

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.411. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The problem has been resolved, This issue is closed

**Comment by bakuradzebakuradze** [comment]
The problem has been resolved, This issue is closed
