### ISSUE TITLE
We created an aggregated report, entered the values, and saved it, the system confirmed that it saved this report successfully (Fig. 1), while verifying and opening the same report, the entered values were missing (Fig.2). However, only the details of the report were remembered (Fig. 3). Matrix details - no.

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#589]
**Summary**
We created an aggregated report, entered the values, and saved it, the system confirmed that it saved this report successfully (Fig. 1), while verifying and opening the same report, the entered values were missing (Fig.2). However, only the details of the report were remembered (Fig. 3). Matrix details - no.

**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): function
Username: bakuradze
Build: 
Severity (MANDATORY): high

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
1) ![image](https://user-images.githubusercontent.com/128576431/235482447-389d245b-414b-457b-a587-acb757532c9f.png)
2) ![image](https://user-images.githubusercontent.com/128576431/235482490-ec4114bd-82d5-495c-a04a-d34560c89c56.png)
3)![image](https://user-images.githubusercontent.com/128576431/235482527-897d1017-ebb0-43ad-a09c-337b500f645d.png)

**Additional context**

**Comment by bakuradzebakuradze** [comment]
Severity (MANDATORY): high

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.411. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The problem has been resolved, This issue is closed
