### ISSUE TITLE
ADM12 - Manage lab test and sample types for a disease 

### ISSUE THREAD

**Issue by Aj-Kakar** [EIDSS/EIDSS7#59]
**Summary**

Users should be able to sort or search he Lab test and samples types for a disease. 

**To Reproduce**
1. Log in as parkermason
2. Select Disease - Lab Test Matrix under the Configuration drop down.
3. Add in the the different disease - lab test
4. Review the Disease Lab Test matrix to confirm the tests were added, this is where the lab test results should have a sort functionality or search functionality. 

**Expected behavior**
user should be able to sort disease lab tests 

Screenshots**
![No sort or search](https://user-images.githubusercontent.com/52667376/60903598-9ea89b00-a23f-11e9-950e-ff2a11fd19e6.PNG)

**Issue severity**
Low

**Build**
79

**Comment by christhompson17** [comment]
This is a confirmed bug. All menu items should have sort functionality as a global feature. Additionally, we will be adding an enhancement requirement to include a search feature on these screens in Admin.
