### ISSUE TITLE
Notification, date of filling out the paper form - this field has remained from the time when it was mandatory to make the notification in paper form. Currently, this rule is abolished. In v7, the date of paper form completion - variable is not controlled by the date of diagnosis, which must be earlier than the date of paper form completion. Depending on the existing rules, the message in the tab, the date of filling out the paper form - can be completely removed.

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#592]
**Is your feature request related to a problem? Please describe.**
Notification, date of filling out the paper form - this field has remained from the time when it was mandatory to make the notification in paper form. Currently, this rule is abolished.
In v7, the date of paper form completion - variable is not controlled by the date of diagnosis, which must be earlier than the date of paper form completion. Depending on the existing rules, the message in the tab, the date of filling out the paper form - can be completely removed.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bakuradzebakuradze** [comment]
![image](https://user-images.githubusercontent.com/128576431/236430244-f7b14481-f9f0-4e4e-b1ba-d2efc9557298.png)

**Comment by herashchenkoa** [comment]
Based on the meeting with GG WG on February 26, 2024, it was agreed to hide 'Date of Completion of Paper form' field.

**Comment by bakuradzebakuradze** [comment]
The issue is closed
