### ISSUE TITLE
notification>Hospital Name - There are only a few hospitals in the variable dropdown menu. It is necessary to have the possibility to add hospitals

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#593]
**Is your feature request related to a problem? Please describe.**
notification>Hospital Name - There are only a few hospitals in the variable dropdown menu. It is necessary to have the possibility to add hospitals
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by herashchenkoa** [comment]
This issue will be addressed as part of the approved Change Control Board (CCB) №4 meeting on February 13, 2024, and will be included in the feature EIDSSv7 releases.

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.480. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
the issue is closed
