### ISSUE TITLE
Diagnosis: brucellosis caused by Brucella canis; Account ID HUMTBTBZ23HAPY

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#594]
**Is your feature request related to a problem? Please describe.**
see the screenshot   What is marked with a yellow marker should be moved to where the red line is drawn

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/128576431/236436328-4eca5f73-468b-43a4-bb7a-a8bebc62b7d0.png)

**Comment by aherashchenko** [comment]
Please see the updated screenshot. The issue is that the sentence is split into 2 different lines.

![236436328-4eca5f73-468b-43a4-bb7a-a8bebc62b7d0](https://github.com/EIDSS/EIDSS7/assets/127475545/5426f94d-75fc-4d96-9cda-88a129d20310)

**Comment by bakuradzebakuradze** [comment]
Questions in v6 are in this order, so should in v7
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/d8cd92b9-6feb-48c6-93a0-42db5046569e)

**Comment by bakuradzebakuradze** [comment]
Questionnaire questions are messed up, one sentence is "and at least one of the following:" completely missing from the list
Severity: low

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.411. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The issue was resolved, this issue is closed
