### ISSUE TITLE
In the samples, the employee details, personal ID type, and section drop-down menu are in English

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#595]
**Summary**
In the samples, the employee details, personal ID type, and section drop-down menu are in English
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: 
Build: 
Severity (MANDATORY): 

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/128576431/236436630-66ec8ebc-9a63-49f3-9024-73adf9994058.png)
![image](https://user-images.githubusercontent.com/128576431/236436662-f4097cee-f2c0-47bd-9262-b09a65f07720.png)

**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.411. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The problem has been resolved, This issue is closed
