### ISSUE TITLE
In the samples, taken by the employee, the drop-down menu opens unclear signs. I added a new employee, and the system replied that it remembered it, but then it couldn't be found.

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#596]
**Summary**
In the samples, taken by the employee, the drop-down menu opens unclear signs. I added a new employee, and the system replied that it remembered it, but then it couldn't be found.
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: 
Build: 
Severity (MANDATORY): 

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/128576431/236437122-3c573a45-81ef-4d5d-8a56-1151c16e89ca.png)

**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been tested using different scenarios and is not reproducible in EIDSS Release v7.0.427. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The issue is closed
