### ISSUE TITLE
The final outcome- the drop-down menu is in English

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#597]
**Summary**
The final outcome- the drop-down menu is in English

**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: 
Severity (MANDATORY): important

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/128576431/236437486-0362575e-88e3-4c71-8bd2-91dbcc5b0162.png)

**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been resolved in EIDSSv7 build 7.0.402. Please verify.

**Comment by bakuradzebakuradze** [comment]
The issue has been resolved
