### ISSUE TITLE
In the case of mumps - variable  "Non-Notifiable Diagnosis from Facility where patient first sought care" A list of notifiable diseases is opened, and it does not allow to record non-notifiable diseases (eg allergy, hypertension) in case of need.

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#598]
**Summary**
In the case of mumps - the variable  "Non-Notifiable Diagnosis from Facility where the patient first sought care" A list of notifiable diseases is opened, and it does not allow to record non-notifiable diseases (eg allergy, hypertension) in case of need.
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: 7.0.348.75
Severity (MANDATORY): medium

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/128576431/236479168-260f1087-cb96-4ab2-9931-d03845ef88d2.png)

**Additional context**

**Comment by bakuradzebakuradze** [comment]
Severity (MANDATORY): medium

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.480. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
the issue is closed
