### ISSUE TITLE
Human Disease Report> In the process of working in the Georgian version, when there is a certain problem and we want to check it in the English version and then return to the Georgian version, if the data recorded in the Georgian version was not saved before, it is deleted and the form is found empty, that is, we have to open the case again and record the data

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#600]
**Summary**
In the process of working in the Georgian version, when there is a certain problem and we want to check it in the English version and then return to the Georgian version if the data recorded in the Georgian version was not saved before, it is deleted and the form is found empty, that is, we have to open the case again and record the data
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: 
Severity (MANDATORY): important

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem.  Please blur or cover any personally identifiable information in any screenshots.

**Additional context**

**Comment by herashchenkoa** [comment]
This is expected behavior. When the language is changed or the page is refreshed, the data will be lost if it was not saved previously. Please save the data first before changing the language or refresh the page.

**Comment by bakuradzebakuradze** [comment]
The issue has been resolved
