### ISSUE TITLE
Report on Certain Diseases/Conditions (Monthly Form IV-03) The following graphs of the total are not visible. for example; Lab. tested, lab. Confirmed and Totally Confirmed (Lab. or Epid. Connection)

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#601]
**Summary**
Report on Certain Diseases/Conditions (Monthly Form IV-03) The following graphs of the total are not visible. for example; Lab. tested, lab. Confirmed and Totally Confirmed (Lab. or Epid. Connection)
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: 7.0.348.75
Severity (MANDATORY): Critical

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/128576431/236484494-3e8fe4b6-9d8a-4e39-b3e4-0ee690f2693b.png)

**Additional context**

**Comment by jkkannan** [comment]
The report in v6 does not have the columns described; these only exist in the Intermediate Monthly Report. 
![image](https://github.com/EIDSS/EIDSS7/assets/35157698/f2218eb9-c215-4490-bb9d-d365e56b71f1)

**Comment by bakuradzebakuradze** [comment]
The issue is resolved
