### ISSUE TITLE
Mumps-samples tab>Filter the sample by disease>The filter does not work and therefore the list of sample types shows all sample types and not the specific sample types provided for mumps laboratory research. (eg as presented in the case of measles)

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#604]
**Summary**
Mumps-samples tab>Filter the sample by disease>The filter does not work and therefore the list of sample types shows all sample types and not the specific sample types provided for mumps laboratory research. (eg as presented in the case of measles)
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: 
Severity (MANDATORY): Critical

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/128576431/236490764-f78f78ad-3548-4692-a82c-525a81a370ee.png)
![image](https://user-images.githubusercontent.com/128576431/236490808-ce7a252c-a1d0-4545-ae5d-2f48a48fc346.png)

**Additional context**

**Comment by aherashchenko** [comment]
Update based on the discussion with WG on May 10, 2023: The filter works as expected. The matrix will be customized via the Administrative module when required.

**Comment by jkkannan** [comment]
Closing based on WG feedback above.

**Comment by bakuradzebakuradze** [comment]
The issue is still open because it doesn't show anything anymore see the screenshot


![Image](https://github.com/EIDSS/EIDSS7/assets/128576431/d49952bb-ffda-4aee-8322-a728d43062a6)

**Comment by jkkannan** [comment]
It appears that Mumps does not have any samples associated with it from going to the menu item Administration > Reference Editors > Diseases and searching for mumps.  Sample types would need to be added there as part of configuration before they appear in this form.
