### ISSUE TITLE
human>person save problem>When saving the data it does not allow me to save

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#606]
**Summary**
human>person save problem When saving the data it does not allow me to save
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): Function
Username: bakuradze
Build: 7.0.348.75
Severity (MANDATORY): high

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/128576431/236829365-643fd079-37df-46c6-a5f9-5d4318edb194.png)

**Additional context**

**Comment by bakuradzebakuradze** [comment]
Severity (MANDATORY): high

**Comment by herashchenkoa** [comment]
The issue has been tested using different scenarios and is not reproducible in EIDSS Release v7.0.427. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The issue is closed
