### ISSUE TITLE
Human Disease Report>plague - bubonic >Clinical Information-Symptoms>Buboe characteristics> Questions are repeated

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#608]
**Summary**
Human Disease Report>plague - bubonic >Clinical Information-Symptoms>Buboe characteristics> Questions are repeated in both in English and Georgian

**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: 7.0.348.75
Severity (MANDATORY): important

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/6b90336f-1b86-4b32-8e4a-6ef66f7a8436)
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/0a24f2ac-c739-4870-a575-75d21221375f)

**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.411. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The problem has been resolved, This issue is closed
