### ISSUE TITLE
Human Disease Report>Plague septicemic>Clinical Information-Symptoms and List of Risk Factors Questions are messed up in v7 it should be as it is in v6

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#609]
**Summary**
Human Disease Report>Plague septicemic>Clinical Information-Symptoms and List of Risk Factors Questions are messed up in v7 it should be as it is in v6
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: 7.0.348.75
Severity (MANDATORY): 

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem.  Please blur or cover any personally identifiable information in any screenshots.

**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.411. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The problem has been resolved, This issue is closed
