### ISSUE TITLE
Employment/School When we fill in the region and district, it probably does not understand and still tells us that we have filled in the region and district and does not allow us to save

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#612]
**Summary**
Employment/School When we fill in the region and district, it probably does not understand and still tells us that we have filled in the region and district and does not allow us to save
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): Function
Username: bakuradze
Build: 
Severity (MANDATORY): important

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/f5bc6877-eb04-4403-bc81-14e0ba9119c6)
**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.427. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The issue is closed
