### ISSUE TITLE
plague pneumonic>Clinical Information-Symptoms Questionnaire>Case Investigation: Risk Factors are messed up 

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#614]
**Summary**
plague pneumonic>Clinical Information-Symptoms Questionnaire and Case Investigation: Risk Factors are messed up 
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): Function
Username: bakluradze
Build: 
Severity (MANDATORY): 

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/9ab7203a-d2e1-4d02-b97b-77630cf7c550)
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/031e21ef-15f6-4973-a35d-7e68fad96b50)

**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.411. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The problem has been resolved, This issue is closed
