### ISSUE TITLE
Freez after trying to add farmer

### ISSUE THREAD

**Issue by schegelidze** [EIDSS/EIDSS7#617]
**tr**
After trying to add farmer screen freezes

**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): Function
Username: chegelidze
Build: 7.0.349.21
Severity (MANDATORY): High

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. entering the veterinary sector
2. pressing farm
3. add farm
<img width="960" alt="Untitled" src="https://github.com/EIDSS/EIDSS7/assets/128593631/15590ac2-d49b-43f1-ad3c-3149a3494463">

4. checking avian farm
5. writing farm name
6. after trying to add new farm owner screen freezes
7. I cant  go forward or go back to the window
<img width="960" alt="Untitled" src="https://github.com/EIDSS/EIDSS7/assets/128593631/17755771-a7a9-4e99-b041-0baf73ad3230">

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem.  Please blur or cover any personally identifiable information in any screenshots.

**Additional context**

**Comment by bakuradzebakuradze** [comment]
Severity (MANDATORY): High

**Comment by schegelidze** [comment]
It is fixed
