### ISSUE TITLE
Add button is missing in Outbreak session

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#618]
**Summary**
Add button is missing in the Outbreak session
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): Function
Username: bakuradze
Build: 
Severity (MANDATORY): 

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
.
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/7c1bad71-a974-40be-82d8-911ec5be0b75)

**Additional context**

**Comment by herashchenkoa** [comment]
This issue is not reproducible. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
This issue is closed
