### ISSUE TITLE
A record of vector surveillance session with disease-->West Nile Virus fails to display after selecting the search criteria for status, vector type, disease, Region; the data entry field for Rayon was autopopulated. 

### ISSUE THREAD

**Issue by shahina77** [EIDSS/EIDSS7#62]
**Summary**
A record of vector surveillance session with disease-->West Nile Virus fails to display after selecting the search criteria for status, vector type, disease, Region; the data entry field for Rayon was autopopulated. 

**To Reproduce**
1. Log in as 
2. Go to 
3. Click on 

**Expected behavior**
A record of vector surveillance session with disease-->West Nile Virus should display after selecting the search criteria. 
Screenshots**

**Additional details:**
 - Build: 80
 - Script title (enter ad hoc if not script-based):

**Issue severity**
Severity (critical, major, minor, low):
Critical 
**Additional context**
VEC04
[VEC04.zip](https://github.com/EIDSS/EIDSS7/files/3373863/VEC04.zip)

**Comment by jkkannan** [comment]
This error of an autopopulated region/rayon that the user cannot change also occurs in ADMIN module.

**Comment by MaheshwarDeo** [comment]
The attached screen shots under "additional context" file VEC04 shows that user can select/change the auto populated region/rayon. I think the issue is search not returning data as expected by selected search criteria by user.
