### ISSUE TITLE
human person information field shows age 22 years, date of birth 08.08.2000 but When going to the add disease field, the age is changed as 23 years old, which is a mistake

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#623]
**Summary**
The human person information field shows age 22 years, date of birth 08.08.2000 but When going to the add disease field, the age is changed to 23 years old, which is a mistake
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: 
Severity (MANDATORY): 

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/f92b1c47-0ab6-47a6-83dd-0528f2a02314)
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/09f34ced-2f1b-4ef2-beca-7d48bab0b9d3)

**Additional context**

**Comment by bakuradzebakuradze** [comment]
I was unable to perform the same process, the issue remains open
Severity: medium

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.427. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The issue is closed
