### ISSUE TITLE
On the notification page, the name of the person receiving the notification is still in English and unclear fonts

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#624]
**Summary**
On the notification page, the name of the person receiving the notification is still in English and unclear fonts

**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): Function
Username: bakuradze
Build: 
Severity (MANDATORY): importent

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/83cb8a76-5af0-49fd-9260-50e18575f244)

**Additional context**

**Comment by jkkannan** [comment]
Names in English reflect how the name was initially entered. However, the unclear fonts are a bug and are in progress.

**Comment by herashchenkoa** [comment]
The issue has been resolved in EIDSSv7 build 7.0.402. Please verify.

**Comment by bakuradzebakuradze** [comment]
The issue has been resolved
