### ISSUE TITLE
We cant fill Farm Epi Information 

### ISSUE THREAD

**Issue by schegelidze** [EIDSS/EIDSS7#626]
**Summary**
when we are in Disease Report Summary (Farm Epi Information) we cant fill graphs for example, “Was any disease registered at the farm during the last 12 months?". When we click, we cannot select the desired option, it freezes. - Georgian language version.

**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc): 
If ad hoc, Category (Function, customization, , migration, integration) (optional): Function
Username: Chegelidze
Build: 7.0.349.21
Severity (MANDATORY): Hight
**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… Veterinary, Farm
2. Searching Any farm and go into Farm information
3. disease report, Add Avian
4. Farm epi information
5. And Choose Farm's disease history
<img width="960" alt="Untitled" src="https://github.com/EIDSS/EIDSS7/assets/128593631/90f24c03-b2df-48f9-a79e-82855202cc1f">

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem.  Please blur or cover any personally identifiable information in any screenshots.

**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been addressedd in EIDSS Release v7.0.411. Please verify to confirm that the issue was resolved.

**Comment by schegelidze** [comment]
It is fixed
