### ISSUE TITLE
ADM14 - Manage Vector Types

### ISSUE THREAD

**Issue by Aj-Kakar** [EIDSS/EIDSS7#63]
**Summary**
Missing drop down option for the test name Rickettsial-pox penside test.

**To Reproduce**
1. Log in as parkermason
2. Go to Vector Type - Field Test Matrix under configuration
3. Review step recorder  

**Expected behavior**
User should be able to select the test name Rickettsial-pox penside test.

**Screenshots**
[Missing drop down-rickettsial-pox penside test.zip](https://github.com/EIDSS/EIDSS7/files/3373921/Missing.drop.down-rickettsial-pox.penside.test.zip)

**Issue severity**
Minor

**Build**
80

**Comment by christhompson17** [comment]
Need to confirm that Rickettsial-pox penside is in the DB, if not this is not a bug and is a GAT data issue.
