### ISSUE TITLE
yellow fever>List of Risk Factors>The order of the questions is messed up 

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#631]
**Summary**
yellow fever>List of Risk Factors>The order of the questions is messed up 

**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze 
Build: 
Severity (MANDATORY): 

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/3bb0a234-baee-4977-833f-b3d8359f663f)
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/30a0a3af-b12d-45d8-8d85-26542aa13c6a)

**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.411. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The problem has been resolved, This issue is closed
