### ISSUE TITLE
I have moved the case that I had uploaded in March and was closed back into the process. I tried to add the information in the clinical and risk factor variables tab and it won't allow it

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#634]
**Summary**
I have moved the case that I had uploaded in March and was closed back into the process. I tried to add the information in the clinical and risk factor variables tab and it won't allow it
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc): 
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: 
Severity (MANDATORY): 

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem.  Please blur or cover any personally identifiable information in any screenshots.

**Additional context**

**Comment by herashchenkoa** [comment]
In order to make changes in the Human Disease Report, it shall be opened in the edit mode. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The problem has been resolved, This issue is closed
