### ISSUE TITLE
any human case > outcome are not translated see the screenshot 

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#637]
**Summary**
any human case > outcome are not translated see the screenshot 
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: 
Severity (MANDATORY): important

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/b1d7b9db-7a74-44d3-9e4b-6a6b93d618cd)

**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been resolved in EIDSSv7 build 7.0.402. Please verify.

**Comment by bakuradzebakuradze** [comment]
The issue has been resolved
