### ISSUE TITLE
Cholera risk factors questions in V7 are out of order, should be as in V6

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#638]
**Summary**
Cholera risk factors questions in V7 are out of order, should be as in V6

**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: 
Severity (MANDATORY): 

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/effb9764-f934-48ff-a2de-c98f665bfea7)
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/8e22713e-f0d0-4033-ac27-7ad0acf62537)

**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.411. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The problem has been resolved, But in version 7 we don't have  "add parameter" in "case classification" which we have in version 6 see screenshots 
![Capture (1)](https://github.com/EIDSS/EIDSS7/assets/128576431/c71d0ffb-0a86-4085-9c29-92198e3d9303)

**Comment by bakuradzebakuradze** [comment]
<img width="930" alt="Screenshot 2023-12-26 144722" src="https://github.com/EIDSS/EIDSS7/assets/128576431/c3c72c17-70a0-4bca-a5b4-fb42b5acc319">

**Comment by herashchenkoa** [comment]
Based on the user's feedback, the bug described in this issue is resolved. Thus, this bug will be closed. 
For the issue related to missing "add parameter" in "case classification" which is present in version 6 a new issue is opened #885.
