### ISSUE TITLE
final outcome>outcome is in English

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#639]
**Summary**
final outcome>outcome is in English

**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: 
Build: 
Severity (MANDATORY): 

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/5f758305-2ade-42a0-b9b1-30d780a4f83f)

**Additional context**

**Comment by jkkannan** [comment]
Duplicate of #637

**Comment by herashchenkoa** [comment]
The issue has been resolved in EIDSSv7 build 7.0.402. Please verify.

**Comment by bakuradzebakuradze** [comment]
The issue has been resolved
