### ISSUE TITLE
VPS01 search for livestock disease report issue

### ISSUE THREAD

**Issue by jeanmrichards** [EIDSS/EIDSS7#64]
**Summary**
Script says to search using given criteria and it doesn't result in any records. When you go to edit the criteria and change brucellosis to brucellosis abortus you cant search again. you have the option only to cancel and start the search over and input all the data again. should be able to search again with corrected fields in the same page

**To Reproduce**
1. Log in as ryan johnson
see attached

**Expected behavior**
find record in the search with the script info, or be able to search again without starting over after correcting search criteria

**Screenshots**
see attached

**Additional details:**
 - Build: 79.0
 - Script title (enter ad hoc if not script-based): VPS01

**Issue severity**
Severity (critical, major, minor, low): minor
[VPS01 livestock disease report search issue.zip](https://github.com/EIDSS/EIDSS7/files/3373918/VPS01.livestock.disease.report.search.issue.zip)

**Additional context**

**Comment by jkkannan** [comment]
Should be two issues.
1) Script issue; should not reference brucellosis.
2) Bug on search; should not force user to cancel and go back.  Should maintain a search button on the screen after the first search.
