### ISSUE TITLE
final outcome> When the epidemiologist's name is dropped, hieroglyphs are visible

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#640]
**Summary**
final outcome> When the epidemiologist's name is dropped, hieroglyphs are visible
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: 
Build: 
Severity (MANDATORY): 

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/a6b3eaa9-6d72-46b4-a613-ebf87810897d)

**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been resolved in EIDSSv7 build 7.0.402. Please verify.

**Comment by bakuradzebakuradze** [comment]
The issue has been resolved
