### ISSUE TITLE
EIDSS v7_GG lang - Label “Permanent Address” is not translated on Person Window Address tab

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#641]
**Summary**
EIDSS v7_GG lang - Label “Permanent Address” is not translated on the Person Window Address tab

**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: 
Build: 7.0 .354.12
Severity (MANDATORY): 

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/3d312764-20ec-493d-8e87-4f30b5f10a2e)

**Additional context**

**Comment by jkkannan** [comment]
![image](https://github.com/EIDSS/EIDSS7/assets/35157698/67d49a0a-8e64-46c3-bf27-183390bbc442)

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.411. Translation applied based on the duplicate with #506 . Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The problem has been resolved, This issue is closed
