### ISSUE TITLE
GG lang_School Name and Employer Name field is not displayed text with GG symbols on Person Window – School tab

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#643]
**Summary**
GG lang_School Name and Employer Name field is not displayed text with GG symbols on Person Window – School tab

**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: 
Build: 7.0.354.12
Severity (MANDATORY): 

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/97d94ee8-c09e-4241-8a88-865b9d000afd)

**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been resolved in EIDSSv7 build 7.0.402. Please verify.

**Comment by bakuradzebakuradze** [comment]
The issue has been resolved
