### ISSUE TITLE
Initial Case Classification field is not marked with red asterisk on HDR – Clinical Information – Symptoms tab

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#644]
**Summary**
Initial Case Classification field is not marked with red asterisk on HDR – Clinical Information – Symptoms tab

**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: 
Build: 7.0.354.12
Severity (MANDATORY): 

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/8b974c69-9085-4add-828a-8d41eb19bdaf)

**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been resolved in EIDSSv7 build 7.0.402. Please verify.

**Comment by bakuradzebakuradze** [comment]
The issue has been resolved
