### ISSUE TITLE
GG lang When HDR – Notification tab, then Date of Diagnosis field Date is not saved after Save and click on Dashboard

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#645]
**Summary**
GG lang When HDR – Notification tab, then Date of Diagnosis field Date is not saved after Save and click on Dashboard
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: 
Build: 7.0.354.12
Severity (MANDATORY): 

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/72af069b-4575-48fc-9fe2-693920f4b400)

**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been tested using different scenarios and is not reproducible in EIDSS Release v7.0.427. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The issue is closed
