### ISSUE TITLE
GG lang Default value choose Not by default on Clinical Information: Facility Details section

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#646]
**Summary**
GG lang Default value choose Not by default on Clinical Information: Facility Details section

**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: 
Build: 7.0.354.12
Severity (MANDATORY): 

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/a3ef9811-b7d7-414d-b5db-cacb07ecc11c)

**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.480. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
the issue is closed
