### ISSUE TITLE
GG lang HDR- Clinical Information-Facility tab Details, then “Non-Notifiable Diagnosis from Facility where patient first sought care” field is incorrectly translated, this should be used from v.6

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#647]
**Summary**
GG lang HDR- Clinical Information-Facility tab Details, then “Non-Notifiable Diagnosis from Facility where the patient first sought care” field is incorrectly translated, this should be used from v.6
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: 
Build: 7.0.354.12
Severity (MANDATORY): 

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/ef2429b8-29d9-4d23-8951-3b64a5eb6657)
**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been resolved in EIDSSv7 build 7.0.402. Please verify.

**Comment by bakuradzebakuradze** [comment]
The issue has been resolved
