### ISSUE TITLE
HDR - Antibiotic/Antiviral History tab then “Antibiotic/ Antiviral therapy administered?” and “Was specific vaccination administered?” fields are not saved NO value

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#648]
**Summary**
HDR - Antibiotic/Antiviral History tab then “Antibiotic/ Antiviral therapy administered?” and “Was specific vaccination administered?” fields are not saved NO value
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: 
Build: 7.0.354.12
Severity (MANDATORY): 

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/f51726db-4efd-40d3-9672-feb3159002c6)

**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.480. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
the issue is closed
