### ISSUE TITLE
HDR is not saved when HDR - Case Investigation: Risk Factors tab then any fields on FF template with date values AND choose date with day more then 12 AND [Save].

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#649]
**Summary**
HDR is not saved when HDR - Case Investigation: Risk Factors tab then any fields on FF template with date values AND choose a date with day more than 12 AND [Save].
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: 
Build: 7.0.354.12
Severity (MANDATORY): 

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/6d0d6095-440c-4b6a-b04b-e14a6bfe84f1)

**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.411. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The problem has been resolved, This issue is closed
