### ISSUE TITLE
Employment/School>translation should be  "სამუშაო ადგილი/სასწავლო დაწესებულება" 

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#652]
**Summary**
Employment/School>translation should be  "სამუშაო ადგილი/სასწავლო დაწესებულება" 

**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: 
Severity (MANDATORY): minor

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/c0ae957f-651d-4555-a84b-7dfaa4f5860a)

**Additional context**

**Comment by bakuradzebakuradze** [comment]
same as it was before, the issue is not resolved   Severity: Low

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.411. Please verify to confirm that the issue was resolved.
Duplicate with #510

**Comment by bakuradzebakuradze** [comment]
The problem has been resolved, This issue is closed
