### ISSUE TITLE
Person>Employment/School> Does the Person currently attend school> translation should be ეს პირი ამჟამად დადის სასწავლო და ან სკოლამდელ დაწესებულებაში

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#653]
**Summary**
Person>Employment/School> Does the Person currently attend school> translation should be "ეს პირი ამჟამად დადის სასწავლო და ან სკოლამდელ დაწესებულებაში"
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: 
Severity (MANDATORY): minor

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/8da19b20-b35d-4c56-8078-38c9a9f2fad1)

**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.411. Translation applied based on the duplicate with #511. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The translation has been corrected but not as we indicated
<img width="916" alt="Screenshot 2023-12-21 193000" src="https://github.com/EIDSS/EIDSS7/assets/128576431/3823227d-c17a-41ba-b9f0-b11bac84f1cf">

**Comment by bakuradzebakuradze** [comment]
The problem has been resolved, This issue is closed
