### ISSUE TITLE
Person>Employment/School>School Name>translation should be "სასწავლო და ან სკოლამდელი დაწესებულების სახელწოდება"

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#654]
**Summary**
Person>Employment/School>School Name>translation should be "სასწავლო და ან სკოლამდელი დაწესებულების სახელწოდება"
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: 
Build: 
Severity (MANDATORY): minor

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/0bafa6ca-db12-4cfd-9326-d1cc320a17f5)

**Additional context**

**Comment by bakuradzebakuradze** [comment]
same as it was before, the issue is not resolved   Severity: Low

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.411. Translation applied based on the duplicate with #512 . Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The translation has been corrected but not as we indicated

**Comment by bakuradzebakuradze** [comment]
The problem has been resolved, This issue is closed
