### ISSUE TITLE
new disease case/notification>when entering data we were saving it step by step when reviewing it does not remember the Date of diagnosis

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#656]
**Summary**
new disease case/notification> when entering data we were saving it step by step when reviewing it does not remember the Date of diagnosis
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: 
Build: 
Severity (MANDATORY): major

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/54113c43-40f6-4cc0-824c-ef0b8c1a944a)

**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.480. Please verify to confirm that the issue was resolved.
