### ISSUE TITLE
VPS01

### ISSUE THREAD

**Issue by jeanmrichards** [EIDSS/EIDSS7#66]
**Summary**
after entering new livestock disease report the script says to click "return to dashboard" and expected result is to see epizootologist dashboard but i see "unaccessioned samples" list

**To Reproduce**
1. Log in as ryan johnson 
2. Go to follow steps to create the new livestock disease record and enter all the herd info as per script, then
3. Click on return to dashboard

**Expected behavior**
epizootologist dashboard

**Screenshots**
would have to create new record and not sure if that will impact script...?
**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based):

**Issue severity**
Severity (critical, major, minor, low): low or minor?

**Additional context**

**Comment by jkkannan** [comment]
Seems to be a permissions issue.  Occured elsewhere as well.
