### ISSUE TITLE
2.	 Person form – Change place of fields: Phone Type should be located before Country Code and Number on other phone section on Person form – Address tab

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#665]
**Is your feature request related to a problem? Please describe.**
2.	 Person form – Change place of fields: Phone Type should be located before Country Code and Number on other phone section on Person form – Address tab
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/0a09cddb-5de1-4f65-be72-de56985bca84)

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.480. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
the issue is closed
