### ISSUE TITLE
Change label on EN and GG lang – Label of field “Country Code and Number” recommended change to “Country Code and Phone Number”

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#667]
**Is your feature request related to a problem? Please describe.**
Change label on EN and GG lang – Label of field “Country Code and Number” recommended change to “Country Code and Phone Number”
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/d43f9c23-d62b-4e08-aaea-b56e5891f2cd)

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.480. Please verify to confirm that the issue was resolved.
