### ISSUE TITLE
Human Disease Report

### ISSUE THREAD

**Issue by srbatni** [EIDSS/EIDSS7#67]
**Summary**
The region and rayon in the human disease report screen was NOT prepopulated

**To Reproduce**
1. Log in as: Russell Peters 
2. Go to: Human Disease Report 
3. Click on: Main screen 

**Expected behavior**
Region and Rayon fields would be prepopulated.

**Screenshots**

**Additional details:**
 - Build: v7 80.0
 - Script title (enter ad hoc if not script-based): HPS04

**Issue severity**
Severity (critical, major, minor, low): Low

**Additional context**

**Comment by jkkannan** [comment]
duplicate of #13

**Comment by jkkannan** [comment]
Closing out because duplicate
