### ISSUE TITLE
HDR Advanced Search System, then Received by Facility field should include only sites

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#677]
**Summary**
HDR Advanced Search System, then Received by Facility field should include only sites
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: 
Build: 
Severity (MANDATORY): major

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/ba3dd704-54eb-407f-9c27-b56b526572ff)
**Additional context**

**Comment by herashchenkoa** [comment]
The bug fix was addressed in EIDSSv7 build 7.0.402.
