### ISSUE TITLE
HDR – Case Investigation: Details, the fields “Investigation Organization”, Start Date of Investigation are not saved values

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#679]
**Summary**
HDR – Case Investigation: Details, the fields “Investigation Organization”, Start Date of Investigation are not saved values
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: 
Build: 
Severity (MANDATORY): major

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/d337e01c-98d1-48bf-bc87-6390a0a83cd6)
**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.480. Please verify to confirm that the issue was resolved.
