### ISSUE TITLE
VPS02 farm owner name search

### ISSUE THREAD

**Issue by jeanmrichards** [EIDSS/EIDSS7#68]
**Summary**
Script says the region and rayon fields should be filled with stated names but they are blank

**To Reproduce**
1. Log in as dennis roberts
2. click search button next to farm owner name
see attached

**Expected behavior**
see summary

**Screenshots**
see attached

**Additional details:**
 - Build: 79.0
 - Script title (enter ad hoc if not script-based):

**Issue severity**
Severity (critical, major, minor, low): low
[VPS02 farm owner name search.zip](https://github.com/EIDSS/EIDSS7/files/3374177/VPS02.farm.owner.name.search.zip)

**Additional context**

**Comment by jkkannan** [comment]
Seems like permissions issue, similar to others.
