### ISSUE TITLE
HDR – Case Investigation: Details, the field “Investigation Organization” Value is change possible after the case is closed

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#680]
**Summary**
HDR – Case Investigation: Details, the field “Investigation Organization” Value is change possible after the case is closed
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: 
Build: 
Severity (MANDATORY): medium

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/443d66c9-bddb-40ea-a065-2a484e0a0603)
**Additional context**

**Comment by bakuradzebakuradze** [comment]
Severity (MANDATORY): medium

**Comment by bakuradzebakuradze** [comment]
The issue remains open

**Comment by TulendinovT** [comment]
It is relevant on GG lang

**Comment by bakuradzebakuradze** [comment]
The issue is closed
