### ISSUE TITLE
Human Report – All reports  which have been Language field. After the change language in this field system change language for all fields on the form

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#682]
**Summary**
Human Report – All reports which have been Language field. After the change language in this field, system change the language for all fields on the form
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: 
Build: 
Severity (MANDATORY): high

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/623d8463-94ef-44fe-97b7-2b8bc527e642)

**Additional context**

**Comment by bakuradzebakuradze** [comment]
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/118e5ede-05e8-4e85-9675-39b65a103ced)

**Comment by bakuradzebakuradze** [comment]
Severity (MANDATORY): high

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.411. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The problem has been resolved, This issue is closed
