### ISSUE TITLE
Human Report – “Comparative Report of several years by month”, the Name of report is not include diagnosis in GG language

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#683]
**Summary**
Human Report – “Comparative Report of several years by month”, the Name of the report does not include the diagnosis in GG language
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: 
Build: 
Severity (MANDATORY): medium

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/ffeb1899-4b01-4b69-8c1d-c48a638442ed)

**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.411. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The problem has been resolved, This issue is closed
