### ISSUE TITLE
Human Report - Concordance between Initial and Final Diagnosis, if choose more diagnosis in the fields “Initial Diagnosis” and “Final Diagnosis” system displayed error

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#684]
**Summary**
Human Report - Concordance between Initial and Final Diagnosis, if choose more diagnoses in the fields “Initial Diagnosis” and “Final Diagnosis” the system displayed an error
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: team
Build: 
Severity (MANDATORY): high

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/84f0c2b0-57b9-4527-9706-283288cdc76b)

**Additional context**

**Comment by bakuradzebakuradze** [comment]
Severity (MANDATORY): high

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.411. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The problem has been resolved, This issue is closed
