### ISSUE TITLE
Final Outcome

### ISSUE THREAD

**Issue by srbatni** [EIDSS/EIDSS7#69]
**Summary**
I clicked on the final outcome link in the Navigation Box and tried to select the drop down for Final Case Classification; however, the screen had a red circle that would not allow me to select a drop down choice to select not a case.

**To Reproduce**
1. Log in as: Russell Peters 
2. Go to: Human Disease Report 
3. Click on: Final Outcome link

**Expected behavior**
The drop down menu for final case classification should have allowed me to select not a case.

**Screenshots**

**Additional details:**
 - Build: v7 80.0
 - Script title (enter ad hoc if not script-based): HPS04

**Issue severity**
Severity (critical, major, minor, low): Major

**Additional context**

**Comment by jkkannan** [comment]
Need to confirm whether this might actually be a permissions issue.
