### ISSUE TITLE
The error occurs when the form opens too long, during time out

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#712]
**Summary**
The error occurs when the form opens too long, during time out
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: 
Build: 
Severity (MANDATORY): high

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/40023672-8feb-4d47-be8d-ae92c87ede14)
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/b250c95d-4df3-4ad3-81cc-b2dc045fc1c5)

**Additional context**

**Comment by bakuradzebakuradze** [comment]
Severity (MANDATORY): high

**Comment by schegelidze** [comment]
It is fixed

**Comment by herashchenkoa** [comment]
Closing the bug as fixed based on the user's feedback.
