### ISSUE TITLE
AVR 2018 Botulismdiseases in imereti query failed to retain filter conditions in the root and child object.

### ISSUE THREAD

**Issue by shahina77** [EIDSS/EIDSS7#74]
**Summary**
2018 Botulismdiseases in imereti query failed to retain filter conditions in the root and child object. 

**To Reproduce**
1. Log in as 
2. Go to 
3. Click on 

**Expected behavior**
2018 Botulismdiseases in imereti query should  retain filter conditions in the root and child object   

**Screenshots**

**Additional details:**
 - Build: 80
 - Script title (enter ad hoc if not script-based):

**Issue severity**
Severity (critical, major, minor, low):
Minor
**Additional context**
AVR03
![AVR03](https://user-images.githubusercontent.com/52667472/60911627-9ce7d300-a251-11e9-9ac1-82c1bf088610.png)

**Comment by Aj-Kakar** [comment]
Comment by Anatoliy using AJ's account (to retain AJ GH page):
Cannot replicate this defect on the DTRA6 machine. The AVR application is correctly saving query filtration statements. 
[AVR-query_filter-conditions.zip](https://github.com/EIDSS/EIDSS7/files/3386984/AVR-query_filter-conditions.zip)

Recommend to close this item.
