### ISSUE TITLE
One HC from v6 .1 -> migrated into 3 HDR to v7 (HGEWEB0021C56R)

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#744]
**Summary**
One HC from v6 .1 -> migrated into 3 HDR to v7 (HGEWEB0021C56R)
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: team
Build: 
Severity (MANDATORY): High

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/760d43c6-65c5-46ce-9d36-7051036a6456)
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/3500ce5b-a8bb-4cef-86c2-e5c1c83c28cc)
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/027678e8-134e-4b5b-88ea-b62f966eaef5)
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/5dcfd085-a66f-4bf0-86f2-f39010d8ee58)

**Additional context**

**Comment by bakuradzebakuradze** [comment]
The issue has not been resolved in EIDSSv7 build 7.0.402 
Severity: High

**Comment by herashchenkoa** [comment]
This is expected behavior. Based on the Data Migration rules, one Human Case from v6.1  will be migrated to the X amount of Human Disease Reports in EIDSSv7 based on the 'Changed Diagnoses' field. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The issue was resolved, this issue is closed
