### ISSUE TITLE
FF: Meningitis due to S. pneumonia -> The string is too long for the marked fields

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#746]
**Summary**
FF: Meningitis due to S. pneumonia -> The string is too long for the marked fields

**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: team
Build: 
Severity (MANDATORY): minor

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/71102557-19ad-4d4a-905a-d7b3ec1a69e3)

**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.411. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The problem has been resolved, This issue is closed
