### ISSUE TITLE
FF are not migrated correctly.

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#747]
**Summary**
FF are not migrated correctly.  
Example: 
Poxvirus diseases – Clinical Signs 
Yellow fever – Risk Factors
Anthrax – Clinical Signs 
Anthrax – Risk Factors
Salmonella spp - Risk Factors
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: 
Build: 
Severity (MANDATORY): major

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
Example: 
Poxvirus diseases – Clinical Signs 
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/14908319-229e-4df5-aa40-1e45c29778c7)
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/f86ea019-6494-44a9-ab31-486cda497bf2)
Yellow fever – Risk Factors
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/ba8493c1-772a-47e8-b802-24ee3a933993)
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/dbc25055-2a52-4c06-bd0c-df476aabcd4d)
Anthrax – Clinical Signs
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/317a74b5-7c1f-42e2-aac4-b009dbb5f67b)
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/6244a2a0-f16d-4a2d-901e-7668b52ae80f)
Anthrax – Risk Factors
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/5a381587-f270-47ab-8dae-a79993b0201d)
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/3da354bb-83e5-4bb2-aa4c-3c2311c38fc4)
Salmonella spp - Risk Factors
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/f15d4195-e1b3-4e10-a654-a5cf9680f247)
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/18f63ed5-9977-4da7-8624-0d1db7edca7e)

**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.411. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The problem has been resolved, This issue is closed
