### ISSUE TITLE
New notifiable disease report

### ISSUE THREAD

**Issue by srbatni** [EIDSS/EIDSS7#75]
**Summary**
When looking at the new notifiable disease report, the "Initial Case Classification" read suspect but should be blank.

**To Reproduce**
1. Log in as: Russell Peters 
2. Go to: Human Disease Report 
3. Click on: New notifiable disease report 

**Expected behavior**
The "Initial Case Classification" field should be blank.

**Screenshots**
![image](https://user-images.githubusercontent.com/52708365/60912139-8e8dbd00-a239-11e9-992a-7a49924e7773.png)

**Additional details:**
 - Build: v7 80.0
 - Script title (enter ad hoc if not script-based): HPS04

**Issue severity**
Severity (critical, major, minor, low): Low

**Additional context**

**Comment by jkkannan** [comment]
Need to verify requirement and whether Initial Case Classification should default to suspect.
