### ISSUE TITLE
v7 allows us to record and remember the identity even if "unknown" is selected, in v6 the input field was not active

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#753]
**Summary**
v7 allows us to record and remember the identity even if "unknown" is selected, in v6 the input field was not active
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: Maka Tsilosani 
Build: 
Severity (MANDATORY): medium

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/3150663d-0249-47d9-9ef7-2f902a8a594c)

**Additional context**

**Comment by bakuradzebakuradze** [comment]
Severity (MANDATORY): medium

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.427. Please verify to confirm that the issue was resolved.
