### ISSUE TITLE
The system should allow searching for a case even without a person's ID

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#756]
**Summary**
The system should allow searching for a case even without a person's ID
For example: by last name and/or other data, because you may not always know the identity of the person you are looking for or the wrong identity was entered when creating the case. In addition, it is important to know in advance whether "personal number" or "unknown" was selected in the field "Personal ID type" when creating a case, because the search depends on the information entered in this field.   For example: patients: Gotsiridze Gulkan and Gotsiridze Madonna (with different diagnoses) are registered in the system. When performing a search, without specifying a personal ID, in the following order: "Person" - "Search Criteria" - "Last Name" - Gotsiridze - "Search Results" 4 patients are searched for, and among them neither Gotsiridze Gukan nor Gotsiridze Madonna. When searching for the patient's name or father's name - David, both patients are visible. In addition, if it is necessary to specify the identity or "unknown" in the personal ID field to search for a person, the system should not search for the 4 patients with the last name - Gotsiridze (especially since one has a personal ID and three do not).
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: 
Build: 
Severity (MANDATORY): major

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/eb1b73b2-2744-4b57-b902-d24ecae53c2e)
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/65b0d6fd-d844-4c1d-b5ca-15bf287a3063)

**Additional context**

**Comment by herashchenkoa** [comment]
It is possible to search for a Human Disease Report by different criteria. Depending on the selected criteria system will show the results accordingly. Please verify to confirm that the issue is resolved.

**Comment by bakuradzebakuradze** [comment]
This issue is closed
