### ISSUE TITLE
In the field - "Current location of the patient" select "hospital", in the field for choosing the name of the hospital - "Hospital name" the list of clinics is not complete (there are only a few clinic names).

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#757]
**Summary**
In the field - "Current location of the patient" select "hospital", in the field for choosing the name of the hospital - "Hospital name" the list of clinics is not complete (there are only a few clinic names).
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: Maka tsilosani
Build: 
Severity (MANDATORY): minor

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/7c5fe8bf-4f05-45cc-aedd-c6bc93e5bf5b)

**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.480. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
the issue is closed
