### ISSUE TITLE
There are pre-marked answers in the system, for example: in the field - "The patient has already sought medical help with the same symptoms" the answer - "No", and in the field "Hospitalization" the answer - "No" are pre-marked, which can cause errors when entering information (all fields must be empty).

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#758]
**Summary**
There are pre-marked answers in the system, for example: in the field - "The patient has already sought medical help with the same symptoms" the answer - "No", and in the field "Hospitalization" the answer - "No" are pre-marked, which can cause errors when entering information (all fields must be empty).
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: maka tsilosani
Build: 
Severity (MANDATORY): Minor

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/57cf2e73-701d-46e0-a476-13437b9ce7ae)
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/5d048337-5613-4f3a-bea8-efc6d856e82f)

**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.480. Please verify to confirm that the issue was resolved.
