### ISSUE TITLE
VPS03 add new disease report can't enter new data in required fields as david robbins

### ISSUE THREAD

**Issue by jeanmrichards** [EIDSS/EIDSS7#76]
**Summary**
david robbins doesnt have permissions to modify case classification, report type, disease, or date of dx; works as dennis roberts

**To Reproduce**
1. Log in as david robbins
2. find big leghorn farm
3. add new disease report
4. try to edit the fields listed above - there is a red symbol and not possible to edit

**Expected behavior**

**Screenshots**

**Additional details:**
 - Build: 79.0
 - Script title (enter ad hoc if not script-based): VPS03

**Issue severity**
Severity (critical, major, minor, low): major

**Additional context**

**Comment by jkkannan** [comment]
Might be permissions issue; need to check.
