### ISSUE TITLE
When creating one of the tetanus cases, the risk factor questionnaire was relevant to another disease and the fields remembered the information entered during the previous tetanus case creation, however these tetanus cases were ultimately not remembered by the system (for an unknown reason) and are currently not searchable (although we have saved the image photographed).

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#761]
**Summary**
When creating one of the tetanus cases, the risk factor questionnaire was relevant to another disease and the fields remembered the information entered during the previous tetanus case creation, however, these tetanus cases were ultimately not remembered by the system (for an unknown reason) and are currently not searchable (although we have saved the image photographed).
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: Maka tsilosani
Build: 
Severity (MANDATORY): critical

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/2a2f081d-8a26-4097-ad89-44017e349935)

**Additional context**

**Comment by herashchenkoa** [comment]
The bug fix was addressed in EIDSSv7 build 7.0.402.

**Comment by bakuradzebakuradze** [comment]
The migration was successful. but the order of the questionnaire is not compatible with version 6
Severity: medium

**Comment by bakuradzebakuradze** [comment]
The issue is closed
