### ISSUE TITLE
Entering the initial classification of the case, as can be seen from the picture, was mandatory, although it was not marked with * (only when saving the data, the system informed you that it was mandatory to fill in this field), and without filling it, the case should not be remembered as a rule, although the case entered by me and by the system In the two remembered cases: "Influenza-like illness" and "Brucellosis", the "Case Classification" fields appear as blank (as if they were not filled in and still remembered) (see image).

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#762]
**Summary**
Entering the initial classification of the case, as can be seen from the picture, was mandatory, although it was not marked with * (only when saving the data, the system informed you that it was mandatory to fill in this field), and without filling it, the case should not be remembered as a rule, although the case entered by me and by the system In the two remembered cases: "Influenza-like illness" and "Brucellosis", the "Case Classification" fields appear as blank (as if they were not filled in and still remembered) (see image).
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: Maka tsilosani
Build: 
Severity (MANDATORY): major

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/8ed14b4b-1b64-4ba1-a405-c3a7b1b2d0b4)
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/8cc4b690-daf4-45ee-9fe0-db804bb68a4b)

**Additional context**

**Comment by herashchenkoa** [comment]
The bug fix was addressed in EIDSSv7 build 7.0.402.

**Comment by bakuradzebakuradze** [comment]
The issue has been resolved
