### ISSUE TITLE
It can be seen from the two images that the questions about risk factors in the case form of Gotsiridze Gulkani's "flu-like disease" are inappropriate for this disease.

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#764]
**Summary**
It can be seen from the two images that the questions about risk factors in the case form of Gotsiridze Gulkani's "flu-like disease" are inappropriate for this disease.
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: maka tsilosani
Build: 
Severity (MANDATORY): critical

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/838e329d-4921-4004-afca-8d6427454109)
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/7c3b377e-938a-4265-a180-03921d4a9db4)

**Additional context**

**Comment by bakuradzebakuradze** [comment]
The issue is not resolved
Severity : medium

**Comment by bakuradzebakuradze** [comment]
The issue is not resolved
Severity : medium

**Comment by bakuradzebakuradze** [comment]
This applies to "ILI-SARI" cases where we want "ILI-SARI" to be a separate module like in version 6

**Comment by herashchenkoa** [comment]
This issue was approved during the Change Control Board (CCB) #3 meeting on October 10, 2023, and will be included in the feature EIDSSv7 releases.
