### ISSUE TITLE
The name of the field - "Epidemiologist's name" should be "Epidemiologist's name and surname"; In addition, in the "Epidemiologist's name" selection list, along with the epidemiologists' names and surnames, there are unclear inscriptions/hieroglyphs (see picture) and some epidemiologists' names and surnames are written in Georgian, some in English (see picture).

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#765]
**Summary**
The name of the field - "Epidemiologist's name" should be "Epidemiologist's name and surname"; In addition, in the "Epidemiologist's name" selection list, along with the epidemiologists' names and surnames, there are unclear inscriptions/hieroglyphs (see picture) and some epidemiologists' names and surnames are written in Georgian, some in English (see picture).
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: maka tsilosani
Build: 
Severity (MANDATORY): minor

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/402abe61-dfc0-40a0-9d8b-4fb5384ab650)
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/774573e1-461c-4a41-a9d5-6b595475cfaf)

**Additional context**

**Comment by herashchenkoa** [comment]
The bug fix was addressed in EIDSSv7 build 7.0.402.

**Comment by bakuradzebakuradze** [comment]
By the decision of the group, this issue is closed
