### ISSUE TITLE
In the previous version, the dates in the search field were set to automatically search for the last 1 month of data, now this period is reduced to 2 weeks (we think it is better to return to 1 month).

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#769]
**Summary**
In the previous version, the dates in the search field were set to automatically search for the last 1 month of data, now this period is reduced to 2 weeks (we think it is better to return to 1 month).

**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: Maka tsilosani
Build: 
Severity (MANDATORY): minor

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem.  Please blur or cover any personally identifiable information in any screenshots.

**Additional context**

**Comment by bakuradzebakuradze** [comment]
Please explain or give the steps on How to change the dates and/or who should change them.

**Comment by herashchenkoa** [comment]
Please navigate to Administration -> System Preferences -> Number of days for which data is displayed by default. In the filed 'Number of days for which data is displayed by default' put number of days that you want to see data e.g 31 which equals to 1 month. lease verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
the issue was resolved
