### ISSUE TITLE
The next 3 pictures belong to the patient - Gotsiridze Gulkani, where it can be seen that in this person's form, the service address indicates the region - Imereti and the district - Baghdati, and when opening disease cases, these mandatory fields for the region and district are empty

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#773]
**Summary**
The next 3 pictures belong to the patient - Gotsiridze Gulkani, where it can be seen that in this person's form, the service address indicates the region - Imereti and the district - Baghdati, and when opening disease cases, these mandatory fields for the region and district are empty
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: 
Build: 
Severity (MANDATORY): major

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/edfa03b3-1dc9-47af-8e8c-3ee9df543a4f)
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/a8e67d07-21d1-4dd5-b811-a1d3b56f08ab)
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/87672df9-9c97-458c-8bb0-82b95193bafd)

**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.480. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
I could not find this case the issue is closed
