### ISSUE TITLE
The comment box on the final output tab should be larger so that the entered information can be seen in full

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#775]
**Summary**
The comment box on the final output tab should be larger so that the entered information can be seen in full
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: Maka tsilosani
Build: 
Severity (MANDATORY): major

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/0d317f22-099f-486a-8bab-16d799aa19b7)

**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.480. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
I could not find this case

**Comment by bakuradzebakuradze** [comment]
the issue is closed
