### ISSUE TITLE
The bottom three pictures also belong to the patient Gotsiridze Gulkan, where Azerbaijan was entered as a foreign address and the system informed us that the information was successfully saved (several times), however, when opening the person's information, it appears that no information has been saved, and when opening the disease case related to this person, it is not visible at all These fields (neither empty nor filled)

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#777]
**Summary**
The bottom three pictures also belong to the patient Gotsiridze Gulkan, where Azerbaijan was entered as a foreign address and the system informed us that the information was successfully saved (several times), however, when opening the person's information, it appears that no information has been saved, and when opening the disease case related to this person, it is not visible at all These fields (neither empty nor filled)
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: Maka tsilosani
Build: 
Severity (MANDATORY): minor

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/b160f039-f69f-4890-a04a-cea211c243a5)
![i
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/9205b4a5-52cd-4723-ae00-03e5b310b7ec)
mage](https://github.com/EIDSS/EIDSS7/assets/128576431/12f7324f-df96-4d18-9d0d-485c483ded4c)

**Additional context**

**Comment by bakuradzebakuradze** [comment]
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/bb91f131-3e37-4563-8c30-9869ec6925ef)

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.480. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
I could not find this case the issue is closed
