### ISSUE TITLE
The foreign country entered and saved in the field "Exposure Location>Foreign Address/Country" (eg: Azerbaijan, Bangladesh, etc.) appears as Georgia when opening the case form.

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#779]
**Summary**
The foreign country entered and saved in the field "Exposure Location>Foreign Address/Country" (eg: Azerbaijan, Bangladesh, etc.) appears as Georgia when opening the case form.
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: 
Build: 
Severity (MANDATORY): minor

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/23a390e2-85a7-467a-91eb-c451269a3bd8)
**Additional context**

**Comment by herashchenkoa** [comment]
Can you please provide the exact steps that you are performing?
Do you open an existing Human Disease Report with an empty Foreign Address? And when you select any country then it appears as Georgia?

**Comment by bakuradzebakuradze** [comment]
Georgia is also on the list of foreign countries

**Comment by bakuradzebakuradze** [comment]
The issue is closed
