### ISSUE TITLE
AVR Layout and Query tree list failed to display for 2018 b Botulism in imereti  

### ISSUE THREAD

**Issue by shahina77** [EIDSS/EIDSS7#78]
**Summary**
Layout and Query tree list failed to display 
**To Reproduce**
1. Log in andrewpeters
2. Go to 
3. Click on 

**Expected behavior**

**Screenshots**

**Additional details:**
 - Build:80
 - Script title (enter ad hoc if not script-based):

**Issue severity**
Severity (critical, major, minor, low):
Critical
**Additional context**
AVr07
![AVR07](https://user-images.githubusercontent.com/52667472/60912608-bf7aeb80-a253-11e9-8436-0977178fc2b4.png)

**Comment by aatmns** [comment]
Reviewed and retested.
The custom-created 2018 Botulism Distribution in Imereti query is displaying properly in the Layout and Query Tree. 
There was an incorrect configuration for database in the logon "Database" tab.
This is already corrected as of 7/11/2019.
Recommend to close this item.
