### ISSUE TITLE
In the probable case classification of "anthrax - skin form", the same sentence is written twice - "and at least one of the following:"

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#780]
**Summary**
In the probable case classification of "anthrax - skin form", the same sentence is written twice - "and at least one of the following:"
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username:Maka tsilosani
Build: 
Severity (MANDATORY): minor

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/42cbe1b6-6193-4a8b-9f62-82500d77c980)
**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.411. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The problem has been resolved, This issue is closed
