### ISSUE TITLE
It would be nice if the fields that are filled in remain highlighted in green when previewing/viewing the case form. Gray or red that are not filled (all come out gray regardless of filling)

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#783]
**Summary**
It would be nice if the fields that are filled in remain highlighted in green when previewing/viewing the case form. Gray or red that are not filled (all come out gray regardless of filling)
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: Maka tsilosani
Build: 
Severity (MANDATORY): minor

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/f6395a75-aeca-414a-93f1-8fcde2e92cf2)

**Additional context**

**Comment by herashchenkoa** [comment]
Based on the meeting with GG WG on February 26, 2024, the issue is closed.
