### ISSUE TITLE
When opening the brucellosis case form I created for patient - Gotsiridze Gulkani, I found information that was not entered in my file (for example: outbreak ID, information related to the antibiotic, the persons who sent and received the message, samples). Maybe this information was added by another person or the system messed up the information (see 5 screenshot). I think, if possible, this fact should be reviewed and checked. However, it should be noted that the system does not allow me to add or change any new information in this case form (the fields are inactive, for example: the add sample button and others) (see images below)

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#784]
**Summary**
When opening the brucellosis case form I created for the patient - Gotsiridze Gulkani, I found information that was not entered in my file (for example outbreak ID, information related to the antibiotic, the persons who sent and received the message, and samples). Maybe this information was added by another person or the system messed up the information (see 5 screenshot). I think, if possible, this fact should be reviewed and checked. However, it should be noted that the system does not allow me to add or change any new information in this case form (the fields are inactive, for example the add sample button and others) (see images below)
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: Maka tsilosani
Build: 
Severity (MANDATORY): major

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/53d2d171-d604-4352-aaf2-fead6c41dc0f)
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/a324c529-f6ac-4dc5-afd1-bd0046605ad9)
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/d66c5d24-4038-4199-bb02-4e6c999a6480)
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/a2116ceb-d48a-4f69-9102-a42bd3518120)
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/14ae8846-acae-442c-a255-01064871bedd)
The bottom two images show that the data entry fields in the disease case form above are inactive
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/a7dd2a79-1fed-401b-ae9b-715f87908b33)
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/6306c5a8-ff8f-4b14-8b69-6c3c1ef4728f)

**Additional context**

**Comment by herashchenkoa** [comment]
It is possible to work on the same Human Disease Report by different users depending on their permissions. System does not add any information automatically. In order to make changes in the Human Disease Report, it shall be opened in the edit mode. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
This issue is closed
