### ISSUE TITLE
In the disease case (eg: anthrax) form, on the risk factor list page, the system automatically flags the answers if you accidentally click anywhere along the answer on that page (see image below)

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#785]
**Summary**
In the disease case (eg: anthrax) form, on the risk factor list page, the system automatically flags the answers if you accidentally click anywhere along the answer on that page (see image below)
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: Maka tsilosani
Build: 
Severity (MANDATORY): medium

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/be298aea-83b0-43a1-9fae-d97dd81ba73d)

**Additional context**

**Comment by bakuradzebakuradze** [comment]
Severity (MANDATORY): medium

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.411. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The problem has been resolved, This issue is closed
