### ISSUE TITLE
When looking at the person's information, it is not clear why outbreak cases are visible (shows 5 pages), when I have not created outbreaks on the cases of this person's disease, and if there are other outbreaks, I think they should not appear in this person's information (see the bottom image).

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#786]
**Summary**
When looking at the person's information, it is not clear why outbreak cases are visible (shows 5 pages), when I have not created outbreaks on the cases of this person's disease, and if there are other outbreaks, I think they should not appear in this person's information (see the bottom image).
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: 
Build: 
Severity (MANDATORY): critical

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/32f1ef4a-adb2-4447-8c77-b13279f6a414)

**Additional context**

**Comment by herashchenkoa** [comment]
This is expected behavior. If any of the Human Disease Reports have been added to the Outbreak, it will be visible on a patient card. Please verify to confirm that the issue is resolved.

**Comment by bakuradzebakuradze** [comment]
This issue is closed
