### ISSUE TITLE
ADR -> Farm Epi Information – ‘Other measure’ Section -> When selecting the value: Yes/No/Unk, it does not allow to select or close the drop-down list

### ISSUE THREAD

**Issue by schegelidze** [EIDSS/EIDSS7#792]
**Summary**
A clear and concise description of the issue.

**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: 
Build: 7.0.354.12
Severity (MANDATORY): Medium

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem.  Please blur or cover any personally identifiable information in any screenshots.

**Additional context**
![image](https://github.com/EIDSS/EIDSS7/assets/128593631/1e39ea61-833c-4224-bb0b-4bbb6fd02512)

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.411. Please verify to confirm that the issue was resolved.

**Comment by schegelidze** [comment]
It is fixed
