### ISSUE TITLE
If you did not enter all the information from the beginning when creating the samples (eg: date of sampling, sampling and receiving institution, sampling person), the system does not allow you to add or correct the entered information (there is no edit button). However, the institution receiving the sample, the date the sample was sent and received does not appear on the final page of the list of samples collected (see the image below).

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#800]
**Summary**
If you did not enter all the information from the beginning when creating the samples (eg: date of sampling, sampling and receiving institution, sampling person), the system does not allow you to add or correct the entered information (there is no edit button). However, the institution receiving the sample, and the date the sample was sent and received does not appear on the final page of the list of samples collected (see the image below).
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: maka tsilsoani
Build: 
Severity (MANDATORY): important

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/9b553328-89b8-4c47-8b41-9018f4daed1c)

**Additional context**

**Comment by herashchenkoa** [comment]
It is possible to edit the Human Disease Report (HDR) including sample details when HDR is opened in the edit mode. On a sample tab, it is needed to move the slicer to the right side and click on the edit icon. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The issue is not resolved

**Comment by bakuradzebakuradze** [comment]
Accession Date does not work
![date](https://github.com/user-attachments/assets/1c3e8706-1000-4bb7-9e6b-a510579daa69)

**Comment by TulendinovT** [comment]
It is right behaviour becoouse Accession Date in this form is not editable, date value in this field is imputed automatically when this sample will accepted in lab module.

**Comment by bakuradzebakuradze** [comment]
The issue is closed
