### ISSUE TITLE
ADR – Farm Epi Information - Forms are different on EN and GG (e.g. ID: VETTBTBZ230G6G) 

### ISSUE THREAD

**Issue by schegelidze** [EIDSS/EIDSS7#804]
**Summary**
A clear and concise description of the issue.

**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: 
Build: 7.0.354.12
Severity (MANDATORY): major

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem.  Please blur or cover any personally identifiable information in any screenshots.
![image](https://github.com/EIDSS/EIDSS7/assets/128593631/da222f4e-fccc-40f8-9725-6f99dedde898)
![image](https://github.com/EIDSS/EIDSS7/assets/128593631/098a52db-61d3-4e20-a9c9-a3c1b36886f7)

**Additional context**

**Comment by herashchenkoa** [comment]
The bug fix was addressed in EIDSSv7 build 7.0.402.

**Comment by schegelidze** [comment]
it fixed
