### ISSUE TITLE
LDR -> Livestock Epi Form, the fields are placed in a wrong order

### ISSUE THREAD

**Issue by schegelidze** [EIDSS/EIDSS7#807]
**Summary**
A clear and concise description of the issue.

**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: 
Build: 7.0.354.12
Severity (MANDATORY): major

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem.  Please blur or cover any personally identifiable information in any screenshots.
![image](https://github.com/EIDSS/EIDSS7/assets/128593631/a0cf3a1a-7163-4bec-9e53-211f2bfb4c6a)
![image](https://github.com/EIDSS/EIDSS7/assets/128593631/4839fe99-dd34-4823-8e22-51708ff79c85)
![image](https://github.com/EIDSS/EIDSS7/assets/128593631/ae4ec296-5645-4d98-a9a8-0dbf7e468a5a)

**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.411. Please verify to confirm that the issue was resolved.

**Comment by schegelidze** [comment]
It is fixed
