### ISSUE TITLE
There are 2 records of Farm with the same ID? For example - FGEIMTS208001Y and no value in the fields ‘Date Entered ‘. Migration-related issue? 

### ISSUE THREAD

**Issue by schegelidze** [EIDSS/EIDSS7#811]
**Summary**
A clear and concise description of the issue.

**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username:
Build: 7.0.402
Severity (MANDATORY): Hight

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem.  Please blur or cover any personally identifiable information in any screenshots.
![image](https://github.com/EIDSS/EIDSS7/assets/128593631/367de8a2-e49f-48f9-bfd4-88f283c902f7)
![image](https://github.com/EIDSS/EIDSS7/assets/128593631/5cc0126e-fbd9-4051-aca7-8893045f6085)

**Additional context**

**Comment by schegelidze** [comment]
it didn't fixed

![2023-11-09_14-37-54](https://github.com/EIDSS/EIDSS7/assets/128593631/691db023-b68c-4a8e-844f-fc09aaa33608)

**Comment by herashchenkoa** [comment]
Based on the user's feedback, the issue is resolved, the bug is closed.
