### ISSUE TITLE
VAR10: Create Vet Aggregate Action Summary -> does not count summary at Treatment-prophylactic and vaccination measures

### ISSUE THREAD

**Issue by schegelidze** [EIDSS/EIDSS7#817]
**Summary**
A clear and concise description of the issue.

**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: 
Build: 7.0.354.12
Severity (MANDATORY): High

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem.  Please blur or cover any personally identifiable information in any screenshots.
![image](https://github.com/EIDSS/EIDSS7/assets/128593631/b5470b73-81b2-4372-b700-3f749e0e8c9a)
![image](https://github.com/EIDSS/EIDSS7/assets/128593631/f8e98a26-28cb-4610-b809-b749f832eb6b)
![image](https://github.com/EIDSS/EIDSS7/assets/128593631/bd2d76c4-cf8e-4852-8237-63f55285142a)
![image](https://github.com/EIDSS/EIDSS7/assets/128593631/f46611a3-628c-4ee4-9352-daa0f735f754)
![image](https://github.com/EIDSS/EIDSS7/assets/128593631/f5f36c4c-2bad-4a95-88c1-575e25a441c2)

**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.411. Please verify to confirm that the issue was resolved.

**Comment by schegelidze** [comment]
Imposible to test , because we cant find our created agregated action reports in system. I think it is not saving it when we are creating

**Comment by herashchenkoa** [comment]
During testing, all the cases were successfully found. Please make sure that during search you use the correct search criteria. 
Note: if you put dates in Start Date and End Date, make sure you enter 1st day and last day of the month for Time Interval Unit: Month. Please also try to perform search without specifying Start Date and End Date. Please verify the bug again and let us know the result.

**Comment by schegelidze** [comment]
Thank you, Anastasia,
We will check it.
I am happy you are back ^_^

Best regards,
Saba

**Comment by schegelidze** [comment]
It is fixed
