### ISSUE TITLE
ASS -> When ASS is saved and user clicks on return to ASS, the user is kicked off

### ISSUE THREAD

**Issue by schegelidze** [EIDSS/EIDSS7#821]
**Summary**
A clear and concise description of the issue.

**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: 
Build: 7.0.354.12
Severity (MANDATORY): High

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem.  Please blur or cover any personally identifiable information in any screenshots.
![image](https://github.com/EIDSS/EIDSS7/assets/128593631/2998f3c0-37df-4355-ac9b-20454ac0339f)
![image](https://github.com/EIDSS/EIDSS7/assets/128593631/5203a57f-a0c8-47e2-83cf-6f0d03ae9a12)

**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.411. Please verify to confirm that the issue was resolved.
