### ISSUE TITLE
Review Screen Did Not Display a Red X Beside Notification Label.

### ISSUE THREAD

**Issue by srbatni** [EIDSS/EIDSS7#84]
**Summary**
When reviewing the information I had entered in the disease field, the review screen did not display a red X beside the notification label as noted in the script.

**To Reproduce**
1. Log in as: russellpeters
2. Go to: Human, person
3. Click on: Review

**Expected behavior**
The system displays a red X beside the Notification label in the Navigation bar.

**Screenshots**
![image](https://user-images.githubusercontent.com/52708365/60974593-327d7400-a2df-11e9-9155-99f2dfe94bf9.png)

**Additional details:**
 - Build: 81
 - Script title (enter ad hoc if not script-based): HPS07

**Issue severity**
Severity (critical, major, minor, low):

**Additional context**

**Comment by jkkannan** [comment]
Verified that this defect is reproducible in Integration.
