### ISSUE TITLE
The electronic system allows us to record and remember the identity even if "unknown" is selected (it is desirable that the field for entering the identity becomes inactive if "unknown" is selected, as it was in the previous version)

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#840]
**Summary**
The electronic system allows us to record and remember the identity even if "unknown" is selected (it is desirable that the field for entering the identity becomes inactive if "unknown" is selected, as it was in the previous version)
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: maka tsilosani
Build: 
Severity (MANDATORY): Minor

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/922f6165-9a1d-4c79-be86-06c211f53a85)

**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.427. Please verify to confirm that the issue was resolved.
