### ISSUE TITLE
In patient Gotsiridze Gulkani's "Anthrax - skin form" case form, on the page - "Case investigation detailed information" in the existing field - "(location of exposure>foreign address) country" is unclear from the database, the memorized word "Georgia" was found, while in the drop-down list of this field there is only The list of foreign countries (in English) and as a rule the field with a drop-down list should not allow memorization of manually entered information

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#842]
**Summary**
patient Gotsiridze Gulkani's "Anthrax - skin form" case form, on the page - "Case investigation detailed information" in the existing field - "(location of exposure>foreign address) country" is unclear from the database, the memorized word "Georgia" was found, while in the drop-down list of this field, there is only The list of foreign countries (in English) and as a rule, the field with a drop-down list should not allow memorization of manually entered information
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: Maka tsilosani
Build: 
Severity (MANDATORY): medium

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/5a03a651-6f89-4944-819f-0c1e64dbc9f7)
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/4002cf8b-ce0d-49a8-9b57-0338404ad300)

**Additional context**

**Comment by bakuradzebakuradze** [comment]
Severity (MANDATORY): medium

**Comment by herashchenkoa** [comment]
In the HDR -> field - "location of exposure>foreign address, only a drop-down list is available for selecting values. No manually entered information is saved in the field. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
In our opinion, Georgia should not be in the list of foreign addresses
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/36c08d93-dfc8-4bfb-be59-ed9fa9eb503d)

**Comment by bakuradzebakuradze** [comment]
I think we should discuss this issue during a video call

**Comment by bakuradzebakuradze** [comment]
The issue is closed
