### ISSUE TITLE
When performing a search in the following order: "Person" - "Search criteria" in the received "search result", clicking on the column headings: "Name" and "Region" does not sort the information in alphabetical order. Also, cases are not sorted alphabetically when searching for "Human Disease Report" by clicking on the column heading - "Case Classification" in the search result

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#844]
**Summary**
When performing a search in the following order: "Person" - "Search criteria" in the received "search result", clicking on the column headings: "Name" and "Region" does not sort the information in alphabetical order. Also, cases are not sorted alphabetically when searching for "Human Disease Report" by clicking on the column heading - "Case Classification" in the search result
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: maka tsilosani
Build: 
Severity (MANDATORY): Minor

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/734fc5c6-f5eb-44c3-82c1-c24ee3381be1)
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/ddeeeb2a-fc95-4836-b670-749c49ba8b93)

**Additional context**

**Comment by bakuradzebakuradze** [comment]
When performing a search in the following order: "Person" - "Search criteria" in the received "search result", clicking on the column headings: "Name" does not work  The rest have been fixed

**Comment by TulendinovT** [comment]
Will check with Zurab on UAT env

**Comment by bakuradzebakuradze** [comment]
The issue is closed
