### ISSUE TITLE
It is not known how to change the patient's initial diagnosis to the final diagnosis and whether the system has the ability to do so (without creating a new case). If this feature is not provided, we think it is necessary to have a complete picture regarding this particular case history.

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#845]
**Summary**
It is not known how to change the patient's initial diagnosis to the final diagnosis and whether the system has the ability to do so (without creating a new case). If this feature is not provided, we think it is necessary to have a complete picture regarding this particular case history.
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: Maka tsilosani
Build: 
Severity (MANDATORY): major

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem.  Please blur or cover any personally identifiable information in any screenshots.

**Additional context**

**Comment by TulendinovT** [comment]
Logic of Connecting DR is removed, the bug should be obsolete and closed. Could you please confirm.

**Comment by bakuradzebakuradze** [comment]
The issue is closed
