### ISSUE TITLE
1.	Data from field “Facility patient first sought care” is not migrated. Type of this field in v7 is drop down menu and in v6 is text field.

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#857]
### Country

Georgia

### Username

bakuradze

### Build number

7.0.402

### Language

None

### Severity (MANDATORY)

1 - Critical

### Module

Human

### Description of the steps to reproduce

Step: HDR>Clinical Information-Facility> Facility patient first sought care
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/fc7147e8-89eb-459f-a37d-fa0b1b1df5aa)

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.480. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
the issue is closed
