### ISSUE TITLE
Patient does not appear on the list to select for sample destruction 

### ISSUE THREAD

**Issue by Chavez34** [EIDSS/EIDSS7#86]
**Summary**

Patient does not appear on the list to select for sample destruction 

**To Reproduce**

1. Log in as mollyrue
2. Go to Select Laboratory>Samples:  John  Smith is not present on the list for sample destruction.

**Expected behavior**
Patient should appear on the list in order to mark for sample destruction.

**Screenshots**
![image](https://user-images.githubusercontent.com/52667706/60974834-cad42280-a2f8-11e9-91cb-67f66d2a2330.png)

**Additional details:**
 - Build: 81
 - Script title: LAB16 Mark a sample for destruction

**Issue severity**
Severity:  Major

**Additional context**
None

**Comment by christhompson17** [comment]
Data team needs to confirm if this is missing GAT data, or if "John Smith" is in the DB and not displaying. Likely a GAT data issue.
