### ISSUE TITLE
In the process of working in human>person> It did not allow me to add a person. adding button went grey

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#864]
### Country

Georgia

### Username

bakuradze

### Build number

7.0.402

### Language

None

### Severity (MANDATORY)

3 - Medium

### Module

None

### Description of the steps to reproduce

In the process of working in human>person> It did not allow me to add a person. adding button went grey
![არ მამატებინებს პიროვნებას](https://github.com/EIDSS/EIDSS7/assets/128576431/1e4c15cf-177f-43b1-9beb-1ffc9e0fd88f)

**Comment by herashchenkoa** [comment]
Verify that the user is not using Archive mode, as it is not possible to create a new record when connecting to the Archive module.

**Comment by bakuradzebakuradze** [comment]
This issue is closed
