### ISSUE TITLE
Translation> Human Disease Report> Notification>current location of patient> should be 	Home > “სახლში“ 	Hospital > “საავადმყოფო“ 	Other > “სხვა“ 	Unknown > ‘’უცნობია“

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#867]
### Country

Georgia

### Username

bakuradze

### Build number

7.0.402

### Language

None

### Severity (MANDATORY)

4 - Low

### Module

None

### Description of the steps to reproduce

Translation> Human Disease Report> Notification>current location of patient> should be
•	Home > “სახლში“
•	Hospital > “საავადმყოფო“
•	Other > “სხვა“
•	Unknown > ‘’უცნობია“
![სად იმყოფება პაციენტი](https://github.com/EIDSS/EIDSS7/assets/128576431/883d17da-4074-4923-a4a1-f8254a972f08)

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.411. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The issue is not res
<img width="929" alt="Screenshot 2023-12-22 124055" src="https://github.com/EIDSS/EIDSS7/assets/128576431/0c4873f7-bc8e-47c6-8f03-1b49f6ee6d72">
olved

**Comment by bakuradzebakuradze** [comment]
The issue is not resolved

**Comment by TulendinovT** [comment]
It is ready for testing

**Comment by bakuradzebakuradze** [comment]
The issue is resolved
