### ISSUE TITLE
An error occurred while working 

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#868]
### Country

Georgia

### Username

bakuradze

### Build number

7.0.402

### Language

Georgian

### Severity (MANDATORY)

2 - High

### Module

Human

### Description of the steps to reproduce

![მუშაობის პროცესში გაითიშა](https://github.com/EIDSS/EIDSS7/assets/128576431/1ed3aa29-67b8-4140-aed9-1aebe4be1de7)

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.411. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
this issue is closed
