### ISSUE TITLE
System Timed Out

### ISSUE THREAD

**Issue by srbatni** [EIDSS/EIDSS7#87]
**Summary**
After hitting submit for a record I had just reviewed, the system timed out to the login screen. Had to reenter script information as none was retained.

**To Reproduce**
1. Log in as: russellpeters 
2. Go to: Human, Person 
3. Click on: Review 

**Expected behavior**
Should have been allowed to submit form and continue with script, but system timed out with none of previously entered information saved.

**Screenshots**

![image](https://user-images.githubusercontent.com/52708365/60974933-d830e300-a2df-11e9-9ecd-4bb004a8f6f5.png)

**Additional details:**
 - Build: 81
 - Script title (enter ad hoc if not script-based): HPS07

**Issue severity**
Severity (critical, major, minor, low): Critical

**Additional context**

**Comment by christhompson17** [comment]
This is an intermittent issue that is difficult to recreate, but we can confirm that we have seen this behavior multiple times in the GAT environment.
