### ISSUE TITLE
ADM16 - Missing "Human Clinical Signs" 

### ISSUE THREAD

**Issue by Aj-Kakar** [EIDSS/EIDSS7#88]
**Summary**
Missing "Human Clinical Signs" under the flexible form, might be a script issue but need to confirm. However, there are two item listed as clinical sign. Please review the script with the system, multiple discrepancies. 

**To Reproduce**
1. Log in as rykermase
2. Go to Flexible Form Parameter
3. Scroll through the list for human clinical signs 

**Expected behavior**
Human Clinical signs should be listed under the flexible based on the script.

**Screenshots**

**Additional details:**
 - Build: 81
 - Script title: ADM 16 

**Issue severity**
Minor, however able to complete the testing based on the discrepancies. 

**Additional context**
Please review all the listed throughout the system and check for sorting/searching functionality. It is extremely difficult to find link to pages.

**Comment by christhompson17** [comment]
Not a bug, incorrect label in script. Instead of "Human Clinical Signs", it should be under "Clinical Signs", should be able to re-test.
