### ISSUE TITLE
No disease warning was displayed after clicking submit

### ISSUE THREAD

**Issue by srbatni** [EIDSS/EIDSS7#89]
**Summary**
After clicking submit control (Step 11 in script), I should have received the following Disease Warning notification "Disease value is not valid" below the Disease data field but it was not there.

**To Reproduce**
1. Log in as: russellpeters 
2. Go to: Human Person Report Summary
3. Click on Submit

**Expected behavior**
I should have received a Disease Warning notification "Disease value is not valid" below the Disease data field

**Screenshots**
![image](https://user-images.githubusercontent.com/52708365/60975518-fc40f400-a2e0-11e9-90d9-ddb0a935ae6a.png)

**Additional details:**
 - Build: 81
 - Script title (enter ad hoc if not script-based): HPS07

**Issue severity**
Severity (critical, major, minor, low): Major

**Additional context**

**Comment by jkkannan** [comment]
Confirmed that this defect is reproducible in Integration.
