### ISSUE TITLE
[BUG] Unable to find disease report and open to edit HPS

### ISSUE THREAD

**Issue by shahina77** [EIDSS/EIDSS7#9]
**Summary**
Abigail Adams Measles report fail to display 
**To Reproduce**
1. Log in as Russell Peters
2. Select Human --> Disease Report 
3. Search for Abigail Adams, rayon = blank, disease = measles
4. List of human disease reports matching search parameters was not displayed; was not able to execute further steps in script

**Expected behavior**
User is able to open disease report and edit to add contact.

Screenshots**

**Additional details:**
 - Build: 77
 - Script title (enter ad hoc if not script-based): HPS05

**Issue severity**
Severity (critical, major, minor, low): 
Critical
![russellpeter 2](https://user-images.githubusercontent.com/52667472/60827765-f03d2100-a17e-11e9-9104-835ea070ee80.png)

**Additional context**

**Comment by jkkannan** [comment]
Changed to data issue as it appears the disease report referenced in script was not entered. Leaving critical and bug labels for now.

**Comment by jkkannan** [comment]
Closed during GAT remediation as this was a script issue.
