### ISSUE TITLE
System would not allow me to enter valid disease name Acute Viral Hepatitis A

### ISSUE THREAD

**Issue by srbatni** [EIDSS/EIDSS7#90]
**Summary**
When went back to form to change disease value from 15-49 years... to Acute Viral Hepatitis A, the field had a red circle and would not allow me to change the disease.

**To Reproduce**
1. Log in as russellpeters
2. Go to Human Person
3. Click on Disease

**Expected behavior**
Should have been able to change disease value from "15-49..." to "Acute Viral..."
**Screenshots**
![image](https://user-images.githubusercontent.com/52708365/60976095-f4358400-a2e1-11e9-9b34-e2606dc318f2.png)

**Additional details:**
 - Build: 81
 - Script title (enter ad hoc if not script-based): HPS07

**Issue severity**
Severity (critical, major, minor, low): Major

**Additional context**

**Comment by jkkannan** [comment]
Not a bug; due to system saving the record successfully in related ticket and then the disease cannot be changed per EIDSS requirements. Requires retest after validation fix.
