### ISSUE TITLE
Human Disease Report >Employment/School> Country is written instead of Occupation

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#903]
### Country

Georgia

### Username

bakuradze

### Build number

7.0.411 

### Language

Georgian

### Severity (MANDATORY)

3 - Medium

### Module

Human

### Description of the steps to reproduce

Human Disease Report >Employment/School> Country is written instead of Occupation see screenshot
![საქმიანობაზე წარწერა ქვეყანა](https://github.com/EIDSS/EIDSS7/assets/128576431/b34ebfa0-1013-4a2e-823d-c3b7cbb8568f)

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.480. Please verify to confirm that the issue was resolved.
