### ISSUE TITLE
EIDSS Dashboard Error Message at End of Script

### ISSUE THREAD

**Issue by srbatni** [EIDSS/EIDSS7#91]
**Summary**
At end of script, I selected Return to Dashboard and received an error notification (see screenshot below). 
**To Reproduce**
1. Log in as russellpeters
2. Go to Human Person
3. Click on Submit notification

**Expected behavior**
The epidemiologist dashboard displays.

**Screenshots**

![image](https://user-images.githubusercontent.com/52708365/60976571-cc92eb80-a2e2-11e9-83ee-4810346368f2.png)

**Additional details:**
 - Build: 81
 - Script title (enter ad hoc if not script-based): HPS07

**Issue severity**
Severity (critical, major, minor, low): Critical

**Additional context**

**Comment by jkkannan** [comment]
Confirmed as an intermittent issue across testers.

**Comment by EBH2001** [comment]
Reproducible in Integration build 83.3.

PLEASE SEE ATTACHMENT

![image](https://user-images.githubusercontent.com/16134915/61292062-3b1df080-a79e-11e9-845f-dbbb5f1d4559.png)
