### ISSUE TITLE
ADMN20 - Species and Vector List

### ISSUE THREAD

**Issue by Aj-Kakar** [EIDSS/EIDSS7#95]
**Summary**
Script asked me to update the stray dog field and save my changes. Later the script asked me to verify if cattle was record was added. Also, I can't find my stray dog changes.

**To Reproduce**
1. Log in as rykermase
2. Go to Admin > Reference Editor > Species Types
3. Edit species > Dog (Stray)

**Expected behavior**
The system should allow me to update my species submission and save my changes.

**Screenshots**
None

**Additional details:**
 - Build: 81
 - Script title (enter ad hoc if not script-based): ADM20

**Issue severity**
Minor

**Additional context**
Please review the details in the script with the system.

**Comment by jkkannan** [comment]
Closed during remediation.  Script passed and user was able to retrieve species.
