### ISSUE TITLE
HDR: Clinical Info - Facility Details Tab - Fields default to No when they should be blank

### ISSUE THREAD

**Issue by herashchenkoa** [EIDSS/EIDSS7#962]
### Country

Georgia

### Language

None

### Severity (MANDATORY)

None

### Module

None

### Description of the steps to reproduce

Human Disease Report | Clinical Information: Faciity Details | Fields default to No when they should be blank
Expected Result: Yes/No/Unknown shall be empty by default

**Comment by bakuradzebakuradze** [comment]
The issue is closed

![image](https://github.com/EIDSS/EIDSS7/assets/128576431/b6780f18-d3b0-4e54-bb4a-6e7ffe3cdd7f)

**Comment by TulendinovT** [comment]
Closed by previous comment from users
