### ISSUE TITLE
VPS 04 drop down menus duplications

### ISSUE THREAD

**Issue by jeanmrichards** [EIDSS/EIDSS7#97]
**Summary**
step 15 when entering the vaccination information - there are 2 options for foot and mouth disease (both say FMD exactly the same) and 3 options when you go to enter "cattle" that all say cattle.

**To Reproduce**
1. Log in as ryan johnson
2. Go to enter vaccination info after finding b abortus disease record
3. Click on vacc info tab and try to choose foot and mouth disaease for disease name and cattle for species

**Expected behavior**
should only see FMD once and cattle once

**Screenshots**

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based):

**Issue severity**
Severity (critical, major, minor, low): low

**Additional context**

**Comment by jkkannan** [comment]
Reproducible in GAT.

**Comment by EBH2001** [comment]
Issue was reproduced in Integration 83.4

**PLEASE SEE ATTACHMENT**

[VPS04_GitHub#97_Investigation_livestock_Brucellosis_Reproducible.docx](https://github.com/EIDSS/EIDSS7/files/3402923/VPS04_GitHub.97_Investigation_livestock_Brucellosis_Reproducible.docx)
