### ISSUE TITLE
Verification Status: An In progress record for Edward Talbot was not found

### ISSUE THREAD

**Issue by srbatni** [EIDSS/EIDSS7#98]
**Summary**
Could not find an in progress report for editing Edward Talbot was not found when logged in as Russell Peters. 

**To Reproduce**
1. Log in as: russellpeters
2. Go to: Human Disease Reports , enter Edward Talbot 
3. Click on Search

**Expected behavior**
An in process record for Edward Talbot was not found. Only a closed record exists. Could not complete step 6 in script.

**Screenshots**
![image](https://user-images.githubusercontent.com/52708365/60979800-2fd34c80-a2e8-11e9-9d39-2ff0a69905e8.png)

**Additional details:**
 - Build: 81
 - Script title (enter ad hoc if not script-based): HSP08

**Issue severity**
Severity (critical, major, minor, low):

**Additional context**

**Comment by jkkannan** [comment]
Bug due to failed step previously.
