### ISSUE TITLE
HDR: Tests Tab - 'Tests conducted' radio button default state is "No" AND Tests + control is not enabled

### ISSUE THREAD

**Issue by herashchenkoa** [EIDSS/EIDSS7#986]
### Country

Georgia

### Language

None

### Severity (MANDATORY)

None

### Module

None

### Description of the steps to reproduce

HDR | Tests conducted Radio button defaults to "No" AND Tests + control is not enabled
Expected Result: Yes/No/Unknown shall be empty by default

**Comment by herashchenkoa** [comment]
This issue was identified during UAT Training conducted in June 2023 and added to GitHub for proper records tracking.

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.480. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
Problem solved, I just can't close it

**Comment by herashchenkoa** [comment]
Based on the user's feedback, the issue is closed.
