### ISSUE TITLE
Human disease report clinical information-facility details patient previously sought care for similar symptoms automatically No is marked Hospitalization No is marked which should not be marked 

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#989]
### Country

Georgia

### Username

bakuradze

### Build number

7.0.411 

### Language

Georgian

### Severity (MANDATORY)

4 - Low

### Module

Human

### Description of the steps to reproduce

Human disease report clinical information-facility details patient previously sought care for similar symptoms automatically No is marked Hospitalization No is marked which  should not be marked 
![დაწესებულების დეტალები](https://github.com/EIDSS/EIDSS7/assets/128576431/e927d71a-75ac-4873-bd85-71e0e5a812c2)

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.480. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
the issue is closed
