### ISSUE TITLE
The save data button should be easily accessible as it is in version 6, since the program is often closed and the recorded data is lost.

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#990]
### Country

Georgia

### Username

bakuradze

### Build number

7.0.411 

### Language

Georgian

### Severity (MANDATORY)

4 - Low

### Module

Human

### Description of the steps to reproduce

The save data button should be easily accessible as it is in version 6, since the program is often closed and the recorded data is lost.
![save](https://github.com/EIDSS/EIDSS7/assets/128576431/0d567bba-a476-48e2-bd57-b36d38c05fcd)

**Comment by TulendinovT** [comment]
[Save] button presented on the bottom side of navigation bar

**Comment by bakuradzebakuradze** [comment]
The issue is closed
